### ISSUE TITLE
support mongodb 3.4?

### ISSUE THREAD

**Issue by luisdavim** [bitnami/bitnami-docker-mongodb#100]
would it be possible to have images for mongodb 3.4?

**Comment by carrodher** [comment]
We had it in the past, but it was deprecated a few months ago.

Anyway, you can find it in the GitHub releases history:
https://github.com/bitnami/bitnami-docker-mongodb/tags?after=3.6.0-r0

The first non-3.4.X release was `3.6.0-r0`, so searching the previous one you can find all the `3.4.X` releases. I hope this can help you

**Comment by luisdavim** [comment]
Why was it deprecated? 3.4 didn't reach EOL yet will you only support two versions at a time?
In fact I'm using the [mongodb helm chart](https://github.com/kubernetes/charts/tree/master/stable/mongodb) that uses this image and I need mongodb 3.4.x I guess I'll have to build an image myself from your old release....

any alternative suggestions?

Thanks for your reply.

**Comment by dwitzig** [comment]
any news on this? 
im hoping to use the Bitnami MongoDB helm chart however i am confined to version 3.4 

setting featureCompatibilitySet to 3.4 does not resolve the requirement for cursor or explain in aggregate query since 3.6

I have tried setting bitnami/mongodb:3.4.9-r1 in the helm values. I get the following error 
```
INFO ==> Starting mongod...
error: failed switching to "mongo": unable to find user mongo: no matching entries in passwd file
```

Have also tied building my own docker image based off the 3.6 image changing 
`RUN bitnami-pkg unpack mongodb-3.6.8-4 ` to `RUN bitnami-pkg unpack mongodb-3.4.10-1`
it can't to find the package (3.4.10-1 is last 3.4 version mentioned in the package change log https://bitnami.com/stack/mongodb/changelog.txt)
```
INFO  ==> Downloading mongodb-3.4.10-1-linux-amd64-debian-9 package
curl: (22) The requested URL returned error: 404
WARN  ==> Package name 'mongodb-3.4.10-1-linux-amd64-debian-9' does not exist, will try 'mongodb-3.4.10-1-linux-amd64'...
curl: (22) The requested URL returned error: 404
ERROR ==> Could not find the requested package...
The command '/bin/sh -c bitnami-pkg unpack mongodb-3.4.10-1' returned a non-zero code: 1
```

**Comment by carrodher** [comment]
Hi, at this moment we are supporting three versions:
- `3.6` for the branch `3`
- `4.0` as the stable version
- `4.1` as the dev version

If you need to use the `3.4` version you can go back in the git history and build the `3.4` image:
```bash
# Clone the repository
$ git clone git@github.com:bitnami/bitnami-docker-mongodb.git && cd bitnami-docker-mongodb

# Go to the last 3.4 image
$ git checkout f1bf9fdee69b01f6c47545c32da090e4a933edd8

# Find the 3.4 Dockerfile
$ cd 3
$ cat Dockerfile

# Build and tag it
$ docker build . -t mongodb-3.4:latest
```
After that you should be able to use this image, I used it with `docker-compose`:
```diff
-    image: 'bitnami/mongodb:3'
+    image: mongodb-3.4:latest
```
```bash
$ docker-compose up

$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                      NAMES
6c4ecc515a9d        mongodb-3.4:latest   "/app-entrypoint.sh …"   23 seconds ago      Up 21 seconds       0.0.0.0:27017->27017/tcp   3_mongodb_1

$ docker exec -it 6c4ecc515a9d bash
root@6c4ecc515a9d:/# mongo --version
MongoDB shell version v3.4.10
git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```

**Comment by Bessonov** [comment]
No need to build image. Use

```
mongodb:
  image:
    tag: 3.4.10-r0
```

in `values.yaml`.

Furthermore, I've debugged problem of @dwitzig . If you look at [kubernetes.yml](https://github.com/bitnami/bitnami-docker-mongodb/blob/f1bf9fdee69b01f6c47545c32da090e4a933edd8/kubernetes.yml), then you can see that there is no securityContext to run the container as user 1001.

In fact, run `nami` as non root user gives:

```
$ nami --log-level debug inspect mongodb
Cannot find any module matching the provided specification 'mongodb'
```

But as root:

```
# nami --log-level trace inspect mongodb
{
  "id": "com.bitnami.mongodb",
  "name": "mongodb",
  "version": "3.4.10",
  "revision": "0",
  "installedAsRoot": true,
[...]
```

In other words: 3.4 image was intended to run as root and it's incompatible with default helm chart values. To adjust that you must disable security context:

```
mongodb:
  securityContext:
    enabled: false
```

or go deeper.

Cheers! :beer:
