### ISSUE TITLE
Ability to use hostnames for replicaset?

### ISSUE THREAD

**Issue by dennybaa** [bitnami/bitnami-docker-mongodb#105]
Is it possible to have DNS names for replicaset configuration?

https://github.com/helm/charts/issues/7075

**Comment by juan131** [comment]
I think you're looking for **MONGODB_ADVERTISED_HOSTNAME** environment variable. See https://github.com/bitnami/bitnami-docker-mongodb#setting-up-a-replication

However, this can't be specified on the chart yet as you can check at:

https://github.com/helm/charts/blob/master/stable/mongodb/templates/statefulset-primary-rs.yaml

We should find a way to set this env. variable dynamically...

Any thoughts @tompizmor ?

**Comment by dennybaa** [comment]
@juan131 cool clue, thanks I will insert this variable into the chart, and see if it will work with the container. I'll update you.

**Comment by dennybaa** [comment]
@juan131 @tompizmor Any idea how, since I haven't found a clear way to do so.

We can fetch pod name from the env source.
```
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
```

Though a compound variable is needed `{{ POD_NAME }}.{{ template "mongodb.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local`

I'm still new to K8S, what's the best approach to do it? I'm just thinking to use init containers, which seems kinda awkward :(

**Comment by dennybaa** [comment]
@juan131 @tompizmor It should work but it doesn't seem too. Check this out:

![Failure](https://i.gyazo.com/ef8910141b1e95ddcecf58420016f125.png)

**Comment by dennybaa** [comment]
sorry to early, still testing.

**Comment by dennybaa** [comment]
sorry to early, was testing. @juan131 @tompizmor here are the results:

I've tested the configuration with `MONGODB_ADVERTISE_HOSTNAME`. It seems with a little readiness tuning replicaset is created successfully! **So ability to pass hostname exists and can be resolved in the k8s chart**.

Though, I can't see stable operation of the chart yet, should we continue here or move a new issue to k8s charts repo?

Failure scenario: 1 - primary, 1 - arbiter, 1 - secondary with replicaset.enabled = true.

1) deleting arbiter/secondary pods *has no issues*.
2) deleting primary pod makes it leave replicaset forever!

How do you guys use the k8s chart (though maybe you don't...) Would you please give some details on how this can even work:

As I understand `MONGODB_PRIMARY_HOST` points to mongodb service with `ClusterIP` which always resolved into one primary node! After **primary pod** failure secondary becomes PRIMARY, however when it goes up there's no single chance for **the previous primary pod** to get back into the cluster even if we provide `MONGODB_PRIMARY_HOST` variable since it will point nowhere...

**Comment by dennybaa** [comment]
@tompizmor @juan131 I went on and created this PR https://github.com/helm/charts/pull/7096 to leverage `MONGODB_ADVERTISE_HOSTNAME`. ReplicaSet is indeed configured with the hostnames as Tomas says. Thank you guys again for the awesome containers, charts and assistance!

Though I've got a bunch of questions on how RS might actually survive after killing/deleting various pods from the replica set.

**Comment by juan131** [comment]
Hi @dennybaa 

I'm taking a look to the PR. Thanks so much for this contribution.

**Comment by dennybaa** [comment]
Guy, howdy! When you have time I kindly ask you to give any suggestions on https://github.com/bitnami/bitnami-docker-mongodb/issues/105#issuecomment-411409922. Maybe when can open up another issue for that discussions?

**Comment by juan131** [comment]
Hi @dennybaa 

I'd rather open a new thread to discuss it. It's much better in order to avoid confusion to stick to the point of each issue.

Thanks so much in advance. proceed to close this issue since the PR was already accepted and merged!
