### ISSUE TITLE
Replica set mode enabled usage on K8S

### ISSUE THREAD

**Issue by dennybaa** [bitnami/bitnami-docker-mongodb#107]
Howdy, bitnami!

I'd like to discuss scenarios of using `replicaSet.enabled = true` on K8S in production. mongodb helm upgrade for instance a version bump `image.tag` to a new version can not be performed _without failing the replica set_.

1. Arbiter/master/secondary upgrade order?
   Is there any predictable upgrade order for pods with the current chart? What I can see master/secondary/arbiter are shutdown simultaneously and go back up the same way.
2. Since the startup order on upgrade is unpredictable (at least seems to me) secondary might become master and master can be removed from the replica set. Even if the replica set uses hostnames with the recent PR https://github.com/helm/charts/pull/7096, it get's broken anyways. Is mongodb able survive pod failures with any configuration which can mongodb chart provide?
3. Do you use any sidecar (ex: https://github.com/cvallance/mongo-k8s-sidecar) to run mongodb on k8s in production environments?

**Comment by juan131** [comment]
Hi @dennybaa 

I'd like @tompizmor to take a look to this interesting scenario you're describing since he has more expertise on this MongoDB chart. He might be unable to take a look today but I'll ping him so he does it tomorrow. Thanks for bringing this up!

**Comment by tompizmor** [comment]
Hello @dennybaa,

I will try to reply the questions.

1. As you mention there is no upgrade order. So if you run `helm upgrade` all the pods will be deleted and started after that. 

2. It is true that as there is no order, a secondary can eventually become a primary node. However, once the primary node is started again it will recover its primary role as it is specifically configured with a higher priority in the replicaset. I am also seeing issues when recovering a pod so it seems there is something wrong. We will take a look to try to fix it and we will update this issue as soon as we have more information.

3. No. The mongodb does not use any sidecar to run the replica set.

**Comment by dottodot** [comment]
I've recently moved my mongodb on to kubernetes using the helm chart for this and seeing some issues. 

Firstly I has the same issue with `helm upgrade` in that takes down all the pods which isn't ideal if you want to make any changes.

I've also had a couple of instances where the primary pod has restarted but rather than the secondary taking over I get a database unreachable error.

**Comment by tompizmor** [comment]
> Firstly I has the same issue with `helm upgrade` in that takes down all the pods which isn't ideal if you want to make any changes.

Which one do you think is the ideal method? 

> I've also had a couple of instances where the primary pod has restarted but rather than the secondary taking over I get a database unreachable error.

Could you let us know how we can reproduce this issue?
