### ISSUE TITLE
jx install on kubernetes , Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'

### ISSUE THREAD

**Issue by jialzhang** [bitnami/bitnami-docker-mongodb#115]
**Description**

jx install on kubernetes

```
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
```

**Steps to reproduce the issue:**

1. [First Step]

```
### jenkins-x-mongodb-696fdf64fc-bl8zk                  0/1     CrashLoopBackOff   1          26s
### jenkins-x-monocular-api-6b676d869-pr622             0/1     CrashLoopBackOff   5          5m4s
jenkins-x-monocular-prerender-77f6cd8449-fqjwm      1/1     Running            0          28m
jenkins-x-monocular-ui-56bcbc4b7c-m2hk8             1/1     Running            0          28m
jenkins-x-nexus-7794454d6d-ldq2f                    1/1     Running            0          28m
root@master01:~/.jx# kubectl logs jenkins-x-mongodb-696fdf64fc-bl8zk

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
### Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
root@master01:~/.jx# 

root@master01:~/.jx# kubectl logs jenkins-x-monocular-api-6b676d869-pr622
time="2018-10-19T08:30:15Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-10-19T08:30:15Z" level=info msg="Configuration file found!" 
time="2018-10-19T08:30:15Z" level=info msg="Loading CORS from config file" 
time="2018-10-19T08:30:15Z" level=info msg="Loading repositories from config file" 
time="2018-10-19T08:30:15Z" level=info msg="Configuration bootstrap finished" 
time="2018-10-19T08:30:26Z" level=fatal msg="unable to connect to MongoDB" host="jenkins-x-mongodb:27017" 
```

2. [Second Step]

```
Updated the team settings in namespace jx
Cloning the Jenkins X cloud environments repo to /root/.jx/cloud-environments
Enumerating objects: 34, done.
Counting objects: 100% (34/34), done.
Compressing objects: 100% (28/28), done.
Total 1047 (delta 15), reused 17 (delta 6), pack-reused 1013
Generated helm values /root/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /root/.jx/cloud-environments/env-kubernetes
Installing jx into namespace jx
waiting for install to be ready, if this is the first time then it will take a while to download images
### deployment jenkins-x-mongodb failed to become ready in namespace jx
```

3. [and so on...]

**Comment by juan131** [comment]
Hi @jialzhang 

It seems you installed MongoDB as part of the Monocular Helm chart. Could you please share the deployment/statefulset that it installed on your Kubernetes cluster? It seems it doesn't have the proper `securityContext` configured an you're facing issues with permissions.

You can obtain the deployment by running the command below:

```
kubectl get deploy jenkins-x-mongodb -o yaml
```

Or the command below if it installed a statefulset:

```
kubectl get statefulest jenkins-x-mongodb -o yaml
```

**Comment by juan131** [comment]
Hi @jialzhang 

It seems you installed MongoDB as part of the Monocular Helm chart. Could you please share the deployment/statefulset that it installed on your Kubernetes cluster? It seems it doesn't have the proper `securityContext` configured an you're facing issues with permissions.

You can obtain the deployment by running the command below:

```
kubectl get deploy jenkins-x-mongodb -o yaml
```

Or the command below if it installed a statefulset:

```
kubectl get statefulest jenkins-x-mongodb -o yaml
```

**Comment by 2969266** [comment]
I got the same issue, below is the deployment yaml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: ibm-privileged-psp
  creationTimestamp: 2018-10-30T06:55:06Z
  generateName: jenkins-x-mongodb-6bfd5d9c79-
  labels:
    app: mongodb
    chart: mongodb-4.0.4
    pod-template-hash: "2698185735"
    release: jenkins-x
  name: jenkins-x-mongodb-6bfd5d9c79-5zdpg
  namespace: jx
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jenkins-x-mongodb-6bfd5d9c79
    uid: 015a6a2c-dc10-11e8-9d00-da55ec5d5307
  resourceVersion: "12406764"
  selfLink: /api/v1/namespaces/jx/pods/jenkins-x-mongodb-6bfd5d9c79-5zdpg
  uid: bc1148c2-dc10-11e8-9d00-da55ec5d5307
spec:
  containers:
  - env:
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: jenkins-x-mongodb
    - name: MONGODB_USERNAME
    - name: MONGODB_DATABASE
      value: monocular
    - name: MONGODB_EXTRA_FLAGS
    image: docker.io/bitnami/mongodb:3.6.6-debian-9
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: jenkins-x-mongodb
    ports:
    - containerPort: 27017
      name: mongodb
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mongodb
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hqmlr
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: 10.93.191.50
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: jenkins-x-mongodb
  - name: default-token-hqmlr
    secret:
      defaultMode: 420
      secretName: default-token-hqmlr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-30T06:55:06Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-10-30T06:55:06Z
 55         image: docker.io/bitnami/mongodb:3.6.6-debian-9
    message: 'containers with unready status: [jenkins-x-mongodb]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'containers with unready status: [jenkins-x-mongodb]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2018-10-30T06:55:06Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f02ee87e0de80ed6c40d9c613011c2b629eec76c34c8cfa873828c151f320d91
    image: docker.io/bitnami/mongodb:3.6.6-debian-9
    imageID: docker.io/bitnami/mongodb@sha256:110d3d4bfa71c8ebaabc4ee0a8fd19464b68fe239c5c4effcd41c585cc53665a
    lastState:
      terminated:
        containerID: containerd://f02ee87e0de80ed6c40d9c613011c2b629eec76c34c8cfa873828c151f320d91
        exitCode: 1
        finishedAt: 2018-10-30T06:57:05Z
        reason: Error
        startedAt: 2018-10-30T06:57:02Z
    name: jenkins-x-mongodb
    ready: false
    restartCount: 4
    state:
      waiting:
        message: Back-off 1m20s restarting failed container=jenkins-x-mongodb pod=jenkins-x-mongodb-6bfd5d9c79-5zdpg_jx(bc1148c2-dc10-11e8-9d00-da55ec5d5307)
        reason: CrashLoopBackOff
  hostIP: 10.93.191.50
  phase: Running
  podIP: 172.30.33.88
  qosClass: BestEffort
  startTime: 2018-10-30T06:55:06Z
```

**Comment by juan131** [comment]
Hi @2969266 

It seems you share the **pod**'s yaml instead of the deployment one. 

Could you please share the yaml corresponding to the **deployment/statefulset** related to that pod?

**Comment by 2969266** [comment]
It works now, got wrong cloud provider

**Comment by juan131** [comment]
Hi @2969266 

I'm glad you could solve it. I'd keep the issue open in case there are other people with permissions issues.

**Comment by ysfAskri** [comment]
I have the same issue and this my deployment config : 
`{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "jenkins-x-mongodb",
    "namespace": "jx",
    "selfLink": "/apis/extensions/v1beta1/namespaces/jx/deployments/jenkins-x-mongodb",
    "uid": "fc744509-6c27-11e9-89bf-525400261060",
    "resourceVersion": "198163",
    "generation": 1,
    "creationTimestamp": "2019-05-01T15:44:20Z",
    "labels": {
      "app": "mongodb",
      "chart": "mongodb-4.0.4",
      "heritage": "Tiller",
      "release": "jenkins-x"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "mongodb",
        "chart": "mongodb-4.0.4",
        "release": "jenkins-x"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "mongodb",
          "chart": "mongodb-4.0.4",
          "release": "jenkins-x"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "data",
            "persistentVolumeClaim": {
              "claimName": "jenkins-x-mongodb"
            }
          }
        ],
        "containers": [
          {
            "name": "jenkins-x-mongodb",
            "image": "docker.io/bitnami/mongodb:3.6.6-debian-9",
            "ports": [
              {
                "name": "mongodb",
                "containerPort": 27017,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "MONGODB_ROOT_PASSWORD",
                "valueFrom": {
                  "secretKeyRef": {
                    "name": "jenkins-x-mongodb",
                    "key": "mongodb-root-password"
                  }
                }
              },
              {
                "name": "MONGODB_USERNAME"
              },
              {
                "name": "MONGODB_DATABASE",
                "value": "monocular"
              },
              {
                "name": "MONGODB_EXTRA_FLAGS"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "data",
                "mountPath": "/bitnami/mongodb"
              }
            ],
            "livenessProbe": {
              "exec": {
                "command": [
                  "mongo",
                  "--eval",
                  "db.adminCommand('ping')"
                ]
              },
              "initialDelaySeconds": 30,
              "timeoutSeconds": 5,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 6
            },
            "readinessProbe": {
              "exec": {
                "command": [
                  "mongo",
                  "--eval",
                  "db.adminCommand('ping')"
                ]
              },
              "initialDelaySeconds": 5,
              "timeoutSeconds": 5,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 6
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {
          "runAsUser": 1001,
          "fsGroup": 1001
        },
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "unavailableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-05-01T15:44:22Z",
        "lastTransitionTime": "2019-05-01T15:44:22Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      },
      {
        "type": "Progressing",
        "status": "False",
        "lastUpdateTime": "2019-05-01T18:10:22Z",
        "lastTransitionTime": "2019-05-01T18:10:22Z",
        "reason": "ProgressDeadlineExceeded",
        "message": "ReplicaSet \"jenkins-x-mongodb-6bfd5d9c79\" has timed out progressing."
      }
    ]
  }
}`

**Comment by juan131** [comment]
Hi @ysfAskri 

It's so weird... You're using the right securityContext and the permissions should be fine. 

I guess you can try using the parameter `extraInitContainers` to include a initContainer such as the one below:

```
      - name: volume-permissions
        image: "bitnami/minideb"
        imagePullPolicy: "Always"
        command: ["/bin/chown", "-R", "1001:1001", "/bitnami/mongodb"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: "/bitnami/mongodb"
```

**Comment by dantwining** [comment]
I'm having the same issue, I'd like to try the `extraInitContainers` but I'm afraid that I'll need additional instructions on how to set one up. I'm new to both jx and k8s/helm, I'm assuming that this needs to be added to a helm chart somewhere but I don't know where, nor how to apply it once I have. I have tried to attach to the mongodb container in the hope of just running the `chmod` command and verifying the fix, but that doesn't seem to be possible either.

**Comment by juan131** [comment]
Hi @dantwining 

Did you try by editing the MongoDB deployment which is created when installing the chart?

```
$ kubectl edit deploy xxx....
```
