### ISSUE TITLE
Wrong project link in Readme file

### ISSUE THREAD

**Issue by ikandars** [bitnami/bitnami-docker-mongodb#116]
Hi,
In Readme file it wrote:
> Subscribe to project updates by watching the [bitnami/redis GitHub repo](https://github.com/bitnami/bitnami-docker-redis).

I Belief the correct one is:
> Subscribe to project updates by watching the [bitnami/mongodb GitHub repo](https://github.com/bitnami/bitnami-docker-mongodb).

**Comment by juan131** [comment]
Hi @ikandars 

Thanks so much for reporting it!! I just updated it!!
