### ISSUE TITLE
crash or failed authentication on a fresh deploy

### ISSUE THREAD

**Issue by mer2github** [bitnami/bitnami-docker-mongodb#117]
**Description**

I'm deploying the image via Kubernetes (1.9.3) into a Fedora Atomic 27 VM and Docker version 1.13.1. Fairly often I am seeing an assert failure when mongod starts after the creation of the root user. It seems that nami iniitalization is *sometimes* leaving the mongodb db folder in a state that the storage system does not like.

With about the same frequency that i see assert failures, i am also seeing an inability to authenticate as root after nami initialization competes. i created a custom initialization script in the docker-entrypoint-initdb.d directory that invokes: "mongo admin -u root -p $MONGODB_ROOT_PASSWORD". When it fails i can see ACCESS log entries that claim root@admin is an unknown user. 

$ echo $BITNAMI_IMAGE_VERSION 4.0.3-debian-9-r11

**Steps to reproduce the issue:**

1. deploy mongodb via helm with the 4.4.0 chart
2. if successful, helm delete --purge and try it again

**Describe the results you received:**

sometimes i see an assert from the mongodb storage system: "Unable to start up mongod due to missing featureCompatibilityVersion document." See the attached [log_crash.txt](https://github.com/bitnami/bitnami-docker-mongodb/files/2521057/log_crash.txt)

other times i see that authenticating as the root user fails both in custom start up scripts and when attaching to the running container. see attached [log_authn_fail.txt](https://github.com/bitnami/bitnami-docker-mongodb/files/2521064/log_authn_fail.txt)

**Describe the results you expected:**

i expect a successfully initialized mongodb with an ability to log in a root to create other users and databases etc.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue seems to happen regularly when i deploy mongo simultaneously with other deployments--weighing down my underpowered cluster. When trying to isolate the problem by deploying mongo alone, the install seemed to work reliably.

**Version**

- Output of `docker version`:

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-44.git584d391.fc27.x86_64
 Go version:      go1.9.1
 Git commit:      caba767-unsupported
 Built:           Thu Nov 23 21:17:26 2017
 OS/Arch:         linux/amd64
 Experimental:    false
```

- Output of `docker info`:

```
Containers: 23
 Running: 19
 Paused: 0
 Stopped: 4
Images: 18
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 5.47 GB
 Data Space Total: 10.24 GB
 Data Space Available: 4.772 GB
 Metadata Space Used: 2.122 MB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 23.04 MB
 Thin Pool Minimum Free Space: 1.024 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.144 (2017-10-06)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version: caba7670d38dc7cddb0c19bcd97cc27fdd65a789 (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: caba7670d38dc7cddb0c19bcd97cc27fdd65a789-dirty (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.14.18-300.fc27.x86_64
Operating System: Fedora 27 (Atomic Host)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 7.789 GiB
Name: k8s-cluster2-24564qjopcsz-minion-0.novalocal
ID: MCMP:K2NW:VX6C:HJKV:WPPH:IFT2:HTLL:WNUX:TQCK:KLUW:TYP6:USSB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenStack Kubernetes cluster stood up via the OpenStack Magnum tool;
OpenStack release: Queens
K8s version 1.9.3
Helm version 2.11.0

**Comment by mer2github** [comment]
hi @juan131 , 

thanks for checking on this. i did raise this issue with the folks at Mongodb first. https://jira.mongodb.org/browse/SERVER-37758

They immediately closed it claiming there must be an issue with the container. i wound my way through the bitnami initialization flow and found that whatever nami does to create the root user can sometimes leave the data/db directory in a state that mongodb does not like. the start-up that fails is the one in run.sh that will execute the scripts in docker-entrypoint-initdb.d. i.e. the first startup after creating the root user.

as i mentioned in the initial issue report, sometimes it works, sometimes it asserts and sometimes i cannot authenticate as the root user that was just created. 

mongo points to you and you to them.

**Comment by juan131** [comment]
Hi @mer2github 

> the start-up that fails is the one in run.sh that will execute the scripts in docker-entrypoint-initdb.d. i.e. the first startup after creating the root user.

So.. The problem only appears when mounting custom scripts on **/docker-entrypoint-initdb.d/**, am I right? Were you able to reproduce the issue when not including them?

**Comment by mer2github** [comment]
unfortunately, i see the problem regardless of the presence or absence of initdb scripts. i originally saw the issue without anything in docker-entrypoint-initdb.d and in an effort to change things up, i wrote a script that creates our app's user and database. 

i created a new cluster this morning and removed the initdb script from the chart. i'm seeing authentication failures on my deployment attempts. When this happens neither root nor `ars` are known to mongodb even though they appear to be successfully created:

> Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
> 
> nami    INFO  Initializing mongodb
> mongodb INFO  ==> Deploying MongoDB from scratch...
> mongodb INFO  ==> No injected configuration files found. Creating default config files...
> mongodb INFO  ==> Creating root user...
> mongodb INFO  ==> Creating ars user...
> mongodb INFO  ==> Enabling authentication...
> mongodb INFO 
> mongodb INFO  ########################################################################
> mongodb INFO   Installation parameters for mongodb:
> mongodb INFO     Root Password: **********
> mongodb INFO     Username: ars
> mongodb INFO     Password: **********
> mongodb INFO     Database: ars02
> mongodb INFO   (Passwords are not shown for security reasons)
> mongodb INFO  ########################################################################

[ ... deletia ... ]

> 2018-10-30T19:41:21.097+0000 I ACCESS   [conn9] SASL SCRAM-SHA-1 authentication failed for ars on ars02 from client 10.100.64.9:52468 ; UserNotFound: Could not find user ars@ars02
> 
> 2018-10-30T19:41:21.333+0000 I COMMAND  [conn9] command admin.system.users command: saslStart { saslStart: 1, mechanism: "SCRAM-SHA-1", payload: "xxx", $db: "ars02" } numYields:0 ok:0 errMsg:"Authentication failed." errName:AuthenticationFailed errCode:18 reslen:133 locks:{ Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_query 235ms

**Comment by juan131** [comment]
Hi @mer2github 

Are you able to reproduce the issue on other K8s platforms? Are you able to reproduce it on Minikube for instance?

I install the MongoDB chart several times on Minikube and I did not find any issue:

```
$ helm install stable/mongodb --name mongo1
$ kubectl logs -f mongo1-mongodb-5bb5896bbb-dwqr5

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Creating root user...
mongodb INFO  ==> Enabling authentication...
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Root Password: **********
mongodb INFO   (Passwords are not shown for security reasons)
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
INFO  ==> Starting mongodb...
INFO  ==> Starting mongod...
...
$ export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongo1-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)
$ kubectl run --namespace default mongo1-mongodb-client --rm --tty -i --image bitnami/mongodb --command -- mongo admin --host mongo1-mongodb -u root -p $MONGODB_ROOT_PASSWORD
If you don't see a command prompt, try pressing enter.

> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
```

> Then, I repeated the operations 3 times more with mongo2, mongo3, mongo4.

I want to ensure it's not something related with the platform you're using: **OpenStack Kubernetes cluster**

**Comment by mer2github** [comment]
we haven't seen this issue in other cloud environments (AWS, Ali etc.). i'm the lucky one who drew the OpenStack straw. It seems to have to do with timing / slowness of my cluster. i'm running a lot (OpenStack, K8s,  a bunch of apps) on a pair of servers. If i deploy bitnami/mongodb all alone i typically don't see issues. when i deploy things with our gradle deployment process (sets up our app with mongodb at the same time) i often do. 

if i switch to using the docker.io/library/mongo image i can get clean / successful deployments every time (so far). 

Question: what exactly does nami do to create the root user and MONGODB_USER? there's not much visibility into that.

**Comment by juan131** [comment]
Hi @mer2github 

If it's related to timing/slowness that can be related to lack of RAM/CPU during the initialisation of the container, I'm glad to tell you that we're moving our containers from Nami to Bash scripts.

These scripts consume less resources and they're open for everyone who wants to contribute to them. See for instance:

https://github.com/bitnami/bitnami-docker-redis/tree/master/5.0/debian-9/rootfs
https://github.com/bitnami/bitnami-docker-nginx/tree/master/1.14/debian-9/rootfs

The next on the list to be migrated to Bash is this container, MongoDB.

**Comment by mer2github** [comment]
Thanks @juan131 . I will retry deploying once the new image is available.
