### ISSUE TITLE
Replica set config gets stuck

### ISSUE THREAD

**Issue by saqibahmed515** [bitnami/bitnami-docker-mongodb#121]
**Description**
I'm starting an arbiter on one of my SLES machines and it gets stuck at the configuration of replica set:

**Command to start the arbiter**
`docker run -e MONGODB_REPLICA_SET_MODE=arbiter -e MONGODB_PRIMARY_HOST=192.168.1.76 --restart=always --net=host -d bitnami/mongodb:latest`

**Stuck here:**
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set mode


```
I tried to give it some time but it remains there forever. It doesn't even throw any error. I tried connecting 76 (primary) MongoDB from inside the container on this machine and it worked perfectly so there's no connectivity/firewall issue I guess.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.03.1-ee-4
 API version:       1.37
 Go version:        go1.10.2
 Git commit:        0ded23c
 Built:             Thu Oct 25 00:44:38 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.03.1-ee-4
  API version:      1.37 (minimum version 1.12)
  Go version:       go1.10.2
  Git commit:       0ded23c
  Built:            Thu Oct 25 00:47:12 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.03.1-ee-4
Storage Driver: btrfs
 Build Version: Btrfs v4.5.3+20160729
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.73-5-default
Operating System: SUSE Linux Enterprise Server 12 SP3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.679GiB
Name: linux-kqn7
ID: RVYZ:7Q5E:2ZBJ:4WUL:G7UH:JUCX:BXYU:MXDR:EF6M:PPLX:NCRA:GWYG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.security.apparmor=enabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: IPv4 forwarding is disabled
```

## Update November 23, 2018 (Resolved)
After some investigation, I found the function which gets stuck:
`/.nami/components/com.bitnami.mongodb/lib/network.js L#248`
```javascript
...
  function getMachineIp() {
    return this.lookup(os.hostname());
  }
...
```
**The content of my `/etc/hosts` file was wrong**. `hostname` of my machine was different and it is configured differently in `/etc/hosts`. `lookup()` function shouldn't stuck however. There should be some timeout anyway if lookup fails.

I couldn't find this code on this repo by the way. Where is this code located?

**Comment by tompizmor** [comment]
Hi @saqibahmed515,

In order to get additional logs when initializing a container you can set the environment variable `NAMI_LOG_LEVEL=trace8`.

Regarding the `network.js` file, I am afraid that currenty that code is not published in any github repository.
