### ISSUE TITLE
[helm chart] Unable to write key in keyfile 

### ISSUE THREAD

**Issue by cyril-berber** [bitnami/bitnami-docker-mongodb#123]
**Description**
When I set some parameters in the configmap section of the values file of the Helm Chart (here to set the system log output) the container starts with the following error:

    Welcome to the Bitnami mongodb container  

    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb  

    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues  

    nami INFO Initializing mongodb  

    mongodb INFO ==> Deploying MongoDB with persisted data...  

    mongodb INFO ==> Configuration files found...  

    mongodb INFO ==> Writing keyfile for replica set authentication  

    Error executing 'postInstallation': Unable to write key in /opt/bitnami/mongodb/conf/keyfile: Error: EACCES: permission denied, open '/opt/bitnami/mongodb/conf/keyfile'`

**Steps to reproduce the issue:**

Deploy the latest Helm Chart (tested with 4.9.1 and 4.10.1, with Docker Image 4.0.3 and 4.1.4) with systemLog parameter set in the configmap section of the values file:

    configmap:  

      systemLog:  

        destination: file  

        logAppend: true  

        path: /opt/bitnami/mongodb/logs/mongodb.log

**Describe the results you received:**

The container fails to start with the error given above.

**Describe the results you expected:**

The container should start without error and with logs written in the file specified in the configmap instead of the stdout output.

**Additional information you deem important (e.g. issue happens only occasionally):**

Deployment in a Kubernetes cluster, in replicaset mode with values-production file, persistence enabled.

**Version**

- Helm Chart: 4.9.1, 4.10.1
- Docker Image: 4.0.3, 4.1.1

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Deployment on a private cloud (based on OpenStack).

**Comment by bhargavtruecom** [comment]
Hey @tompizmor 

    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
    
    nami    INFO  Initializing mongodb
    mongodb INFO  ==> Deploying MongoDB from scratch...
    mongodb INFO  ==> No injected configuration files found. Creating default config files...
    mongodb INFO  ==> Writing keyfile for replica set authentication
    mongodb INFO  ==> Configuring MongoDB replica set
    mongodb INFO  ==> Enabling MongoDB replica set name
    mongodb INFO  ==> Configuring MongoDB secondary node
    mongodb INFO  Trying to connect to MongoDB server
    mongodb INFO  Found MongoDB server listening at mongodb-primary:27017
    mongodb INFO  Cannot connect to MongoDB server. Retrying in 5 seconds...:
    2019-02-12T08:23:33.516+0000 E QUERY    [js] Error: not master and slaveOk=false :
    _getErrorWithCode@src/mongo/shell/utils.js:25:13
    DB.prototype.getUsers@src/mongo/shell/db.js:1763:1
    @(shell eval):1:1
    
    
    
    mongodb INFO  MongoDB server listening and working at mongodb-primary:27017

    Welcome to the Bitnami mongodb container
    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
    
    nami    INFO  Initializing mongodb
    mongodb INFO  ==> Deploying MongoDB from scratch...
    mongodb INFO  ==> Configuration files found...
    mongodb INFO  ==> Writing keyfile for replica set authentication
    Error executing 'postInstallation': Unable to write key in /opt/bitnami/mongodb/conf/keyfile: Error:         
    EACCES: permission denied, open '/opt/bitnami/mongodb/conf/keyfile'
    
    Welcome to the Bitnami mongodb container
    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
    
    nami    INFO  Initializing mongodb
    mongodb INFO  ==> Deploying MongoDB from scratch...
    mongodb INFO  ==> Configuration files found...
    
    Welcome to the Bitnami mongodb container
    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
    
    nami    INFO  Initializing mongodb
    mongodb INFO  ==> Deploying MongoDB from scratch...
    mongodb INFO  ==> Configuration files found...
    mongodb INFO  ==> Writing keyfile for replica set authentication
    Error executing 'postInstallation': Unable to write key in /opt/bitnami/mongodb/conf/keyfile: Error:     EACCES: permission denied, open '/opt/bitnami/mongodb/conf/keyfile'



**How to reproduce**


    version: '2'
    
    services:
      mongodb-primary:
        image: 'bitnami/mongodb:latest'
        environment:
          - MONGODB_REPLICA_SET_MODE=primary
          - MONGODB_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
        ports:
          - "27017:27017"
        volumes:
          - 'mongodb_master_data:/bitnami'
    
      mongodb-secondary:
        image: 'bitnami/mongodb:latest'
        depends_on:
          - mongodb-primary
        ports:
          - "27018:27017"
        environment:
          - MONGODB_REPLICA_SET_MODE=secondary
          - MONGODB_PRIMARY_HOST=mongodb-primary
          - MONGODB_PRIMARY_PORT_NUMBER=27017
          - MONGODB_PRIMARY_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
        
      mongodb-arbiter:
        image: 'bitnami/mongodb:latest'
        depends_on:
          - mongodb-primary
        ports:
          - "27019:27017"
        environment:
          - MONGODB_REPLICA_SET_MODE=arbiter
          - MONGODB_PRIMARY_HOST=mongodb-primary
          - MONGODB_PRIMARY_PORT_NUMBER=27017
          - MONGODB_PRIMARY_ROOT_PASSWORD=password123
          - MONGODB_REPLICA_SET_KEY=replicasetkey123
    
    volumes:
      mongodb_master_data:
        driver: local

**Comment by tompizmor** [comment]
@bhargavtruecom I am not able to reproduce the issue with your provided docker-compose file. Is there anything else we need to know in order to reproduce it on our side?

**Comment by simplypost** [comment]
@cyril-berber : Have you resolved the issue ?
I got exactly the same error when deploying on aws using helm chart.

**Comment by tompizmor** [comment]
@simplypost Were you providing your own configuration and enabling the replica set configuration?
