### ISSUE TITLE
[helm charts] cannot launch mongodb after i uncomment the configMap part.It seems that the process dosen't write the keyfile.

### ISSUE THREAD

**Issue by SgtDaJim** [bitnami/bitnami-docker-mongodb#124]
**Description**

I am planning to use my own config by modifying the configMap in values.yaml in helm charts. Here is my configMap:
```
configmap:
  # Where and how to store data.
  storage:
    dbPath: /opt/bitnami/mongodb/data/db
    journal:
      enabled: true
    #engine:
    #wiredTiger:
  # where to write logging data.
  systemLog:
    destination: file
    logAppend: true
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 5
  # network interfaces
  net:
    port: 27017
    bindIp: 0.0.0.0
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
  # replica set options
  replication:
    replSetName: rs0
  # process management options
  processManagement:
     fork: false
     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
  # set parameter options
  setParameter:
     enableLocalhostAuthBypass: true
  # security options
  security:
    authorization: enabled
    keyFile: /opt/bitnami/mongodb/conf/keyfile
```
then i install the charts, and cannot make it run normally.
i am running it in replicaSet mode.
here is the log from primary db in kubernetes web ui
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 nami    INFO  Initializing mongodb
mongodb INFO  ==&gt; Deploying MongoDB from scratch...
mongodb INFO  ==&gt; Configuration files found...
```
then it hanged. so i get into the container and read the log of mongodb:
```
I have no name!@***:/$ cat /opt/bitnami/mongodb/logs/mongodb.log
2018-12-21T02:35:11.448+0000 D NETWORK  [main] fd limit hard:1048576 soft:1048576 max conn: 838860
2018-12-21T02:35:11.449+0000 I ACCESS   [main] Error reading file /opt/bitnami/mongodb/conf/keyfile: No such file or directory
```
so obviously the keyfile didn't be generated.

**Steps to reproduce the issue:**

1. [First Step]
modify the configMap in values.yaml
2. [Second Step]
install the service
3. [and so on...]

**Describe the results you received:**

keyfile doesn't be generated.

**Describe the results you expected:**
mongodb run normally in replica set mode.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
helm charts version 5.0.0
helm client and server version 2.10.0

**Comment by andresbono** [comment]
Hi @SgtDaJim, it seems you need to create the key file first.

Please check this section of the official MongoDB documentation: 
https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/#create-a-keyfile

**Comment by SgtDaJim** [comment]
> Hi @SgtDaJim, it seems you need to create the key file first.
> 
> Please check this section of the official MongoDB documentation:
> https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/#create-a-keyfile

Thank you @andresbono , but i've tried to initial the key file use kubernetes initContainer, but it didn't work. do you have any good idea on it ?

**Comment by tompizmor** [comment]
@SgtDaJim Currentl is not possible to provide a custom configmap with replication enabled due to some limitation in the mongodb docker image. We will investigate this issue to see how we can solve it.

In the meantime, could you let us know what have you changed  in the original configuration file? Maybe there is other way to configure it via env variabke for example.

**Comment by SgtDaJim** [comment]
> @SgtDaJim Currentl is not possible to provide a custom configmap with replication enabled due to some limitation in the mongodb docker image. We will investigate this issue to see how we can solve it.
> 
> In the meantime, could you let us know what have you changed in the original configuration file? Maybe there is other way to configure it via env variabke for example.

@tompizmor OK. I just changed the systemLog.verbosity to 5, the others i just keep them original.

**Comment by tompizmor** [comment]
I see...I am afraid that there is not an environment variable to configure the system log verbosity.

**Comment by SgtDaJim** [comment]
@tompizmor OK then.. So do you guys have any ideas of how to initial the keyfile? Or give me an example of initContainers? I am wondering whether i made mistakes on writing the config but i didn't realize..

**Comment by tompizmor** [comment]
> I am wondering whether i made mistakes on writing the config but i didn't realize.. 

No. Your config file looks good. The problem is in the initialization logic of the MongoDB container. 

> Or give me an example of initContainers?

Instead of initContainer, I tried using a [postStart hook](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/). However, despite the fact that the keyfile was created, there were other issues initializating MongoDB.

If you are only interested on increasing the log level it would be easy for us to enable a environment variable so you don't have to provide the full configuration file. What do you think? We will also continue investigating the issue to see how we can improve it.

**Comment by tompizmor** [comment]
@SgtDaJim I just wanted to let you know that we have already added the environment variable to configure the systemLog verbosity level. Please check [this section](https://github.com/bitnami/bitnami-docker-mongodb#increase-system-log-verbosity-level) in the readme for more info.

The stable/mongodb chart has also been updated. The [PR](https://github.com/helm/charts/pull/10501) is already merged but it may take some time before the chart gets packaged and published to the charts repo. 
Please make sure you install the chart version 5.1.0

**Comment by myauie** [comment]
I have been having the same issue, but would like to achieve the opposite - we've been trying to use a custom configmap in the chart to enable systemLog.quiet, but have been met with the same results.

**Comment by tompizmor** [comment]
@myauie I will work on adding a `MONGODB_DISABLE_SYSTEM_LOG` env var to the container at the moment. I will let you know once the new images and chart are released.

**Comment by tompizmor** [comment]
Hi @myauie! The MongoDB docker image now supports the `MONGODB_DISABLE_SYSTEM_LOG` env var. Please check the [readme](https://github.com/bitnami/bitnami-docker-mongodb#configuring-system-log-verbosity-level).

I have also sent a PR to update the stable/mongodb chart (https://github.com/helm/charts/pull/10721)

**Comment by myauie** [comment]
Hi @tompizmor, thanks for the PR. I've been doing some testing and it still looks like we're getting the usual MongoDB log spam with MONGODB_DISABLE_SYSTEM_LOG set to yes

The pod manifest as deployed by Helm:

```apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: mongo-logger-55498764d9-
  labels:
    app: mongodb
    chart: mongodb-5.3.1
    pod-template-hash: "1105432085"
    release: dataswitch-mongodb
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mongo-logger-55498764d9
    uid: d71afdd1-2e04-11e9-9b94-005056b3b2ae
  selfLink: /api/v1/namespaces/dataswitch-test/pods/mongo-logger-55498764d9-glphk
spec:
  containers:
  - env:
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: mongo-logger
    - name: MONGODB_USERNAME
      value: xxxx
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-password
          name: mongo-logger
    - name: MONGODB_SYSTEM_LOG_VERBOSITY
      value: "0"
    - name: MONGODB_DISABLE_SYSTEM_LOG
      value: "yes"
    - name: MONGODB_DATABASE
      value: admin
    - name: MONGODB_ENABLE_IPV6
      value: "yes"
    image: docker.io/bitnami/mongodb:4.0.5
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: mongo-logger
    ports:
    - containerPort: 27017
      name: mongodb
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mongodb
      name: data
    - mountPath: /docker-entrypoint-initdb.d
      name: custom-init-scripts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-drh64
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: worker6
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: mongo-logger-init-scripts
    name: custom-init-scripts
  - name: data
    persistentVolumeClaim:
      claimName: mongo-logger
  - name: default-token-drh64
    secret:
      defaultMode: 420
      secretName: default-token-drh64```

**Comment by tompizmor** [comment]
Hi! I just checked the chart and I see that MongoDB is updating the configuration depending on the `MONGODB_DISABLE_SYSTEM_LOG` value.

If MONGODB_DISABLE_SYSTEM_LOG=false, 

```
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path:
  verbosity: 0
```

if MONGODB_DISABLE_SYSTEM_LOG=true,

```
# where to write logging data.
systemLog:
  destination: file
  quiet: true
  logAppend: true
  logRotate: reopen
  path:
  verbosity: 0
```

I see the next kind of log messages in both deployments but they are because of the liveness and readiness probes.

```
2019-02-21T14:26:00.362+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:33476 #220 (1 connection now open)
2019-02-21T14:26:00.363+0000 I NETWORK  [conn220] received client metadata from 127.0.0.1:33476 conn220: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.0.6" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 9 (stretch)"", architecture: "x86_64", version: "Kernel 4.14.65+" } }
2019-02-21T14:26:00.367+0000 I NETWORK  [conn220] end connection 127.0.0.1:33476 (0 connections now open)
```

Are you seeing any other messages?

**Comment by myauie** [comment]
No, we're not seeing other messages. After a bit of trial and error, I think what we're actually after is the ability to define `systemLog.path`.

**Comment by tompizmor** [comment]
Which value would you want to set? I would like to test how it behaves...
