### ISSUE TITLE
how to built the cluster from different host?

### ISSUE THREAD

**Issue by WhoamiV** [bitnami/bitnami-docker-mongodb#127]
I need to put the secondary to the other host,so I changed the configration below
```
docker run --name mongodb-secondary \
-e MONGODB_REPLICA_SET_MODE=secondary \
-e MONGODB_PRIMARY_HOST=192.168.1.6 \
-e MONGODB_PRIMARY_ROOT_PASSWORD=mongo \
-e MONGODB_PRIMARY_PORT_NUMBER=27017 \
-e MONGODB_REPLICA_SET_KEY=replicasetkey123 \
-p 27017:27017 \
bitnami/mongodb:4.0.3
```
192.168.1.6  is the host of primary,but when I run the secondary, i seems wrong by telling me that ```[LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured```

**Comment by WhoamiV** [comment]
Or should I use kubernetes?

**Comment by juan131** [comment]
Hi @WhoamiV 

Did you configure replication in the primary node? See https://github.com/bitnami/bitnami-docker-mongodb#step-1-create-the-replication-primary

> Or should I use kubernetes?

We always recommend K8s as the platform to deploy these containers. You can use [Helm](https://docs.helm.sh/) and the stable MongoDB chart which uses this images to deploy MongoDB on K8s:

https://github.com/helm/charts/tree/master/stable/mongodb

You just need to enable the replicaSet parameter when deploying it,

```
$ helm install --name mongodb stable/mongodb --set replicaSet.enabled=true
```

**Comment by juan131** [comment]
Hi @WhoamiV 

Is the Primary node reachable from the Secondary node?

It seems you're using a private IP: `192.168.1.6`. Therefore, when using different hosts, the nodes can't reach each other. Do you have anything connecting both hosts under the same private network?

**Comment by WhoamiV** [comment]
Yes, the secondary node can reach Primary node by the host's IP and exposed port,but the Primary node can not reach the secondary node,that might be the reason.....sad....

**Comment by juan131** [comment]
Yes, I also think it's a networking issue.
