### ISSUE TITLE
Configuration error systemLog.quiet

### ISSUE THREAD

**Issue by nerumo** [bitnami/bitnami-docker-mongodb#128]
I'm using the helm chart 4.9.1 with the image tag 4.0.3. Today my mongodb container got restarted, pulled the latest image (4.0.3) and since then I have a startup error.

```
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB with persisted data...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Enabling authentication...
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
?[0m?[38;5;2mINFO ?[0m ==> Starting mongodb...
?[0m?[38;5;2mINFO ?[0m ==> Starting mongod...
Expected boolean switch but found string:  for option: systemLog.quiet
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

I removed the volume and tried with a plain startup, with the same results. In the chart I set the configmap option and set `systemLog.quiet` to `true` and after that it worked again.

**Comment by gbandet** [comment]
I have faced the same issue and investigated on it.

The image uses the "com.bitnami.mongodb" nami package to set up the MongoDB.
The config file is generated from a template (`/.nami/components/com.bitnami.mongodb/templates/mongodb.conf.tpl`) where the systemLog.quiet is set with `quiet: {{disableSystemLog}}`.

The `disableSystemLog` variable is set in the `/.nami/components/com.bitnami.mongodb/main.js` script with two cases:

* initial set up (no db files)
```
      $hb.renderToFile(
        'mongodb.conf.tpl',
        $app.confFile,
        {
          enableIPv6: $app.enableIPv6 === 'yes' ? true : false,
          disableSystemLog: $app.disableSystemLog === 'yes' ? true : false,
        }
      );
```
* Existing db
```
      $hb.renderToFile(
        'mongodb.conf.tpl',
        $app.confFile,
        {enableIPv6: $app.enableIPv6 === 'yes' ? true : false}
      );
```

In the 2nd case, the `disableSystemLog` variable is not set at all and then rendered as an empty string in the MongoDB config file, which make mongod to fail when started.

**Comment by javsalgar** [comment]
Hi,

Thanks a lot for reporting the issue. We will release a new revision of the container that fixes the issue. I will post here when it is out.

**Comment by rporres** [comment]
Any news on this, @javsalgar? Thanks!

**Comment by javsalgar** [comment]
Hi,

Sorry for not reaching out. Just a note to let you know that we the new mongodb containers already have the issue fixed. Please let us know if you find any issue.

**Comment by carrodher** [comment]
Feel free to reopen it if you find the mentioned issues
