### ISSUE TITLE
License is no longer opensource

### ISSUE THREAD

**Issue by pierreozoux** [bitnami/bitnami-docker-mongodb#129]
As you may have read on the news, MongoDB SSPL license is not considered open source and will not be shipped by debian nor RedHat any more.

What is bitnami plan on this? Do you plan to remove this image? Or do you plan to keep this in your catalog? What is your strategy to communicate to your users about this change?

As a free software advocate, I think it is our duty to manage expectation of users of proprietary software.

This issue is linked with
https://github.com/docker-library/mongo/issues/324
https://github.com/helm/charts/issues/10785

**Comment by beltran-rubo** [comment]
Hi, as this has been discussed in some of the other linked issues. Similar to Docker, our templates and Dockerfiles themselves are Apache 2.0-licensed. We will update the documentation to reflect the fact that MongoDB license changed but it is up to end users if they want to continue to use it or not. In any case, it is the responsibility of the end user to review and comply with software licenses. There are plenty of people that are OK with the license changes of MongoDB (regardless of how you or I feel about it) and we want to continue to offer a valuable service to them.

**Comment by pierreozoux** [comment]
I understand, can you be kind and share me how you warn the user? I'm curious and then I could copy the logic elsewhere!

Thanks!

**Comment by beltran-rubo** [comment]
We will not implement any logic into the container, we will just add a note in the README.

**Comment by pierreozoux** [comment]
You could add the need for an environment variable to be set? Then it is a conscious decision that the user is doing.

**Comment by prydonius** [comment]
I added a comment in https://github.com/helm/charts/issues/10785#issuecomment-458328206, r.e. the chart. I'm not sure it makes sense to set an environment variable, but open to discuss it. In the meantime, an update to the README would be a good idea.

**Comment by beltran-rubo** [comment]
We added a note in the README file into the main description of the Container and into the Notable changes.
