### ISSUE TITLE
Provide image for 4.0.5

### ISSUE THREAD

**Issue by sottolski** [bitnami/bitnami-docker-mongodb#130]
not at least out of curiosity, the latest bitnami/mongodb image seems to be 4.0.3.

"Bitnami closely tracks upstream source changes and promptly publishes new versions of this image using our automated systems."

Since then, mongodb released 4.0.4 Nov 8, and 4.0.5 Dec 20.

https://docs.mongodb.com/manual/release-notes/4.0/

May there are specific problems with those versions for bitnami not to build images for them?

Thanks

Sascha

**Comment by beltran-rubo** [comment]
Hi Sascha,

This version has been blocked because the license change of MongoDB. We are working on adding notes to make sure Bitnami users understand the implications of this license change and we will release new container versions this week.

**Comment by sottolski** [comment]
I see, thanks for the insight Beltran

**Comment by tompizmor** [comment]
I am closing this issue! Please create a new one if you have any other question.
