### ISSUE TITLE
Can I log using file instead of std output

### ISSUE THREAD

**Issue by zffocussss** [bitnami/bitnami-docker-mongodb#131]
Hi I want to log useing a file.but it is default sends the container logs to the stdout.

**Comment by andresbono** [comment]
Hi @zffocussss, you can do it by commenting out this line in the `run.sh` file:

https://github.com/bitnami/bitnami-docker-mongodb/blob/5073ed52c0b6ef819fcff9a2d8f43ceae86c6e2b/4.0/debian-9/rootfs/run.sh#L24-L25

After doing so, you can build the customized Docker image and the logs will be added to the `/opt/bitnami/mongodb/logs/mongodb.log` file in the container.

Hope it helps!

**Comment by zffocussss** [comment]
hi Bono
        thanks.

**Comment by andresbono** [comment]
Hi @zffocussss, did it work?

Let us know if it didn't!

**Comment by zffocussss** [comment]
> Hi @zffocussss, did it work?
> 
> Let us know if it didn't!

I have not tried it.I will give you feedback after I try.
