### ISSUE TITLE
Is there a bitnami image with support for MongoDB sharded cluster?

### ISSUE THREAD

**Issue by arunjp** [bitnami/bitnami-docker-mongodb#133]
**Description**
We wanted to create MongoDB sharded cluster for Kubernetes for Azure cloud platform. Wanted to know if there's a bitnami image that supports MongoDB sharded cluster.

**Comment by marcosbc** [comment]
Hi @arunjp, currently we do not support MongoDB sharding in our containers.

It is possible to [mount a custom configuration file](https://github.com/bitnami/bitnami-docker-mongodb#configuration-file), so it is likely that advanced users might be able to get it working by following these steps: https://docs.mongodb.com/manual/tutorial/deploy-shard-cluster/#start-each-member-of-the-config-server-replica-set

We're curious though, as this is the first request we've seen on this topic: What's your use case? Won't a normal MongoDB setup work for you?

**Comment by arunjp** [comment]
Hi,
Thanks for your response. Will read through the document and try it out. Thanks for the reference.

We consume data coming in from external partners. There are multiple partners and we receive few GBs of data per day for each partner. We use MongoDB as our datastore. We are planning to add more partners in our foreseeable future and it'll keep increasing linearly over the time. Currently, we have MongoDB replica set that manages the data. However, with the increasing load, we came into consensus that scaling MongoDB datastore horizontally (using Sharded cluster) would be the right approach. Hence the requirement.

Please do let me know if you need further details.

Thanks
Arun

**Comment by victisomega** [comment]
I too have found a need to utilize a sharded cluster inside of docker so I thought I'd throw my two cents in. Our situation is similar to what was posted above. I'm going to try my hand at getting it working by hand using this docker image.

**Comment by marcosbc** [comment]
Thanks for sharing your cases! I have created an internal task for adding official support for it, but unfortunately we cannot provide an ETA for when we will start working on this.

Of course, if you get it working on your side before, it would be great if you could share it with us!

**Comment by arunjp** [comment]
Hi @marcosbc,
Thanks for looking into it. Would try our best to have something in place and would certainly share the information if we get it working before you guys.

Thanks again

**Comment by marcosbc** [comment]
Thanks @arunjp! If you find a blocker for implementing this due to a missing image feature, let us know and we'll look into it.

**Comment by arunjp** [comment]
Sure @marcosbc, will let you know. But just curious, do you have this as your priority? The reason is, the focus from our end might be shifted to something else and we might not get into this in the short term.

**Comment by marcosbc** [comment]
Hi @arunjp, that's fine. Unfortunately it's not a priority for us right now, so it may take some time if we start looking into it (probably a few months).

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
