### ISSUE TITLE
Support hidden mode for replicaset

### ISSUE THREAD

**Issue by simplypost** [bitnami/bitnami-docker-mongodb#145]
**Description**
Hi guys,

I would like to create a mongodb's replicaset which include 1 primary, 1 secondary, 1 hidden member (for backup db to s3)
Unfortunately, I unable find out where is in docker's source which allow to custom these configurations.

Any advises ?

**Comment by andresbono** [comment]
Hi @simplypost, thanks for opening the issue. We have not included `hidden` as a replica-set role yet but it seems like an interesting feature to add to our container :+1:.

We are right now in the process of publishing the configuration logic in this repository in the same way we have for other containers like [bitnami/bitnami-docker-mysql - 8.0/debian-9/rootfs](https://github.com/bitnami/bitnami-docker-mysql/tree/master/8.0/debian-9/rootfs).

Once the logic is on this repository, we can work together on including it to fit your use case.

**Comment by simplypost** [comment]
Hi @andresbono 

Thanks for your answer, I just spent few hours to customize the mongodb lib from the bitnami-pkg and enable to make it work for our case. However, It is a good news when your guy planning to public the configuration logic.

**Comment by andresbono** [comment]
Great to hear @simplypost!

We will update this issue when we have more news.

**Comment by marcosbc** [comment]
Hi, just wanted to let you know that we released the MongoDB container with the new logic early this week. Now you can find the logic in the script repo.

Also, if you find any way the logic can be improved, feel free to send a PR.

**Comment by simplypost** [comment]
@marcosbc : Great ! Thank for your information.

**Comment by GL-KenDLG** [comment]
Question,

I know you mentioned this was released last week, however, I am not able to find the logic to use it anywhere. What do you mean by "Now you can find the logic in the script repo"? I imagine I am looking in the wrong place. Or how can I configure a secondary node to be hidden (and delayed if it happens to be supported).

Thank you in advance for any guidance you can provide.

**Comment by carrodher** [comment]
You can find the logic in the [_rootfs_](https://github.com/bitnami/bitnami-docker-mongodb/tree/master/4.0/debian-9/rootfs) folder. The previous link redirects to the `4.0` version and debian 9 as the platform, but you can find the equivalent to other versions/platforms in the respective directories.

**Comment by GL-KenDLG** [comment]
Thanks! Apparently I just needed to remove and redownload the container for everything to show up.

**Comment by andresbono** [comment]
Closing the issue now.
