### ISSUE TITLE
Unable to install commands like crontab scp.

### ISSUE THREAD

**Issue by babalsurer** [bitnami/bitnami-docker-mongodb#147]
Hello,
       When I try to install command in the container there are no permissions I need to install crontab and Scp how I can install it.?

**Comment by rafariossaa** [comment]
Hi @babalsurer ,
  You can add the packages you need to the **RUN install_packages** line in the Dockerfile and build your own image, or you can exec as root into the running container and do **apt update**; **apt install** .

  The method chosen would depend on if you need a more permanent solution or not.

Best regards,
Rafael Rios Saavedra
