### ISSUE TITLE
Container is unreachable and eventually errors out

### ISSUE THREAD

**Issue by rochdev** [bitnami/bitnami-docker-mongodb#148]
**Description**

Container is unreachable on the default port and eventually fails with a `Error executing 'postInstallation': Unable to stop com.bitnami.mongodb` error.

**Steps to reproduce the issue:**

Run this job in CircleCI: https://github.com/DataDog/dd-trace-js/blob/eb48759a82ceb5a1cf766885cb9dacc0d78b026b/.circleci/config.yml#L278-L286

**Describe the results you received:**

`Error executing 'postInstallation': Unable to stop com.bitnami.mongodb` error

**Describe the results you expected:**

The container should be reachable and shutdown gracefully.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue started about 2 months ago with no change in the image. It looks like there may be a new incompatibility between CircleCI and this image. However, all our other images work properly in CircleCI.

**Version**

- Output of `docker version`:

```
N/A
```

- Output of `docker info`:

```
N/A
```

- Output of `docker-compose version` (if applicable):

```
N/A
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

https://circleci.com/workflow-run/6b2901cd-1da6-457c-88b5-394580dbfa29

**Comment by andresbono** [comment]
Hi @rochdev,

Did you try with more recent versions of the container? Can you add the following environment variable to the container to get more information?

```
NAMI_LOG_LEVEL=trace
```

**Comment by rochdev** [comment]
See https://circleci.com/gh/DataDog/dd-trace-js/37035 for output with trace logs.

`Container bitnami/mongodb:4` contains the output of the container.
`Unit tests` contains the output from the app trying to connect and failing. This only happens when using a Replica Set.

We were previously using `bitnami/mongodb:3.6` with the same issue.

**Comment by rochdev** [comment]
One common thing we've noticed is that the container usually fails after ~45 seconds consistently. This is the case for all our tracer builds (Node, Python, Go, Ruby, etc).

**Comment by lokst** [comment]
Hi,

Here's a more simplified reproduction of the error, with the NAMI_LOG_LEVEL environment variable set to trace8 for debugging: https://circleci.com/gh/lokst/bitnami-mongodb-error-repro/2

If you expand the "Container bitnami/mongodb:4" section and look at the output, the following lines keep repeating until the container errors out.

```
mongodb TRACE [normalize] File normalization: /opt/bitnami/mongodb/tmp/mongodb.pid -> /opt/bitnami/mongodb/tmp/mongodb.pid
mongodb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mongodb/tmp
```

```
Error executing 'postInstallation': Unable to stop com.bitnami.mongodb
nami    TRACE Error: Error executing 'postInstallation': Unable to stop com.bitnami.mongodb
    at Service._stopUsingPidFile (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:184:15)
    at Service._stop (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:390:12)
    at Service._restart (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:416:12)
    at Service.restart (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:431:21)
    at Object.$app.helpers.configureReplicaSet (/.nami/components/com.bitnami.mongodb/helpers.js:94:8)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.mongodb/main.js:59:20)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)

Exited with code 1
```

**Comment by marcosbc** [comment]
Hi all, early this week we made a major change to the internal logic of the container. Now it uses Bash logic, which is public in this repo. The container should work the same, but it is possible this issue was fixed with the changes.

Could you try updating to the latest revision (e.g. `4.1.13-debian-9-r24` for 4.1) and see if it fixes your issue?

**Comment by rochdev** [comment]
I am now getting an error about authentication. According to the documentation authentication is optional, and we were not using any before.

```yaml
version: '2'
services:
  mongo:
    image: bitnami/mongodb:4.1.13
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
    ports:
      - "127.0.0.1:27017:27017"
```

```
ERROR ==> MONGODB_ROOT_PASSWORD have to be set on a 'primary' node!
```

It's unclear if the problem is solved since now the connection seems to hangs even locally.

**Comment by marcosbc** [comment]
If you remove `MONGODB_REPLICA_SET_MODE=primary` it should be fine. Why are you configuring a single-node replicaset?

**Comment by rochdev** [comment]
@marcosbc Built-in support for replica sets is the only reason I am using this image over the official CircleCI Mongo image. I need a replica set so I can test support for the different Mongo topologies in CI.

**Comment by marcosbc** [comment]
That's fine. It's a weird configuration, but makes sense in a CI environment. I've created an internal task for fixing this issue and we'll keep you updated with any progress.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
