### ISSUE TITLE
bitnami/mongodb:latest restart loop when running from docker-compose detached (-d flag)

### ISSUE THREAD

**Issue by affirmed-gl** [bitnami/bitnami-docker-mongodb#154]
I am a little new to docker / docker-compose and I have inherited an environment using the bitnami/mongodb container and I have a question about its behavior (spoiler going through getting all this info I figured out the issue but there is still a question at the end).
 
When I run the container detached:
 
```$docker-compose -f docker-compose.yml up -d```
 
The container starts and runs for about a minute and then enters a never ending loop of restarting just about every minute.  When I look at the docker logs command for this container this is what I see.

```Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB with persisted data...
INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
INFO  ==> 
INFO  ==> ########################################################################
INFO  ==>  Installation parameters for MongoDB:
INFO  ==>    Persisted data and properties have been restored.
INFO  ==>    Any input specified will not take effect.
INFO  ==> (Passwords are not shown for security reasons)
INFO  ==> ########################################################################
INFO  ==> 
INFO  ==> Stopping MongoDB...

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MongoDB setup **
INFO  ==> Validating settings in MONGODB_* env vars...
INFO  ==> Initializing MongoDB...
INFO  ==> Deploying MongoDB with persisted data...
INFO  ==> Custom configuration /opt/bitnami/mongodb/conf/mongodb.conf detected!
INFO  ==> 
INFO  ==> ########################################################################
INFO  ==>  Installation parameters for MongoDB:
INFO  ==>    Persisted data and properties have been restored.
INFO  ==>    Any input specified will not take effect.
INFO  ==> (Passwords are not shown for security reasons)
INFO  ==> ########################################################################
INFO  ==> 
INFO  ==> Stopping MongoDB...
```

if I ```docker exec -it <containername> bash```  I can poke around the file system but do not see any logs that would help me diagnose the issue.

 If I run the container and keep the console open: 
 
```$docker-compose -f docker-compose.yml up```
 
The container runs as expected for as long as the console is kept open.  In the case when I call docker-compose in detached (-d) mode then shut all the containers down

```docker stop $(docker ps -a -q)```

and then I try to run it in console mode the container fails to start with the above log entry, but does not try to restart.  I have to delete the container and images and then restart with 

```docker-compose -f docker-compose.yml up```
 
On both Ubuntu and CentOS the docker-compose is run by my user who is in the docker group. 

This is the service in the docker compose file
 
```mongodb:
    restart: always
    image: 'bitnami/mongodb:latest'
    user: root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/bitnami/mongodb
    networks:
      - db_network
 ```

I have Windows 10 prof version 1903 OS, on which I run an Ubuntu 18.04 LTS and a CentOS 7 virtualbox virtual machines and the issue occurs on both systems identically.

VirtualBox Graphical User Interface (do not know if this is also the virtual box engine version?)
Version 5.2.30 r130521 (Qt5.6.2)

centos-release-7-6.1810.2.el7.centos.x86_64
Docker version 18.09.7, build 2d0083d
docker-compose version 1.24.0, build 0aa59064

18.04.1-Ubuntu SMP
Docker version 18.09.6, build 481bc77
docker-compose version 1.17.1, build unknown

And finally I believe I figured out the problem but do not know how to cure it permanently.

On the underlying VM file system there is a file /mongodb/data/db/mongod.lock in the volume. If I manually delete this file then the container runs fine in detached mode.  So deleting and rebuilding the container must overwrite this entire directory.  This is why I found I had to delete and rebuild the container to get it to run in console mode, which makes sense as I always run in console mode first to see the stream of log output for verification, and then would shut down and start in detached mode.

So the question becomes will I always have to either rebuild the container before running docker-compose or is there a way to make the mongod.lock file clean itself up on shutdown?

Thanks for taking the time to read this!
Greg

**Comment by GL-KenDLG** [comment]
Not sure if it is related but my deployment recently stopped working in much the same way as yours once I pulled in the recent change. In addition to the above, I see:

==
2019-06-29T03:18:52.531+0000 F  CONTROL  [main] Failed global initialization: FileNotOpen: Failed to open "/opt/bitnami/mongodb/logs/mongodb.log"
==

The file does exists as a symlink (which I think it always has been):
==
root@219977c6b7e5:/# ls -lash  /opt/bitnami/mongodb/logs/mongodb.log
0 lrwxrwxrwx 1 root root 11 Jun 28 14:55 /opt/bitnami/mongodb/logs/mongodb.log -> /dev/stdout
==

If not related, feel free to disregard this comment.

**Comment by andresbono** [comment]
Hi @affirmed-gl, @GL-KenDLG, we have faced a recent issue with the MongoDB image, but it should be solved now, see #152. Could you please try the latest image and let us know if it works?

**Comment by affirmed-gl** [comment]
I just removed all my containers and images and re-ran my docker-compose command detached and in console mode and restarts always seem to work now so I think the issue is resolved.  Thanks for the help!
Greg

**Comment by andresbono** [comment]
Great to hear, @affirmed-gl!! :tada:

**Comment by andresbono** [comment]
@GL-KenDLG, we just closed the issue, but let us know if you still face any problems and we will try to help you.
