### ISSUE TITLE
Custom user initialization scripts not being run on startup

### ISSUE THREAD

**Issue by cliffcotino** [bitnami/bitnami-docker-mongodb#162]
**Description**

It seems that during the migration to the `bash`-based container setup scripts, the functionality for executing custom scripts from `/docker-entrypoint-initdb.d` has been left out.
Example commit where this seems to have been introduced (see: `4.0/ol-7/rootfs/run.sh`): 78a0d851c16f2aa4a764b62b6e61b2cf1c6e1ac7

**Steps to reproduce the issue:**

1. Create a script
```
// give the primary time to realize that it's in charge
sleep(5000);
db = db.createCollection('foo');
db.foo.insert({'_id': 0});
```

2. Start the container with the example script mounted in `/docker-entrypoint-initdb.d/create.js`
3. Verify that there is a `foo` collection using `echo "db.getCollectionNames()" | mongo -u root -p $MONGODB_ROOT_PASSWORD admin` from within the container

**Describe the results you received:**
Actual:
- The collection `foo` is not present

**Describe the results you expected:**
Expected:
- The collection is present

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Version**
Latest bitnami/bitnami-docker-mongodb version

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Mac

**Comment by alemorcuq** [comment]
Hi, @cliffcotino.

Thank you very much for reporting this. We are working on bringing it back, I'll ping you when it's ready.

Regards,
Alejandro

**Comment by cliffcotino** [comment]
Hi @alemorcuq, thanks for the update!

**Comment by vitali-zevako** [comment]
The same for 3.6

**Comment by alemorcuq** [comment]
Hi, @vitali-zevako.

Thanks. It's something that was left out during the migration to bash scripts by mistake. It affects all versions. We are working to bring it back.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi, @cliffcotino, @vitali-zevako.

We've released a new bunch of containers that reimplement this feature. They are the following:

- `3.6.13-debian-9-r67`
- `3.6.13-ol-7-r69`
- `4.0.11-debian-9-r14`
- `4.0.11-ol-7-r14`
- `4.1.13-debian-9-r74`
- `4.1.13-ol-7-r77`

Please, let us know if it's working as expected for you.

Regards,
Alejandro

**Comment by vitali-zevako** [comment]
hi @alemorcuq,

I have tried 3.6.13-ol-7-r69
Init script is now executing automatically
But sometimes getting error during executing:

> :
INFO  ==> Loading custom scripts...
INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
MongoDB shell version v3.6.13
connecting to: mongodb://test-mongo-rs-mongodb-primary-0.test-mongo-rs-mongodb-headless.default.svc.cluster.local:27017/?gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("4fada6d0-0771-4a54-8b65-97fb23273a5f") }
MongoDB server version: 3.6.13
admin
1
2019-08-07T07:59:51.728+0000 E QUERY    [thread1] Error: error: {
        "ok" : 0,
        "errmsg" : "not master and slaveOk=false",
        "code" : 13435,
        "codeName" : "NotMasterNoSlaveOk"
} :

Maybe need to add some delay before execution.

Will try to add sleep in my .js init script.

Thank you

**Comment by javsalgar** [comment]
Please let us know if adding the sleep works for you. Maybe it makes sense for, in the case of the cluster, to have some sort of health check prior to executing the scripts.

**Comment by vitali-zevako** [comment]
@javsalgar just for sure i have added sleep 90 sec as first line in init .js script and it works stable.
I am using replica set, probably it is not required for standalone

**Comment by cliffcotino** [comment]
The fix works for a replicaset without ssl, for a cluster with ssl configuration it fails.
The problem seems to be that something went wrong with an (automated?) commit.

The relevant lines which were incorrectly overwritten (the correct content was merged in with PR #161):
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/run.sh#L15
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh#L168
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.0/debian-9/rootfs/libmongodb.sh#L178

**Comment by javsalgar** [comment]
Hi,

Could you share the logs so we can see the error message?

**Comment by cliffcotino** [comment]
Sure,
The setup is a bit more involved, but when you've setup the required certificates, I added the required SSL options:

primary configuration:
- `BITNAMI_DEBUG=true`
- `MONGODB_EXTRA_FLAGS=--sslMode=requireSSL --sslPEMKeyFile=/certificates/mongodb-primary.pem --sslClusterFile=/certificates/mongodb-primary.pem --sslCAFile=/certificates/mongoCA.crt`
- `MONGODB_CLIENT_EXTRA_FLAGS=--ssl --sslPEMKeyFile=/certificates/mongodb-primary.pem --sslCAFile=/certificates/mongoCA.crt`

secondary configuration:
- `BITNAMI_DEBUG=true`
- `MONGODB_EXTRA_FLAGS=--sslMode=requireSSL --sslPEMKeyFile=/certificates/mongodb-secondary.pem --sslClusterFile=/certificates/mongodb-secondary.pem --sslCAFile=/certificates/mongoCA.crt`
- `MONGODB_CLIENT_EXTRA_FLAGS=--ssl --sslPEMKeyFile=/certificates/mongodb-secondary.pem --sslCAFile=/certificates/mongoCA.crt`

arbiter configuration:
- `BITNAMI_DEBUG=true`
- `MONGODB_EXTRA_FLAGS=--sslMode=requireSSL --sslPEMKeyFile=/certificates/mongodb-arbiter.pem --sslClusterFile=/certificates/mongodb-arbiter.pem --sslCAFile=/certificates/mongoCA.crt`
- `MONGODB_CLIENT_EXTRA_FLAGS=--ssl --sslPEMKeyFile=/certificates/mongodb-arbiter.pem --sslCAFile=/certificates/mongoCA.crt`

The relevant parts of the logs:
```
mongodb-primary_1    |  15:48:40.18 DEBUG ==> Executing /docker-entrypoint-initdb.d/create.js
mongodb-primary_1    | MongoDB shell version v4.0.11
mongodb-primary_1    | connecting to: mongodb://mongodb-primary:27017/?gssapiServiceName=mongodb
mongodb-primary_1    | Implicit session: session { "id" : UUID("8a5ec195-09a7-46de-9715-25627956de96") }
mongodb-primary_1    | MongoDB server version: 4.0.11
mongodb-primary_1    | {
mongodb-primary_1    |  "ok" : 1,
mongodb-primary_1    |  "operationTime" : Timestamp(1565192930, 1),
mongodb-primary_1    |  "$clusterTime" : {
mongodb-primary_1    |          "clusterTime" : Timestamp(1565192930, 1),
mongodb-primary_1    |          "signature" : {
mongodb-primary_1    |                  "hash" : BinData(0,"qbZtwqg6fGwcMQrOwhEW5wnEoz8="),
mongodb-primary_1    |                  "keyId" : NumberLong("6722452407625711617")
mongodb-primary_1    |          }
mongodb-primary_1    |  }
mongodb-primary_1    | }
mongodb-primary_1    | WriteResult({ "nInserted" : 1 })
mongodb-primary_1    | bye
mongodb-primary_1    |  15:48:50.34 INFO  ==> Stopping MongoDB...
mongodb-primary_1    | 
mongodb-primary_1    |  15:49:05.39 INFO  ==> ** MongoDB setup finished! **
mongodb-primary_1    |  15:49:05.40 INFO  ==> ** Starting MongoDB **
mongodb-primary_1    | BadValue: unsupported value for sslMode requireSSL --sslPEMKeyFile=/certificates/mongodb-primary.pem --sslClusterFile=/certificates/mongodb-primary.pem --sslCAFile=/certificates/mongoCA.crt
mongodb-primary_1    | try '/opt/bitnami/mongodb/bin/mongod --help' for more information
bitnami-docker-mongodb_mongodb-primary_1 exited with code 2
mongodb-secondary_1  |  15:48:49.48 INFO  ==> ** Starting MongoDB **
mongodb-secondary_1  | BadValue: unsupported value for sslMode requireSSL --sslPEMKeyFile=/certificates/mongodb-secondary.pem --sslClusterFile=/certificates/mongodb-secondary.pem --sslCAFile=/certificates/mongoCA.crt
mongodb-secondary_1  | try '/opt/bitnami/mongodb/bin/mongod --help' for more information
bitnami-docker-mongodb_mongodb-secondary_1 exited with code 2
mongodb-arbiter_1    |  15:48:52.21 INFO  ==> Loading custom scripts...
mongodb-arbiter_1    | find: '/docker-entrypoint-initdb.d/': No such file or directory
mongodb-arbiter_1    |  15:48:52.21 INFO  ==> ** MongoDB setup finished! **
mongodb-arbiter_1    | 
mongodb-arbiter_1    |  15:48:52.23 INFO  ==> ** Starting MongoDB **
mongodb-arbiter_1    | BadValue: unsupported value for sslMode requireSSL --sslPEMKeyFile=/certificates/mongodb-arbiter.pem --sslClusterFile=/certificates/mongodb-arbiter.pem --sslCAFile=/certificates/mongoCA.crt
mongodb-arbiter_1    | try '/opt/bitnami/mongodb/bin/mongod --help' for more information
bitnami-docker-mongodb_mongodb-arbiter_1 exited with code 2
```

**Comment by javsalgar** [comment]
Hi,

From what I see, the error is not because of the user init scripts, right? It is more because of the ssl settings that are set in the nodes that are not primary. Am I correct?

**Comment by cliffcotino** [comment]
It is not because of the user init scripts themselves. All the nodes fail,
the primary node as well.
The commits causing the regression were due to this change, so that's why
I'm mentioning it here.

**Comment by cliffcotino** [comment]
@javsalgar This commit (on my fork) should fix the regression: https://github.com/cliffcotino/bitnami-docker-mongodb/commit/fd17af6c051d525a185b6377dd10f38cdfd26d8e

**Comment by juan131** [comment]
Hi @cliffcotino 

Please correct me if I'm wrong but according your commit you're just treating the env. variable **MONGODB_CLIENT_EXTRA_FLAGS** as a string instead of an array, aren't you?

Could you please explain your changes?

**Comment by cliffcotino** [comment]
@juan131 My changes only change the scripts back to what the scripts were before.
You will find that my proposed edits are directly from the git history of those files.

Change in `run.sh`:
```
[[ -z "${MONGODB_EXTRA_FLAGS:-}" ]] || flags=("${flags[@]}" "${MONGODB_EXTRA_FLAGS[@]}")
```
changed to:
```
[[ -z "${MONGODB_EXTRA_FLAGS:-}" ]] || flags+=(${MONGODB_EXTRA_FLAGS})
```

For cases when `${MONGODB_EXTRA_FLAGS}` contains multiple, space-separated arguments (e.g. `--enableFreeMonitoring=on --wiredTigerCacheSizeGB=0.5`), bash would add a string `'--enableFreeMonitoring=on --wiredTigerCacheSizeGB=0.5'` essentially with the quotes as a command line argument, which would cause the mongod daemon startup to fail.

Similar changes have been made in `libmongo.sh` (`mongodb_execute` function) - the changes in my diff for `MONGODB_CLIENT_EXTRA_FLAGS` are that there was no need for a sixth parameter, because in all function invocations the value was always equal to `MONGODB_CLIENT_EXTRA_FLAGS`

On [run.sh#L187](https://github.com/cliffcotino/bitnami-docker-mongodb/commit/fd17af6c051d525a185b6377dd10f38cdfd26d8e#diff-a4cbda33b178d696791dba969d237f07L187) we treat `MONGODB_CLIENT_EXTRA_ARGS` the same way

**Comment by juan131** [comment]
Hi @cliffcotino 

I agree on the changes you applied on the **run.sh**. As you mentioned it was even already applied in the `libmongo.sh` script.

Regarding removing the sixth parameter, I think that parameter makes no harm, even if it's not being used at this very moment.

**Comment by juan131** [comment]
By the way, I applied the change in the `run.sh` script and it'll be updated in the next revision of MongoDB

**Comment by cliffcotino** [comment]
Ok, thanks for the update. I'll re-test the containers and close this issue as soon as the new releases are available.

**Comment by juan131** [comment]
Hi @cliffcotino 

Just a quick note to let you know that `run.sh` has already been updated in the **3.6** and **4.1** branches. You can check it in the links below:

https://github.com/bitnami/bitnami-docker-mongodb/blob/master/3.6/debian-9/rootfs/run.sh
https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.1/debian-9/rootfs/run.sh

I'll let you know when the branch `4.0` is updated too.

**Comment by cliffcotino** [comment]
Ok, I've tested successfully with the `4.0.12-ol-7-r6` version of the container, so that seems okay.

Is everything alright with the release of the `4.0.x debian` branch?
I noticed that there was also no release of that version yesterday as well.

**Comment by juan131** [comment]
Hi @cliffcotino 

Some internal issues in our pipeline blocked the release of this branch. We hope to fix these issues during the day so the release of the `4.0.x debian` branch goes ahead.

**Comment by cliffcotino** [comment]
I just tested successfully with `mongodb:4.0.12-debian-9-r7` - so this issue can be closed.

@juan131 Thanks!

**Comment by juan131** [comment]
That's great @cliffcotino !! Please do not hesitate to reopen this issue or create a new one if you continue facing issues with this image.

**Comment by zffocussss** [comment]
what is MONGODB_INITSCRIPTS_DIR.I can not mount files to docker-entrypoint-initdb.d

**Comment by carrodher** [comment]
When the container is executed for the first time, it will execute the files with extensions `.sh` and `.js` located at `/docker-entrypoint-initdb.d`.

In order to have your custom files inside the docker image, you can mount them as a volume.

The [`MONGODB_INITSCRIPTS_DIR` environment variable](https://github.com/bitnami/bitnami-docker-mongodb/blob/f680f932619c94a1a2789c05e959209d7f9d4ae3/4.2/debian-9/rootfs/libmongodb.sh#L44) set by default the directory where those scripts should be placed, if you want to use another directory you can overwrite this env. variable with your desired directory and then mount this new directory.
