### ISSUE TITLE
Error executing 'postInstallation': EIO: i/o error, scandir '/bitnami/mongodb/data/db'

### ISSUE THREAD

**Issue by paxinos** [bitnami/bitnami-docker-mongodb#165]
I've had mongodb running for a few months.  During an upgrade of kubernetes on the cluster the mongodb containers restarted and now I get the following error.    Is there anything that can be done other than a full redeploy?

```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
nami INFO Initializing mongodb
Error executing 'postInstallation': EIO: i/o error, scandir '/bitnami/mongodb/data/db'
```

**Comment by juan131** [comment]
Hi @paxinos 

- How did you deploy MongoDB in K8s? I assume you're using the MongoDB Helm chart (`stable/mongodb`).
- Did you enable persistence? If so, what kind of **PVs (Persistent Volumes)** were you using in your MongoDB pods? It looks like the data at the volumes mounted at your MongoDB pods was corrupted.
- Do you have any MongoDB backup?

**Comment by paxinos** [comment]
Hi @paxinos <https://github.com/paxinos>

>
>    - How did you deploy MongoDB in K8s? I assume you're using the MongoDB
>    Helm chart (stable/mongodb).
>
>
Essentially - yes, helm chart.   Specifically Rancher's catalog system.

>
>    - Did you enable persistence? If so, what kind of *PVs (Persistent
>    Volumes)* were you using in your MongoDB pods? It looks like the data
>    at the volumes mounted at your MongoDB pods was corrupted.
>
> Rancher's Longhorn

>
>    - Do you have any MongoDB backup?
>
> Yes, but not current.   It is an 'experimental' system, so data loss right
now is not a problem.

At this point I'm more concerned about mitigating the problem in the
future.   I understand that Longhorn is not, yet, at production quality.

Pax.

**Comment by juan131** [comment]
> Rancher's Longhorn

I'm not expert on this kind of persistent volumes but, if I'm not wrong, Rancher's Longhorn project creates "local storage volumes" to be available on every K8s node, doesn't it?

The problem of using "local storage" to provision persistent volumes is that all that disk space is taken from the nodes themselves. Therefore, if the node hosting that volume crashes, you lose the data. 

For production environments, we highly recommend using PV that persist even if the cluster crushes (e.g. GCEPersistentDisk , AzureFile, AWSElasticBlockStore , etc. ). Check the complete list at: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes

Using these kind of PVs you can also use the features that Cloud providers offer you to create backups of your data periodically.

**Comment by paxinos** [comment]
Understood...  we are running on-prem with our own server blades.    The
blades did not 'crash', but Kubernetes did restart during an update of
Kubernetes.    The file system is intact.   But I do understand the concern.

So, what we really need is a self-hosted PV system...    And longhorn
distributes 'local storage' across at least three servers for each PV

Pax.


> Rancher's Longhorn
>
> I'm not expert on this kind of persistent volumes but, if I'm not wrong,
> Rancher's Longhorn project creates "local storage volumes" to be available
> on every K8s node, doesn't it?
>
> The problem of using "local storage" to provision persistent volumes is
> that all that disk space is taken from the nodes themselves. Therefore, if
> the node hosting that volume crashes, you lose the data.
>
> For production environments, we highly recommend using PV that persist
> even if the cluster crushes (e.g. GCEPersistentDisk , AzureFile,
> AWSElasticBlockStore , etc. ). Check the complete list at:
> https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes
>
> Using these kind of PVs you can also use the features that Cloud providers
> offer you to create backups of your data periodically.
>
>
>

**Comment by juan131** [comment]
Hi @paxinos 

Maybe in the [Kubernetes Storage SIG](https://github.com/kubernetes/community/tree/master/sig-storage) they can provide you more advices about the best alternative to implement storage in your on-prem cluster.
