### ISSUE TITLE
MongoDB 4.2 release

### ISSUE THREAD

**Issue by HosseinAgha** [bitnami/bitnami-docker-mongodb#168]
**Description**

Please release [MongoDB 4.2](https://docs.mongodb.com/manual/release-notes/4.2/) images. Thank you for awesome images :)

**Comment by alemorcuq** [comment]
Hi, @HosseinAgha.

Thanks for your comment. We are currently working on releasing it.

Regards,
Alejandro

**Comment by alemorcuq** [comment]
Hi, @HosseinAgha.

We released images for MongoDB 4.2. Thank you for your patience.

Regards,
Alejandro
