### ISSUE TITLE
Restarting a stopped container fails when using tmpfs

### ISSUE THREAD

**Issue by HosseinAgha** [bitnami/bitnami-docker-mongodb#172]
**Description**

We are using the docker [`tmpfs` mounts](https://docs.docker.com/storage/tmpfs/) for our integration tests to get a faster result.  
Stopping the container causes the `tmpfs` volume data to get removed and it crashes upon restart (instead of recreating the replicaset).
It seems like you are writing some files in the container's writable layer and you don't mention it in the docs.

**Steps to reproduce the issue:**

1. Run a new `bitnami/mongodb` container according to docs
2. Mount a `tmpfs` volume on the `/bitnami` directory
3. Stop the container
4. Start the container again

**Describe the results you received:**

I get the following logs when I restart the container:  

```
INFO  ==> Starting mongodb... 
INFO  ==> Starting mongod...
I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
I CONTROL  [initandlisten] MongoDB starting : pid=21 port=27017 dbpath=/opt/bitnami/mongodb/data/db 64-bit host=a2caed762fe8
I CONTROL  [initandlisten] db version v4.0.3
I CONTROL  [initandlisten] git version: 7ea530946fa7880364d88c8d8b6026bbc9ffa48c
I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.0f  25 May 2017
I CONTROL  [initandlisten] allocator: tcmalloc
I CONTROL  [initandlisten] modules: none
I CONTROL  [initandlisten] build environment:
I CONTROL  [initandlisten]     distmod: debian92
I CONTROL  [initandlisten]     distarch: x86_64
I CONTROL  [initandlisten]     target_arch: x86_64
I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: true, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { replSetName: "rset" }, security: { authorization: "disabled" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/opt/bitnami/mongodb/data/db", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, logRotate: "reopen", path: true } }
I STORAGE  [initandlisten] exception in initAndListen: NonExistentPath: Data directory /opt/bitnami/mongodb/data/db not found., terminating
I NETWORK  [initandlisten] shutdown: going to close listening sockets...
I NETWORK  [initandlisten] removing socket file: /opt/bitnami/mongodb/tmp/mongodb-27017.sock
I CONTROL  [initandlisten] now exiting
I CONTROL  [initandlisten] shutting down with code:100
mongo exited with code 100
```  

**Describe the results you expected:**

Container recreates the replica set information on restart.

**Version**

- Output of `docker version`: 

```
19.03.2
```

- Output of `docker-compose version` (if applicable):

```
1.24.1
```

**Comment by javsalgar** [comment]
Hi,

It looks to me that you are not using the latest version of the container. Could you provide us the version of the container you are using?

**Comment by HosseinAgha** [comment]
Hi @javsalgar,  

I'd be super happy if I could update to `4.2.0` image but i'm still waiting for #151 to get fixed.  
I'm currently on `bitnami/mongodb:4.0.3` (__latest__ tag).

**Comment by javsalgar** [comment]
Hi,

I see. However, I think I may have an idea of what the issue could be. Could you share your docker-compose.yaml or the commands?

**Comment by HosseinAgha** [comment]
Here you are:

```
  mongo:
    image: bitnami/mongodb:4.0.3
    volumes:
      - type: tmpfs
        target: /bitnami 
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs
      - MONGODB_ADVERTISED_HOSTNAME=mongo
```

Thanks

**Comment by HosseinAgha** [comment]
not stale

**Comment by javsalgar** [comment]
Hi,

I found the cause of the issue. Indeed, with the initialization logic based on Node.js, there's an initialization flag that gets stored inside the container and not in the mounted volume

```
nami_initialize_one() {
  local module=${1?module not specified}
  if nami inspect ${module} | grep -q '"lifecycle": "unpacked"'; then
    local inputs=
    if [[ -f /${module}-inputs.json ]]; then
      inputs=--inputs-file=/${module}-inputs.json
    fi
    nami ${NAMI_DEBUG:+--log-level ${NAMI_LOG_LEVEL:-trace}} initialize ${module} $inputs "${@:2}"
  fi
}
```

Because of this line
```
  if nami inspect ${module} | grep -q '"lifecycle": "unpacked"'; then
```

This logic does not exist anymore in our bash containers. So I'm afraid that you would have to wait for the other issue to be solved so you can restart with tmpfs.

**Comment by JLoveI** [comment]
not stale

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
