### ISSUE TITLE
No Arm64 Build + base image is hidden.

### ISSUE THREAD

**Issue by lyndon160** [bitnami/bitnami-docker-mongodb#185]
There is no Arm64 build of this image.

Also the base image is hidden so you can't manually build each layer for Arm64.

1) Can the docker file for the base image be shared so that it can be built for Arm64.
2) Can an Arm64 build of this image be put on to the container registry either via multi-arch images or by a seperate tag.

Thanks

**Comment by andresbono** [comment]
Hi @lyndon160, you can find the base image here: https://github.com/bitnami/minideb-extras-base. 

In any case, are MongoDB binaries supported for Arm64 architecture?

**Comment by lyndon160** [comment]
@andresbono that image is based on [minideb](https://github.com/bitnami/minideb).
Theres no Dockerfile there and the base image is not multi-arch. I assume this can be generated by the makefile?

The official MongoDB binaries and docker images are supported for Arm64. Their docker hub repo supports a wide range of architecures: https://hub.docker.com/_/mongo

![Screenshot 2019-11-15 at 10 59 50](https://user-images.githubusercontent.com/5150703/68938877-2c206c80-0797-11ea-84aa-f90f2067ff3a.png)

**Comment by andresbono** [comment]
> @andresbono that image is based on [minideb](https://github.com/bitnami/minideb).
> Theres no Dockerfile there and the base image is not multi-arch. I assume this can be generated by the makefile?

That's right, the parent image of `minideb-extras-base` is `minideb`. That one is created with [debootstrap](https://docs.docker.com/develop/develop-images/baseimages/#create-a-full-image-using-tar) and you should be able to build it with `make`: [README.md: Building Minideb](https://github.com/bitnami/minideb#building-minideb). You can find the logs of the builds here: https://travis-ci.org/bitnami/minideb.

Note that we haven't explored nor tested it on Arm64 so we can't tell you much more about it.

Hope this information helps!

**Comment by lyndon160** [comment]
@andresbono thanks for your response.

I've sucessfully build all of the base docker images (minideb and minideb-extras-base) for Arm64. I also rebuilt the render-template for Arm64 and replaced instances of amd64 in the scripts with arm64 equivalents.

However, when mongo runs it cuts off at  
16:39:13.65 INFO  ==> Deploying MongoDB from scratch...
with no error log.

I've decided to recreate a helm chart for the offical mongo image as it's currently less effort than fixing this.

**Comment by andresbono** [comment]
Thanks for letting us know, @lyndon160.

**Comment by naphta** [comment]
Same problem here, I'm wanting to run mongo within a k3s cluster of raspberry pi 4s. What's holding back a multiarch build? From what I can see mongodb itself supports amd64, arm64, and s390x.

**Comment by andresbono** [comment]
Hi @naphta, we are focusing all our efforts on delivering an up-to-date and secure container catalog and we are currently supporting amd64 only. We haven't explored other architectures yet.

In any case, thanks for showing interests.

**Comment by lyndon160** [comment]
@andresbono is there any interest in supporting other architectures? I think there are quite a few users requesting this.

This is quite frustrating as this affects all of the bitnami images, the main stopper is that the base images is not compiled for Arm64. Making it difficult for people interested in compiling it for Arm.

The changes are very simple to the compilation process. With Docker's `buildx` command it is very simple to create multi-arch images

For example:

`docker buildx build --platform linux/arm64, linux/amd64 -t repo/image:tag . --load` Creates a multi-arch manifest, and builds the image for both platforms.

**Comment by beltran-rubo** [comment]
Hi @lyndon160, we would really work on supporting ARM but unfortunately we are a small team right now and we have a limited bandwidth to work on this. That would require major changes in our pipeline to support building & testing ARM containers. 

We would be also happy to integrate any changes in the Helm Chart (e.g. parameters) to make it compatible with any other MongoDB ARM container image.

**Comment by arslanakhtar61** [comment]
@lyndon160 can you provide a sample example on how you managed to create the helm chart for the official mongo image specific to arm64 (RPI-4 running Ubuntu 64-Bit) architecture or similar. I am having trouble deploying bitnami/mongodb image on raspberry pi - 4 arm64 running Ubuntu 64-Bit. Can we build an arm64 arch docker image using official or bitnami mongodb docker image on our x86_x64 local machine?
