### ISSUE TITLE
Bitnami MongoDB image and Persistent storage on Azure WebApp for containers

### ISSUE THREAD

**Issue by TesterBoy2020** [bitnami/bitnami-docker-mongodb#191]
Hi,

Using the bitnami/mongodb image I'm trying to use the Azure WebApp persistent storage yet receive the following errors:

```
[initandlisten] WiredTiger error (1) [1578945008:517839][32:0x7f235903f080], connection: __posix_open_file, 672: /bitnami/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1578945008:517839][32:0x7f235903f080], connection: __posix_open_file, 672: /bitnami/WiredTiger.wt: handle-open: open: Operation not permitted
[initandlisten] Failed to start up WiredTiger under any compatibility version.
[initandlisten] Reason: 1: Operation not permitted
[initandlisten] Fatal Assertion 28595 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 707
```
I have the azure web app set to:
`WEBSITES_ENABLE_APP_SERVICE_STORAGE=TRUE`

and the docker-compose contains:
```
volumes:
- ${WEBAPP_STORAGE_HOME}/data:/bitnami
```

I can see the db files created at the persistent storage location but still receive the errors.

I also noticed i can't change the folders permissions which are set to:
 `drwxrwxrwx 2 nobody nogroup.`

Same behavior when using an Azure Storage account as the persistent storage.

Why is the mongod process crashing even tough it Can write files to the persistent storage?

Thank You.

**Comment by andresbono** [comment]
Hi @TesterBoy2020,

Can you compare the structure of files and permissions for a regular docker-compose deployment (see the snippet below) and the one that you are launching? You can execute the following command inside the container:

`ls -lR /bitnami/`
```
/bitnami/:
total 4
drwxrwxr-x 3 root root 4096 Jan 15 07:47 mongodb

/bitnami/mongodb:
total 4
drwxrwxr-x 3 root root 4096 Jan 15 07:47 data

/bitnami/mongodb/data:
total 4
drwxr-xr-x 4 1001 root 4096 Jan 15 07:48 db

/bitnami/mongodb/data/db:
total 248
-rw------- 1 1001 root    45 Jan 15 07:47 WiredTiger
-rw------- 1 1001 root    21 Jan 15 07:47 WiredTiger.lock
-rw------- 1 1001 root  1064 Jan 15 07:48 WiredTiger.turtle
-rw------- 1 1001 root 61440 Jan 15 07:48 WiredTiger.wt
-rw------- 1 1001 root  4096 Jan 15 07:47 WiredTigerLAS.wt
-rw------- 1 1001 root 16384 Jan 15 07:47 _mdb_catalog.wt
-rw------- 1 1001 root 16384 Jan 15 07:47 collection-0--2462597566719340197.wt
-rw------- 1 1001 root 32768 Jan 15 07:48 collection-2--2462597566719340197.wt
-rw------- 1 1001 root  4096 Jan 15 07:47 collection-4--2462597566719340197.wt
drwx------ 2 1001 root  4096 Jan 15 07:49 diagnostic.data
-rw------- 1 1001 root 16384 Jan 15 07:47 index-1--2462597566719340197.wt
-rw------- 1 1001 root 32768 Jan 15 07:48 index-3--2462597566719340197.wt
-rw------- 1 1001 root  4096 Jan 15 07:47 index-5--2462597566719340197.wt
-rw------- 1 1001 root  4096 Jan 15 07:48 index-6--2462597566719340197.wt
drwx------ 2 1001 root  4096 Jan 15 07:47 journal
-rw------- 1 1001 root     2 Jan 15 07:47 mongod.lock
-rw------- 1 1001 root 32768 Jan 15 07:48 sizeStorer.wt
-rw------- 1 1001 root   114 Jan 15 07:47 storage.bson

/bitnami/mongodb/data/db/diagnostic.data:
total 36
-rw------- 1 1001 root 23135 Jan 15 07:48 metrics.2020-01-15T07-47-54Z-00000
-rw------- 1 1001 root  9853 Jan 15 07:49 metrics.interim

/bitnami/mongodb/data/db/journal:
total 307200
-rw------- 1 1001 root 104857600 Jan 15 07:48 WiredTigerLog.0000000002
-rw------- 1 1001 root 104857600 Jan 15 07:47 WiredTigerPreplog.0000000001
-rw------- 1 1001 root 104857600 Jan 15 07:47 WiredTigerPreplog.0000000002
```

**Comment by TesterBoy2020** [comment]
Hi @andresbono 

As i noted, after designating the volume of the persistent storage the permissions of the /bitnami folder and it's content change from `root `to` drwxrwxrwx 2 nobody nogroup`.

I do however see database files being created under the /bitnami folder (with the above permissions).

Thank You.

**Comment by andresbono** [comment]
Hi @TesterBoy2020, this is a similar issue: https://github.com/bitnami/bitnami-docker-mongodb/issues/166. Maybe it's a good idea to try other containers to know if there is something special with MongoDB and Azure Storage.

**Comment by TesterBoy2020** [comment]
Thanks for the link,
I have overcame the permissions issue by mounting the Azure Storage using SMB v3 directly from the container, but now it seems there is a different issue with the SMBv3 protocol and MongoDB..

**Comment by andresbono** [comment]
Thanks for sharing your solution with us, @TesterBoy2020.
