### ISSUE TITLE
Replica set does not scale

### ISSUE THREAD

**Issue by carlosmdb** [bitnami/bitnami-docker-mongodb#192]
**Description**

I followed the instructions to deploy a replica set and used the scale option (same exact command as in the instructions) and I can see that I have all the dockers I am expecting but when I look in MongoDB I can only find 3 nodes in my replica set - 1 primary, 1 secondary and 1 arbiter  - I can't get more than 1 secondary in the replica set.

**Steps to reproduce the issue:**

1. Execute in your shell:
`docker-compose -f docker-compose-replicaset.yml up --detach --scale mongodb-primary=1 --scale mongodb-secondary=3 --scale mongodb-arbiter=1`

**Describe the results you received:**

I can see the 5 docker containers created and running normally as I would expect. But when connecting to the Mongo shell and checking the configuration I only have 1 secondary node and not 3.

**Describe the results you expected:**

I would expect to see a replica set with 1 primary, 3 secondaries and 1 arbiter.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have tried this with the latest image, 4.0 and 4.2.2 and I always get the same result...
'bitnami/mongodb:latest'
'bitnami/mongodb:4.0'
'bitnami/mongodb:4.2.2'

**Version**

- Output of `docker version`:

```
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
❯ docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: ELPD:EWZX:BS4E:6WSS:AG2G:XYXK:A4KO:JVLC:NIQR:Z7BE:M7EU:435C
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 64
  Goroutines: 79
  System Time: 2020-01-14T12:00:01.8267119Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
❯ docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
MacOS Catalina 10.15.2

**Comment by rafariossaa** [comment]
Hi @carlosmdb ,
  I was able to reproduce this issue, thanks for noticing it.
  Let me try to find a fix for it. We will come back when I have news.

**Comment by rafariossaa** [comment]
Hi @carlosmdb 
  I have created an internal task to address this issue. We will come back to you as soon as we have news.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
