### ISSUE TITLE
Support Envoy/Istio by Exposing Localhost Override Variable

### ISSUE THREAD

**Issue by armsnyder** [bitnami/bitnami-docker-mongodb#194]
This image currently does not work when deploying into an Istio-enabled Kubernetes cluster. When the primary host is starting up, the setup script fails to finish configuring the primary node and instead outputs repeatedly:

```bash
exception: connect failed
```

The reason for this is how the `mongodb_is_primary_node_initiated` function in `libmongodb.sh` is written:

```bash
mongodb_is_primary_node_initiated() {
    local node="${1:?node is required}"
    local result
    result=$(mongodb_execute "root" "$MONGODB_ROOT_PASSWORD" "admin" "$node" "$MONGODB_PORT_NUMBER" <<EOF
rs.initiate({"_id":"$MONGODB_REPLICA_SET_NAME", "members":[{"_id":0,"host":"$node:$MONGODB_PORT_NUMBER","priority":5}]})
EOF
)

    grep -q "\"ok\" : 1" <<< "$result"
}
```

 It assumes that the advertised hostname `$node` can be used to make a local connection to the database. This is not the case in an Envoy/Istio deployment because the advertised hostname will expect a mTLS connection. The hostname used to connect to the local database in an Envoy/Istio deployment must be `127.0.0.1`.

I would suggest modifying the function to be:

```bash
 mongodb_is_primary_node_initiated() {
    local node="${1:?node is required}"
    local result
    result=$(mongodb_execute "root" "$MONGODB_ROOT_PASSWORD" "admin" "$(get_mongo_local_hostname)" "$MONGODB_PORT_NUMBER" <<EOF
rs.initiate({"_id":"$MONGODB_REPLICA_SET_NAME", "members":[{"_id":0,"host":"$node:$MONGODB_PORT_NUMBER","priority":5}]})
EOF
)

    grep -q "\"ok\" : 1" <<< "$result"
}
```

And add a function:

```bash
get_mongo_local_hostname() {
    if [[ -n "$MONGODB_LOCAL_HOSTNAME" ]]; then
        echo "$MONGODB_LOCAL_HOSTNAME"
    else
        get_mongo_hostname
    fi
}
```

So that the local hostname could be overridden by optionally setting `MONGODB_LOCAL_HOSTNAME=127.0.0.1` for Envoy users.

**Comment by marcosbc** [comment]
Hi @armsnyder, thanks for contributing with the PR! I have added a couple comments on some ideas and improvements.
