### ISSUE TITLE
Restarting Primary Replica Fails to Start: Error AlreadyInitialized

### ISSUE THREAD

**Issue by armsnyder** [bitnami/bitnami-docker-mongodb#196]
**Description**

I am running a PSA (primary-secondary-arbiter) three-node setup, in Kubernetes. Everything works great initially. The nodes start fine and I can connect with and use the DB. However, if I restart the primary node, I find that it hangs during startup at the log message "Configuring MongoDB primary node" and never re-joins the replicaset.

Based on my own investigation I believe that this is due to a bug in the `libmongodb.sh` script. The function `mongodb_is_primary_node_initiated` seems to be where the hang occurs. The function is initiating the replicaset and expecting that the replicaset was created. It does not consider the possibility that the replicaset already exists. Its `grep` check only looks for `"ok" : 1`, but it should also be checking for `"codeName" : "AlreadyInitialized"`, which is an equally valid response code where `ok` is `0`. In other words, if the replicaset already exists, then the `mongodb_is_primary_node_initiated` function should exit successfully. This would fix the hang.

**Steps to reproduce the issue:**

1. Create a PSA docker-compose set up, where both the primary and the secondary nodes have their own independent attached volumes.
1. Deploy the docker-compose file.
1. Force-kill the primary node but NOT its volume.
1. The replacement primary node will hang and not join the replicaset.

**Describe the results you received:**

The primary node hangs at this point:

```
 08:30:29.13 
 08:30:29.13 Welcome to the Bitnami mongodb container
 08:30:29.14 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 08:30:29.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 08:30:29.14 Send us your feedback at containers@bitnami.com
 08:30:29.14 
 08:30:29.14 INFO  ==> ** Starting MongoDB setup **
 08:30:29.15 INFO  ==> Validating settings in MONGODB_* env vars...
 08:30:29.16 INFO  ==> Initializing MongoDB...
 08:30:29.16 INFO  ==> No injected configuration files found. Creating default config files...
 08:30:29.16 INFO  ==> Deploying MongoDB from scratch...
 08:30:29.78 INFO  ==> Creating users...
 08:30:29.78 INFO  ==> Creating root user...
 08:30:29.88 INFO  ==> Users created
 08:30:29.88 INFO  ==> Writing keyfile for replica set authentication: changeme2 /opt/bitnami/mongodb/conf/keyfile
 08:30:29.89 INFO  ==> Configuring MongoDB replica set...
 08:30:29.89 INFO  ==> Stopping MongoDB...
 08:30:31.92 INFO  ==> Configuring MongoDB primary node
```

I executed into the running container and did some debugging by connecting to the database and running the same command that is being run by `libmongodb.sh` (`rs.initiate({"_id":"changeme2","members":[{"_id":0,"host":"asnyder-mongodb-primary-0.asnyder-mongodb-primary","priority":5}]})`).

```
I have no name!@asnyder-mongodb-primary-0:/$ mongo mongodb://root:changeme@127.0.0.1:27017/admin
MongoDB shell version v4.2.3
connecting to: mongodb://127.0.0.1:27017/admin?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("73d2bc10-be77-49b5-bd40-cf89ffde57cf") }
MongoDB server version: 4.2.3
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
2020-02-03T08:28:14.991+0000 I  STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
---
Enable MongoDB's free cloud-based monitoring service, which will then receive and display
metrics about your deployment (disk utilization, CPU, operation statistics, etc).

The monitoring data will be available on a MongoDB website with a unique URL accessible to you
and anyone you share the URL with. MongoDB may use this information to make product
improvements and to suggest MongoDB products and deployment options to you.

To enable free monitoring, run the following command: db.enableFreeMonitoring()
To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---

replicaset:STARTUP2> rs.initiate({"_id":"changeme2","members":[{"_id":0,"host":"asnyder-mongodb-primary-0.asnyder-mongodb-primary","priority":5}]});
{
        "ok" : 0,
        "errmsg" : "already initialized",
        "code" : 23,
        "codeName" : "AlreadyInitialized"
}
replicaset:STARTUP2>
```

The response

```
{
        "ok" : 0,
        "errmsg" : "already initialized",
        "code" : 23,
        "codeName" : "AlreadyInitialized"
}
```

indicates to me that the replicaset is already created.

**Describe the results you expected:**

I would expect that the above response should constitute a success, and the script should continue without hanging.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Kubernetes v1.14.9-eks

**Comment by rafariossaa** [comment]
Hi @armsnyder ,
  Thanks for noticing this and the well explained issue.
  Also, thanks you very much for your PR.

**Comment by juan131** [comment]
Hi @armsnyder 

Your PR was merged, we replicated your changes in our internal system and new images including your changes were released.

Please give it a try to the latest version: `4.2.3-debian-10-r10`?
