### ISSUE TITLE
Secondary Fails to Join Cluster After Reelection

### ISSUE THREAD

**Issue by armsnyder** [bitnami/bitnami-docker-mongodb#198]
**Description**

Similar issue as #196 but this time I think the `mongodb_is_secondary_node_pending` function in `libmongodb.sh` needs to accept a `103` error code (codeName "NewReplicaSetConfigurationIncompatible").

The problem is that the `libmongodb.sh` script is preventing a secondary replica from starting if its config is not aligned with the primary's config. This can happen in cases where the secondary replica is restarted while it has the role of primary. If an election happens while it is down, then the `mongodb_is_secondary_node_pending` function will block due to the `103` error indicating an incompatible configuration. Rather than blocking, it should allow the secondary node to start and sync with the replicaset.

**Steps to reproduce the issue:**

1. Create a 3-node PSS replicaset
2. Shutdown the primary
3. Simultaneously restart the primary and shutdown the secondary which was elected to primary
4. Restart the stopped secondary
5. Notice the restarted secondary cannot start

**Describe the results you received:**

The logs for the secondary stops at the log "Adding node to the cluster"

**Describe the results you expected:**

I would expect the secondary to be allowed to sync with the replicaset.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Kubernetes v1.14.9-eks

**Comment by juan131** [comment]
Hi @armsnyder 

Thanks so much for reporting this issue and creating a PR to address it!! I'll take a look to it!

**Comment by juan131** [comment]
Hi @armsnyder 

Your PR was merged, we replicated your changes in our internal system and new images including your changes were released.

Please give it a try to the latest version: `4.2.3-debian-10-r10`?
