### ISSUE TITLE
[bitnami/mongodb] Database gets dropped if no document is inserted

### ISSUE THREAD

**Issue by javsalgar** [bitnami/bitnami-docker-mongodb#201]
After some further testing of this issue I think that the customer user, password, and database **are** being created but the database is not persisting without any documents being inserted so mongodb is dropping the database and in turn dropping the user and password.

In my values file I've defined something like below:
```
usePassword: true
# existingSecret: name-of-existing-secret
# mongodbRootPassword:
mongodbUsername: user
# mongodbPassword:
mongodbDatabase: database
```
I also have some custom init scripts being passed in by adding them to the /files/docker-entrypoint-initdb.d/ directory.  Using these scripts I'm creating a few collections and inserting documents.  With this configuration I am able to use the $MONGODB_ROOT_PASSWORD, $MONGODB_USER, and $MONGODB_PASSWORD variables with no issues.  As per the documentation $MONGODB_ROOTPASSWORD and $MONGODB_PASSWORD are generating random strings.  All of my collections and documents insert correctly and I'm able to connect to the database and it appears everything is working great.

When I test without my scripts being passed in to the container, as noted above the custom database is not present and obviously then the custom user isn't being created either.

If this behavior can be further confirmed and verified, can a default document be passed in when creating the custom database and user?  Or possibly adding documentation to the README that a requirement for passing in a custom database and user is to also add a custom script to the /files/docker-entrypoint-initdb.d/ directory that inserts at least one document into the custom database?

_Originally posted by @cuzzo333 in https://github.com/bitnami/charts/issues/1655#issuecomment-596160119_

**Comment by javsalgar** [comment]
Hi,

My experiments so far:

- Installed the chart

```
helm install mongo bitnami/mongodb --set mongodbDatabase=mydatabase --set mongodbUsername=jsalmeron
```

I checked that I can access the database

```
mongodb@mongo-mongodb-6c97c76f45-2gs4f:/$ mongo -u jsalmeron -p $MONGODB_PASSWORD mydatabase
MongoDB shell version v4.2.4
connecting to: mongodb://127.0.0.1:27017/mydatabase?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("5ca68296-b568-40c9-9083-04f5cbaa84f3") }
MongoDB server version: 4.2.4
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2020-03-13T10:29:34.838+0000 I  STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
> 
```

I deleted the pod and tried again

```
mongodb@mongo-mongodb-79f658bb49-8xw7d:/$  mongo -u jsalmeron -p $MONGODB_PASSWORD mydatabase
MongoDB shell version v4.2.4
connecting to: mongodb://127.0.0.1:27017/mydatabase?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("a768801b-ed4a-44a3-aabe-361a6fde7a3b") }
MongoDB server version: 4.2.4
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
2020-03-13T10:35:34.179+0000 I  STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
>
```

I can still access the database. Is there anything else that I'm missing?

**Comment by jorge-romero** [comment]
Hi! I'm having the same problem trying to connect to mongodb from one container to another one.
Did you find any solution?

**Comment by javsalgar** [comment]
Did you try following the same steps as in my reply? Are you using a special storage system?

**Comment by synth3tk** [comment]
Is this supposed to be working now? Using the Helm chart, it doesn't seem to be keeping the database still.

**Comment by javsalgar** [comment]
Hi,

Could you provide more details about the platform and storage you are using? As you can see here, I was unable to reproduce the issue

https://github.com/bitnami/bitnami-docker-mongodb/issues/201#issuecomment-598657501

**Comment by synth3tk** [comment]
After switching to the latest chart version, I can no longer reproduce it.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know!

**Comment by rileyhun** [comment]
I can confirm that I'm also getting the same error. Has this been resolved?

**Comment by javsalgar** [comment]
Hi,

We would need more details in order to reproduce the issue, as you can see above, I've been unable to reproduce it.

**Comment by rileyhun** [comment]
I'm using GKE. Here's my cluster details:

MASTER_VERSION - 1.14.10-gke.36
MASTER_IP - 35.196.224.86
MACHINE_TYPE - n1-standard-2
NODE_VERSION - 1.14.10-gke.36
NUM_NODES - 3

Then I do the following commands:

`helm install ${CLUSTER_NAME} bitnami/mongodb-sharded
`

Next I try to access mongos from the the mongos pod:

`kubectl exec -ti ${POD_NAME} -- mongo`

This results in the following error:

`
MongoDB shell version v4.2.8
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("31a85781-7643-44fa-8173-d0a0650a5a5d") }
MongoDB server version: 4.2.8
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
2020-07-14T01:01:05.847+0000 I  STORAGE  [main] In File::open(), ::open for '//.mongorc.js' failed with Permission denied
`

**Comment by javsalgar** [comment]
Hi,

The `/.mongorc.js` error seems more like a warning than an error. Are you unable to add data the collection?

**Comment by Shilagrawal** [comment]
@javsalgar  I am facing the same issue, 

I am also facing the same issue, somehow This was working fine 2 months back with helm passing mongoUsername and mongoPassword for adding a new user however now that  doesn't work I also tried to install older chart versions of 4.4.12 4.4.10 no luck where as same charts worked for me 2 months back with these values did something change here how do i overcome going to each shard and then creating a user is not a viable solution !!
