### ISSUE TITLE
custom config file not detected !

### ISSUE THREAD

**Issue by thomaslc66** [bitnami/bitnami-docker-mongodb#204]
**Description**

The configuration paragraph in the readme tells to map a host volume to :/bitnami/mongodb/conf
But this post tells us to map to /opt/bitnami/mongodb/conf

> Hi @sameersbn 
> Thanks for reporting this issue. We just published a new version fixing this issue (**3.6.5-r12** & 
> **3.7.9-r6**). The configuration file is not persisted now by default unless it's forced to be persisted 
> mounting a volume on **/opt/bitnami/mongodb/conf**.
> The README.md file has been updated too according to these changes too.
> Could you please try using this new version? Feel free to close the issue if you consider it solved.

_Originally posted by @juan131 in https://github.com/bitnami/bitnami-docker-mongodb/issues/98#issuecomment-395366421_

**Steps to reproduce the issue:**

1. map the conf file `-v '/mnt/user/appdata/mongodb/conf/':'/bitnami/mongodb/conf/`
2. See in log that the default conf file is used

**Describe the results you received:**
The default conf file is used

**Describe the results you expected:**
I've mapped this in my docker command :` -v '/mnt/user/appdata/mongodb/conf/':'/bitnami/mongodb/conf/` but the container still use the default conf file insted: The mapped conf filed should be used

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea838
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 5
  Paused: 0
  Stopped: 3
 Images: 13
 Server Version: 19.03.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.107-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.41GiB
 Name: T-Rex
 ID: E45T:JZT4:TTSZ:S4DS:K4IG:AD77:DRTA:CPJE:STJ4:RNYO:SEFI:4U6H
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
using unraid
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @thomaslc66,

could you tell me your configuration? please. 
I try with:
``` 
docker run --name mongodb -v /path/to/mongodb-configuration-persistence:/bitnami/mongodb/conf bitnami/mongodb:latest
```
edit the file `/path/to/mongodb-configuration-persistence/mongodb.conf`
for example:
```setParameter = logLevel=5```
and **restart** the container:
```
docker restart mongodb
```
And it's working

I hope that helps you.
