### ISSUE TITLE
[Question] Arbiter replicates but not primary and secondary containers

### ISSUE THREAD

**Issue by mogupta** [bitnami/bitnami-docker-mongodb#207]
Awesome work. One click install the mongodb cluster

I am using the following docker-compose with docker swarm
https://pastebin.com/raw/MQpqMvDt

Everything is working fine. Here is the setup
Primary  - wroker (node)
Secondary - wroker2 (node) 
Arbiter - wroker (node)
Sorry about the spelling mistake above. I know its not a good advise to have arbiter on the same node as primary or secondary node. 
When I turn off the wroker node , the arbiter services replicates itself to manager / wroker2 node but doesn't replicate primary service. This makes sense but I am not sure how it is making this decision? Is the volume attached to the primary node preventing replication. 

Same goes for secondary.  Please advise

Mohit

**Comment by Mauraza** [comment]
Hi @mogupta,

About the information on replication, you can see the [documentation of mongo](https://docs.mongodb.com/manual/replication/). I think you can find all the information there.

**Comment by mogupta** [comment]
Hi @Mauraza , this is more of a docker and docker swarm question and how things are setup by bitnami scripts.

**Comment by Mauraza** [comment]
Hi @mogupta,

In this page appear "An arbiter will always be an arbiter whereas a primary may step down and become a secondary and a secondary may become the primary during an election.". The Docker Swarm is an orchestrator to make sure it replicates if something goes wrong.  

The scripts you can find [here](https://github.com/bitnami/bitnami-docker-mongodb/tree/master/4.2/debian-10/rootfs/opt/bitnami/scripts)  their configure the docker to run with the environments variables. 

I don't know if that answers your question if no could you be more specific

**Comment by mogupta** [comment]
Sorry I wasn't clear in my question. I will take a second shot at it.
```
docker stack deploy --compose-file docker-compose.yml mongo
```
Now lets assume the three containers gets deployed to three different machines. 
1. If I turn off the machine with primary node, secondary node takes over and everything works fine. 
2. If I turn off the secondary machine , replication stops and everything works fine since the primary is alive
3. When I turn off the arbiter machine , docker spins up a new arbiter in one of the machines. 

My question is why only arbiter container is recreated , why not primary or secondary. What configuration stops the docker from spinning new instances of primary and secondary

**Comment by Mauraza** [comment]
Hi @mogupta, 

that behaviour is per mongo and its replica [configuration set ](https://docs.mongodb.com/manual/core/replica-set-architecture-three-members/#primary-with-a-secondary-and-an-arbiter-psa)
