### ISSUE TITLE
[helm/mongodb] Mongo replica set not operational after Kubernetes cluster restart

### ISSUE THREAD

**Issue by bfreuden** [bitnami/bitnami-docker-mongodb#211]
**Description**

After installing a MongoDB replica set with the Helm chart, the MongoDB replica set is working fine.
Once the whole Kubernetes cluster have been restarted, the replica set is no longer working.

The same thing is happening after deleting pods and letting Kubernetes recreating them.

**Steps to reproduce the issue:**

Create 2 persistent volumes with ``storageClassName: mongovol``. Example for one of them:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-mongovol0
  labels:
    type: local
spec:
  storageClassName: mongovol
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/kubernetes/mongovol0"
```

Install the MongoDB replica set with the Helm chart:
```bash
helm repo add bitnami https://charts.bitnami.com/bitnami
create ns mongodb
helm install  --namespace mongodb -f mymongo-values.yaml mymongo bitnami/mongodb
```
Where ``mymongo-values.yaml `` is containing:
```yaml
usePassword: true
mongodbRootPassword: secret
useStatefulSet: true
ingress:
  enabled: true
metrics:
  enabled: true
replicaSet:
  enabled: true
  replicas:
    secondary: 1
persistence:
  storageClass: mongovol
```
Once over you have 3 pods: ``mymongo-mongodb-arbiter-0``, ``mymongo-mongodb-primary-0`` and ``mymongo-mongodb-secondary-0``.

After a connection to the replica set, the ``rs.status()`` MongoDB shell command is working fine.

Restart the Kubernetes cluster or simulate a cluster restart by deleting pods (it yields the same error):
```bash
kubectl -n mongodb delete pods mymongo-mongodb-arbiter-0 mymongo-mongodb-primary-0 mymongo-mongodb-secondary-0
```
After a connection to the replica set, the ``rs.status()`` command is returning:

**Describe the results you received:**

```json
{
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}
```
**Describe the results you expected:**

I would expect the command to return the replica set config instead of the error message above.

**Additional information you deem important (e.g. issue happens only occasionally):**

When having a look at primary and secondary logs:
```bash
kubectl logs mymongo-mongodb-primary-0 mongodb-primary | grep -v -E "(connection accepted)|(end connection)|(received client metadata)|(Successfully authenticated)"
kubectl logs mymongo-mongodb-secondary-0 mongodb-secondary | grep -v -E "(connection accepted)|(end connection)|(received client metadata)|(Successfully authenticated)"
```
We can see those errors that might be related to the probelm:
```text
2020-05-02T09:06:39.374+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb") failed: Name or service not known
2020-05-02T09:06:57.771+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-arbiter-0.mymongo-mongodb-headless.mongodb") failed: Name or service not known
2020-05-02T09:07:23.836+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-secondary-0.mymongo-mongodb-headless.mongodb") failed: Name or service not known
2020-05-02T09:08:01.350+0000 W  REPL     [replexec-0] Locally stored replica set configuration does not have a valid entry for the current node; waiting for reconfig or remote heartbeat; Got "NodeNotFound: No host described in new configuration 3 for replica set rs0 maps to this node" while validating
2020-05-02T09:08:01.350+0000 I  REPL     [replexec-0] This node is not a member of the config
2020-05-02T09:08:01.350+0000 I  REPL     [replexec-0] transition to REMOVED from STARTUP
```
The problem is those hostnames are actually correct. If you run:
```bash
kubectl run myshell -it --rm --image busybox -- sh
ping mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb
ping mymongo-mongodb-secondary-0.mymongo-mongodb-headless.mongodb
ping mymongo-mongodb-arbiter-0.mymongo-mongodb-headless.mongodb
```
Then hostnames are actually resolved correctly:
```bash
PING mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb (10.233.92.177): 56 data bytes
64 bytes from 10.233.92.177: seq=0 ttl=62 time=0.545 ms
PING mymongo-mongodb-secondary-0.mymongo-mongodb-headless.mongodb (10.233.96.77): 56 data bytes
64 bytes from 10.233.96.77: seq=0 ttl=62 time=0.597 ms
PING mymongo-mongodb-arbiter-0.mymongo-mongodb-headless.mongodb (10.233.90.213): 56 data bytes
64 bytes from 10.233.90.213: seq=0 ttl=63 time=0.099 ms
```
So it might be possible that DNS Kubernetes DNS resolution is not operational when pods are starting. 

This has already been reported in the past as a kube-dns bug (?): 

https://github.com/kubernetes/kubernetes/issues/54798

My Kubernetes cluster is using coredns.

Do you think this can be the root cause of the problem?

Maybe the startup script of the container could wait for hostname (MONGODB_ADVERTISED_HOSTNAME variable) to be resolvable before starting mongod? I don't know if that makes any sense though...

In any case: thank you for this great Helm chart!

**Version**

- Output of `docker version`:

```
Docker version 19.03.8, build afacb8b7f0
```

- Output of `kubectl version --short`:

```
Client Version: v1.18.0
Server Version: v1.17.5
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Bare metal cluster installed 2 weeks ago with Kubespray on 3 Ubuntu 18.04 server machines.

**Comment by carrodher** [comment]
Hi, I am trying to reproduce the issue without the PV and I am not able to see this situation. What I am doing is:
- Using this values (same parameters except `persistence .storageClass`)
```yaml
usePassword: true
mongodbRootPassword: secret
useStatefulSet: true
ingress:
  enabled: true
metrics:
  enabled: true
replicaSet:
  enabled: true
  replicas:
    secondary: 1
```
- Then deploy the chart with
```
▶ helm install -f myvalue.yaml mymongo bitnami/mongodb
```
- Everything is running as expected:
```
▶ kubectl get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
mymongo-mongodb-arbiter-0                              1/1     Running   0          2m35s
mymongo-mongodb-primary-0                              2/2     Running   0          2m35s
mymongo-mongodb-secondary-0                            2/2     Running   0          2m35s
```
- Delete pods:
```
▶ kubectl delete pods mymongo-mongodb-arbiter-0 mymongo-mongodb-primary-0 mymongo-mongodb-secondary-0
pod "mymongo-mongodb-arbiter-0" deleted
pod "mymongo-mongodb-primary-0" deleted
pod "mymongo-mongodb-secondary-0" deleted
```
- Wait a while and everything is up and running again:
```
▶ kubectl get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
mymongo-mongodb-arbiter-0                              1/1     Running   0          5m50s
mymongo-mongodb-primary-0                              2/2     Running   0          5m19s
mymongo-mongodb-secondary-0                            2/2     Running   0          5m21s
```
- Everything using:
```
▶ helm list
NAME                 	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART           	APP VERSION
mymongo              	default  	1       	2020-05-04 13:44:14.49058588 +0000 UTC 	deployed	mongodb-7.14.0  	4.2.6
```
- In the logs there are no references to the same errors:
```
▶ kubectl logs mymongo-mongodb-primary-0 mongodb-primary | grep 'fail'
2020-05-04T13:48:43.112+0000 I  REPL_HB  [replexec-0] Heartbeat to mymongo-mongodb-arbiter-0.mymongo-mongodb-headless.default.svc.cluster.local:27017 failed after 2 retries, response status: HostUnreachable: Error connecting to mymongo-mongodb-arbiter-0.mymongo-mongodb-headless.default.svc.cluster.local:27017 (10.30.0.165:27017) :: caused by :: Connection refused
```

Are you able to reproduce the issue in your environment without using the PV? Can you try the above values.yaml?

**Comment by bfreuden** [comment]
Hi,
Thank you answering so fast, and thank you for the test!
I will do as you're suggesting and keep you posted before next week.
Actually I've already tried but, at the moment, primary and secondary pods are complaining about unbound PVCs. So I need to setup some kind of dynamic volume provisioning on my bare metal cluster (I'll setup NFS dynamic volume provisioning).

**Comment by bfreuden** [comment]
Hi,

I've finally setup dynamic volume provisioning on my cluster using this Helm chart:
[https://hub.helm.sh/charts/stable/nfs-client-provisioner](https://hub.helm.sh/charts/stable/nfs-client-provisioner)
```bash
helm install -n nfs-client-provisioner -f nfs-client-provisioner-values.yaml nfs-client-provisioner stable/nfs-client-provisioner
```
With ``nfs-client-provisioner-values.yaml`` containing recommended NFS mount options for MongoDB and setting the storage class as the default one (so I can omit it in the bitnami/mongodb chart):
```yaml
nfs:
  server: node1
  path: /srv/nfs/kubedynamic
  mountOptions: [ bg, nolock, noatime ] # recommended mount options
storageClass:
  archiveOnDelete: false
  defaultClass: true
```
Then I precisely followed your procedure (including checking mongodb replica set was working fine before deleting pods!) but I unfortunately still have the same problem:
```bash
 kubectl logs mymongo-mongodb-primary-0 mongodb-primary | grep 'fail'
```
```text
2020-05-08T14:45:50.908+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.default") failed: Name or service not known
2020-05-08T14:45:50.950+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-secondary-0.mymongo-mongodb-headless.default") failed: Name or service not known
```
And ``rs.status()`` is still not ok:
```json
{
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}
```
Unless you have another suggestion I will try to tweak the ``/opt/bitnami/scripts/mongodb/entrypoint.sh`` so it waits a bit before starting mongod (just in case it is a matter of a late dns configuration of the pod).

**Comment by bfreuden** [comment]
Hi,

**Executive summary** (details below)

I finally managed to get the MongoDB replica set working after killing pods but it required:
* modifying  ``entrypoint.sh`` of the mongodb docker image to wait for the MONGODB_ADVERTISED_HOSTNAME to be resolvable by the container before starting mongod (it takes 10 seconds on my cluster)
* disabling  ``livenessProbe`` and ``readinessProbe`` in the mongodb chart

So it looks like the MONGODB_ADVERTISED_HOSTNAME is not resolvable before the pod is considered Alive or Ready (I don't know which one is important) but, to be considered as such by k8s, it requires to start mongod. The problem is: mongod requires a resolvable MONGODB_ADVERTISED_HOSTNAME to **re**start successfully...

I would be very happy to have your take on that (because I'm definitely a Kubernetes newbie).

**Details**

As MongoDB is complaining about ``getaddrinfo`` failing to resolve MONGODB_ADVERTISED_HOSTNAME:
```text
getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb") failed: Name or service not known
```
... I have create a little C program that is waiting until ``getaddrinfo`` is successful (checking every 500 ms, waiting 60 seconds max): [https://gist.github.com/bfreuden/ee6fd78de42dd4fc92357cbf0f0e895b](https://gist.github.com/bfreuden/ee6fd78de42dd4fc92357cbf0f0e895b)

... and I've modified two files of the bitnami mongodb image (``rootfs/opt/bitnami/scripts/mongodb/entrypoint.sh`` and ``rootfs/opt/bitnami/scripts/mongodb/run.sh``) in order to run this little program before starting mongod:
```bash
info "[entrypoint] Checking getaddrinfo(\"$MONGODB_ADVERTISED_HOSTNAME\")"
/opt/bitnami/scripts/mongodb/test $MONGODB_ADVERTISED_HOSTNAME

if [[ "$*" = "/opt/bitnami/scripts/mongodb/run.sh" ]]; then
    info "** Starting MongoDB setup **"
    /opt/bitnami/scripts/mongodb/setup.sh
    info "** MongoDB setup finished! **"
fi
```
Interestingly, when pods are starting, the program never manages to resolve MONGODB_ADVERTISED_HOSTNAME, and always hits the 60 seconds timeout.

Once the replica set is initialized (more than 60 seconds later), I ``kubectl exec -it`` on mongodb containers and the program instantly & successfully returns the IP address of MONGODB_ADVERTISED_HOSTNAME:
```text
IPv4 address: 10.233.90.173 ((null))
IPv4 address: 10.233.90.173 ((null))
IPv4 address: 10.233.90.173 ((null))
```
When I delete all mongodb pods, the program hits the 60s timeout once again, and the MongoDB replica set does not work.

So I started wondering if the DNS resolution was only available when mongo db is considered as ready or something. So I removed ``livenessProbe`` and ``readinessProbe`` from the output of:
```bash
helm template -f myvalue.yaml mymongo bitnami/mongodb > mymongo_install.yaml
```
... then manually installed it, waited for it to be operational and deleted all pods :
```bash
kubectl create -f  mymongo_install.yaml
# wait for mongodb to be operational
kubectl delete pods mymongo-mongodb-arbiter-0 mymongo-mongodb-primary-0 mymongo-mongodb-secondary-0
```
During the restart of the pods the program manages to resolve MONGODB_ADVERTISED_HOSTNAME:
```text
[entrypoint] Checking getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.default")
error in getaddrinfo: Name or service not known
[8<] ... 20 times, so 10 seconds
error in getaddrinfo: Name or service not known
IPv4 address: 10.233.90.173 ((null))
IPv4 address: 10.233.90.173 ((null))
IPv4 address: 10.233.90.173 ((null))
** Starting MongoDB setup **
```
In the end MongoDB is happy, and the replica set is still operational!

**Comment by carrodher** [comment]
Hi, thanks for the detailed information, we are going to investigate this topic. We will update this thread with more information

**Comment by bfreuden** [comment]
Thank you very much Carlos.
Let me provide some additional details just in case.
The problem seems to be related to the ``readinessProbe`` probe (and not to the ``livenessProbe``).
I actually modified the ``rootfs/opt/bitnami/scripts/mongodb/entrypoint.sh`` in 2 ways:
* first display the content of /etc/hosts
* then run my little getaddrinfo program
```bash
print_welcome_page

etc_hosts=`cat /etc/hosts`
info "[entrypoint] /etc/host at startup"
info "$etc_hosts"

info "[entrypoint] Checking getaddrinfo(\"$MONGODB_ADVERTISED_HOSTNAME\")"
/opt/bitnami/scripts/mongodb/test $MONGODB_ADVERTISED_HOSTNAME

etc...
```

And here is the output of:
```bash
kubectl logs  mymongo-mongodb-primary-0 mongodb-primary
```
```text
mongodb 09:42:19.09 Welcome to the Bitnami mongodb container
mongodb 09:42:19.10 Subscribe to project updates by watching https://github.com/bitn
ami/bitnami-docker-mongodb
mongodb 09:42:19.10 Submit issues and feature requests at https://github.com/bitnami
/bitnami-docker-mongodb/issues
mongodb 09:42:19.10 
mongodb 09:42:19.11 INFO  ==> [entrypoint] /etc/host at startup
mongodb 09:42:19.11 INFO  ==> # Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.233.92.19	mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb.svc.cluster.local	mymongo-mongodb-primary-0
mongodb 09:42:19.11 INFO  ==> [entrypoint] Checking getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb")
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
error in getaddrinfo: Name or service not known
IPv4 address: 10.233.92.19 ((null))
IPv4 address: 10.233.92.19 ((null))
IPv4 address: 10.233.92.19 ((null))
mongodb 09:42:24.19 INFO  ==> ** Starting MongoDB setup **
``` 
It looks so strange to me (maybe out of ignorance) that the ``/etc/hosts`` is already containing the IP address but getaddrinfo fails to resolve it:
```text
10.233.92.19	mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb.svc.cluster.local	mymongo-mongodb-primary-0
```
Maybe that's because the line does not explicitely mention ``mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb`` (or something telling that ``svc.cluster.local`` is a domain name)?

**Comment by bfreuden** [comment]
I've made a last test: if I put the domain name at the end of the MONGODB_ADVERTISED_HOSTNAME variables in the manifest generated by the bitnami/mongodb Helm chart (stock image, without any tweak): 
```yaml
- name: MONGODB_ADVERTISED_HOSTNAME
  value: "$(MONGODB_POD_NAME).mymongo-mongodb-headless.default.svc.cluster.local"
```
Then the Mongo replica set is still operational after deleting the pods!
However I don't know if it is safe to do so (or if it is particular to my Kubernetes version).

**Comment by carrodher** [comment]
It is really weird, not sure if it can be related to a discrepancy in the k8s version between the client and the server:
```
Client Version: v1.18.0
Server Version: v1.17.5
```
as both versions are in different dev. branches sometimes we found issues related to that. As I am not able to reproduce the issue on my side, it occurred to me that the error could be related to that.

Can you upgrade the server or downgrade the client in order to have the same version (at least the same minor (`X` in `1.X.Y`)? Although not sure if you can do safely this test as you already have a working deployment with your workarounds.

**Comment by bfreuden** [comment]
Thank you Carlos. I will test a different version of the client and get back to you soon.
Upgrading my cluster to 1.18 will be more difficult but sounds interesting anyway. It is a staging cluster, no worries (I just need some time).

If you are not fed up already by that problem, I admit I would be curious to know if you activate the readiness probe and to know the content of the ``/etc/hosts`` of your MongoDB containers. Mine is only containing the fully qualified name of the headless service (not the advertised hostname):
```text
10.233.92.19	mymongo-mongodb-primary-0.mymongo-mongodb-headless.mongodb.svc.cluster.local	mymongo-mongodb-primary-0
```
The ``svc.cluster.local`` domain name is indeed part of the ``search`` entry of ``/etc/resolv.conf``, but I'm not sure is it supposed to be applied to the content of ``/etc/hosts`` (that would sound weird).

**Comment by carrodher** [comment]
Yes, of course, I can provide that info.

It seems the same configuration in my case, I don't think that is something differential in this case:
```
▶ kubectl exec mymongo-mongodb-primary-0 cat /etc/hosts
10.30.0.166	mymongo-mongodb-primary-0.mymongo-mongodb-headless.default.svc.cluster.local	mymongo-mongodb-primary-0

▶ kubectl exec mymongo-mongodb-primary-0 cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local c.bitnami-gke.internal google.internal
```

About the probes, yes, they are enabled by default and I didn't change it, I just used:
```yaml
 usePassword: true
 mongodbRootPassword: secret
 useStatefulSet: true
 ingress:
   enabled: true
 metrics:
   enabled: true
 replicaSet:
   enabled: true
   replicas:
     secondary: 1
```
```
▶ kubectl describe pod mymongo-mongodb-primary-0
...
    Liveness:   exec [pgrep mongod] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=5s timeout=5s period=10s #success=1 #failure=6
```

**Comment by bfreuden** [comment]
Thank you very much. No difference indeed. This is so strange... 
I'm sorry for being late in testing different client and server versions. I might have the time to do so during the week-end!

**Comment by bfreuden** [comment]
Hi Carlos,
I've just downgraded my kubectl to 1.17.5:
```bash
kubectl version --short
```
```text
Client Version: v1.17.5
Server Version: v1.17.5
```
At the beginning I've had high hopes: it was possible to kill the pods and the replica set was still operational. I did it twice, thrice. Working! Then I restarted my cluster and that was the end:
```json
{
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}
```
I tried to kill pods once again but not to avail.
I uninstalled my mongo release, reinstalled the chart but my luck was definitely gone: mongodb replicaset was no longer operational after killing pods.

Next step: upgrade my Kubernetes cluster to 1.18
I'll keep you posted.

**Comment by bfreuden** [comment]
Hi Carlos,
Sorry for the delay. I've finally updated my cluster (using kubespray).
Here is the new version:
```bash
kubectl version --short
```
```text
Client Version: v1.18.3
Server Version: v1.18.3
```
```bash
kubectl get nodes -o wide
```
```text
NAME    STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    master   44d   v1.18.3   192.168.1.12   <none>        Ubuntu 18.04.4 LTS   4.15.0-96-generic   docker://19.3.9
node2   Ready    master   44d   v1.18.3   192.168.1.14   <none>        Ubuntu 18.04.4 LTS   4.15.0-96-generic   docker://19.3.9
node3   Ready    <none>   44d   v1.18.3   192.168.1.25   <none>        Ubuntu 18.04.4 LTS   4.15.0-96-generic   docker://19.3.9
```
I removed my mongodb release and re-installed it from scratch but I'm afraid I still have the same kind of error when deleting my pods or restarting the cluster (excerpt of ``kubectl logs mymongo-mongodb-primary-0 mongodb-primary``) :
```text
2020-06-01T18:16:17.414+0000 W  NETWORK  [replexec-0] getaddrinfo("mymongo-mongodb-primary-0.mymongo-mongodb-headless.default") failed: Name or service not known
2020-06-01T18:16:17.461+0000 I  REPL     [replexec-0] This node is not a member of the config
```
And ``rs.status()`` in mongo shell gives:
```text
rs0:OTHER> rs.status()
{
	"ok" : 0,
	"errmsg" : "Our replica set config is invalid or we are not a member of it",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}
```
But, to be honest, this updated 1.18.3 cluster feels less responsive than the 1.17.5 I had before the update.

When I disable the readiness probe in the chart configuration file:
```yaml
usePassword: true
mongodbRootPassword: secret
useStatefulSet: true
metrics:
  enabled: true
replicaSet:
  enabled: true
  replicas:
    secondary: 1
readinessProbe:
  enabled: false # disabled
```
... it looks like I can kill my pods and keep an operational mongodb replica set (just did it 4 times in a row).
I'm puzzled.

**Comment by carrodher** [comment]
At the end, the readiness probe is running `mongo --eval db.adminCommand('ping')` to check when the cluster is up and running again:
```yaml
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
```
Apart from disabling it, that seems to be working, you can play with the `readinessProbe` values mentioned above to adjust the parameters, maybe it is a matter of increasing the timeout, the initial delay, etc

**Comment by bfreuden** [comment]
Thanks Carlos, 
You're right: I'll give it a try.

**Comment by bfreuden** [comment]
I've found an interesting page of the Kubernetes documentation about pods and DNS:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

That paragraph is ending with this note:

> Note: Because A or AAAA records are not created for Pod names, hostname is required for the Pod’s A or AAAA record to be created. A Pod with no hostname but with subdomain will only create the A or AAAA record for the headless service (default-subdomain.my-namespace.svc.cluster-domain.example), pointing to the Pod’s IP address. **Also, Pod needs to become ready in order to have a record unless publishNotReadyAddresses=True is set on the Service**.

That seems to shed some light on the impression I got 1 month ago in https://github.com/bitnami/bitnami-docker-mongodb/issues/211#issuecomment-626169487
> So I started wondering if the DNS resolution was only available when mongo db is considered as ready or something. 

So I've generated a manifest with ``helm template``, I've modified the headless service to include this ``publishNotReadyAddresses`` option (below is a fragment of the full manifest):
```yaml
# Source: mongodb/templates/svc-headless-rs.yaml
apiVersion: v1
kind: Service
metadata:
  name: mymongo-mongodb-headless
  namespace: mongodb
  labels:
    app: mongodb
    chart: mongodb-7.13.0
    release: "mymongo"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  # here it is: it will publish a DNS record before pods are ready
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb
    release: mymongo
```
And it's working with the readiness probe (not all the time though, see below).

To be honest, and if I understand the Kubernetes documentation correctly (but that's not sure), I don't get why it can work without that ``publishNotReadyAddresses: true`` parameter. 
It sounds like a chicken or the egg problem: mongod needs to resolve the advertised hostname to be ready (to know it is part of the replica set), but that hostname can only be resolved when mongod is ready.   

With the ``publishNotReadyAddresses: true`` it seems that it takes 5 seconds on my cluster before the hostname is resolvable inside the pod (no matter what: I played with various readiness parameters like you suggested, even disabled the readiness probe). Sometimes mongod is starting before (and the replica set is invalid), sometimes it is starting after (and the replica set is valid). 

Maybe I shall come up with a solution combining that parameter and the ``getent hosts <advertised hostname>`` command before mongod is started.

**Comment by carrodher** [comment]
Thanks for all the information, this thread is really interesting in terms of technical discussion. To be honest, I didn't face this issue in the scenarios we currently handle nor I remembered other similar issues, so it seems a very specific use case.

I would play with the time parameters, as it's supposed that the chart tries to look for functional status, but in some scenarios, it's not easy to adjust the initial delay, retries, etc. I am happy to see how far you go in your tests
