### ISSUE TITLE
/libmongodb.sh: line 221: /usr/local/bin/render-template: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by JoeLvBella** [bitnami/bitnami-docker-mongodb#212]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi @JoeLvBella,
  Could you provide some information on what you were testing and how to reproduce it?

Thanks forehand.

**Comment by JoeLvBella** [comment]
> Hi @JoeLvBella,
> Could you provide some information on what you were testing and how to reproduce it?
> 
> Thanks forehand.

i was Compiling the image of arm architecture.
when i run it，Start failed

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, currently our containers do not support ARM architecture. The only supported architecture is AMD64.

**Comment by JoeLvBella** [comment]
> Hi,
> I am sorry, currently our containers do not support ARM architecture. The only supported architecture is AMD64.

can you complile the image of arm architecture?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, currently this is not in our CI/CD and it is not in our roadmap.

Best regards.

**Comment by rafariossaa** [comment]
Is there is not more comments on this, I am closing the issue.
