### ISSUE TITLE
More than one database on init

### ISSUE THREAD

**Issue by zenbones** [bitnami/bitnami-docker-mongodb#217]
It would be great if mongodbDatabase allowed an [] of databases to create. I need more than one database, and than means creating and running an init container, and exposing the admin password to that container, just so it can create a second db before my main application container starts up (expecting access). I could avoid all of that it you would do me the service of being able to create more than one database on init.

**Comment by dani8art** [comment]
Hi @zenbones , I think you could do from the exact same container using [this](https://github.com/bitnami/bitnami-docker-mongodb#initializing-a-new-instance), you could create any database you want and configure them as you want. Could you give a try?

**Comment by zenbones** [comment]
I'm using the mongo helm chart, so I don't actually have a docker-compose.yml, nor do I want one. When we do create container images, it's via Packer and Ansible, which would  from work fine, and I can certainly create a mongo image exactly the way I want it. However, what I want to know is that our setup works for our customer base, and they'll be using the helm chart.

Is there a way to create a database and users via some set of entries in values.yaml, which the helm chart allows for one database, but not two? Is there a way to do it that can safely inject the passwords into the script from secrets?

**Comment by dani8art** [comment]
Using the chart there is two way of doing the same as with docker-compose, you could locate your files in `bitnami/mongodb/files/docker-entrypoint-initdb.d` and then execute:

```bash
$ helm install my-mongodb bitnami/mongodb/
```

Also, you can provide a config map with the scripts:

**my-init-script.yaml**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-create-databases
data:
  createdb.js: |-
     # My create db script JS
  createdb.sh: |-
    # My create db script sh
```

```bash
$ kubectl apply -f my-init-script.yaml
$ helm install my-mongodb bitnami/mongodb --set initConfigMap.name=script-create-databases
```

**Comment by dani8art** [comment]
Hi @zenbones , was it useful?

**Comment by zenbones** [comment]
Yes, that was useful, thank you. I would prefer that multiple databases be handled in the values in the same way as the original, but in absence of that, this is a way forward.

**Comment by dani8art** [comment]
That good! thank you so much for your feedback, if you have any other problem, do not hesitate to contact us, please.
