### ISSUE TITLE
MongoDB 4.4 support

### ISSUE THREAD

**Issue by mhemrg** [bitnami/bitnami-docker-mongodb#226]
Hi.
I could not find the 4.4 tag in DockerHub but README says that there's a 4.4 tag as well.

```
docker pull bitnami/mongodb:4.4
Error response from daemon: manifest for bitnami/mongodb:4.4 not found
```

**Comment by dani8art** [comment]
Hi @mhemrg, it seems there are some issues in our pipeline and some of our tests for mongodb container are failing with this new version. We will work on fixing them in the next 2-3 weeks

Thank you so much for opening the issue. We will keep you updated.

**Comment by andresbono** [comment]
Hi @mhemrg, the 4.4 tag is now available:

```
docker pull bitnami/mongodb:4.4
4.4: Pulling from bitnami/mongodb
```
