### ISSUE TITLE
How to solve "mkdir" permission denied problem?

### ISSUE THREAD

**Issue by blatoo** [bitnami/bitnami-docker-mongodb#233]
**Description**

`mkdir` permission denied, how can I make it possible? I can not even install the `sudo`...

It looks like, I can not do `mkdir xxx`, so how can I solve this problem? 

**Steps to reproduce the issue:**

1. [First Step]
I want to use the command "mongodump" to dump a database in terminal. 
`$ mongodump --db testdb`

**Describe the results you received:**
Error: `Failed: error dumping metadata: error creating directory for metadata file dump/memosnap_web: mkdir dump: permission denied`

**My docker image version**

Image version: 4.4.0-debian-10-r7
OS: debian-10

Thanks very much for the help!

Conny

**Comment by FraPazGal** [comment]
Hi @blatoo,

Thanks for reaching out! This is a non-root container so, once the image is built, you lose your root privileges. As you are trying to dump your databases, one option that avoids modifying the image is to mount a volume in the container and store your dump files in said directory with `mongodump -o /mounted/path/`. 

You can see an example of a mounted volume in the [Persisting your database](https://github.com/bitnami/bitnami-docker-mongodb#persisting-your-database) section of our README.
