### ISSUE TITLE
.mongorc.js not created in the new version of 4.2 image

### ISSUE THREAD

**Issue by mklokocka** [bitnami/bitnami-docker-mongodb#237]
Reopening issue #209 

An update broke the fix introduced in #223 as you can see here:

https://github.com/bitnami/bitnami-docker-mongodb/commit/7dfb7f23b7277a59369ede705b7f18b6ed395c49#diff-931a618a3b67d4e2f6bd4ddbca00363c0250139124e673138bd527b7b7a17e06

It just creates the same file twice in the loop.

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting, I will work on fixing it and release a new revision of the container.

**Comment by FraPazGal** [comment]
Hi @mklokocka,

Could you confirm that everything is working as expected? From what I can see, the update was reverted on [4.2.10-debian-10-r12 release](https://github.com/bitnami/bitnami-docker-mongodb/commit/049024595d2b58edbce5bebd2aaa9e7f64abcc56#diff-5e8a1b05b373352f3b6933db3bb34571e0726459453b0c3b92bd9042aa463dd5). Thanks in advance.

**Comment by mklokocka** [comment]
Looks OK on the r12 release. :)
