### ISSUE TITLE
Usernames/passwords with single-quotes cause silent user creation failure

### ISSUE THREAD

**Issue by TBBle** [bitnami/bitnami-docker-mongodb#241]
**Description**

Setting up the [MongoDB Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mongodb), I specified an `auth.rootPassword` of "Hampy's Super-secret MongoDB root password".

**Steps to reproduce the issue:**

1. Create a values.yaml:
```yaml
auth:
  rootPassword: "Hampy's Super-secret MongoDB root password"
useStatefulSet: true
```
2. `helm install mongodb bitnami/mongodb --values values.yaml --atomic`
3. Attempt to connect to the resulting mongodb with username `root` and password `Hampy's Super-secret MongoDB root password`, e.g. using `kubectl exec mongodb-0 -- bash` to get a shell in the container.

**Describe the results you received:**

Authentication failure

**Describe the results you expected:**

Authentication success
*or*
Container fails to start because `'` is invalid in a password, and hence reports a useful error at the end of the logs.

**Additional information you deem important (e.g. issue happens only occasionally):**

I logged into the container with `kubectl exec mongodb-0 -- bash` and confirmed that `MONGODB_ROOT_PASSWORD` env-var was correct, and included the single-quote.

This appears to be because [`mongodb_create_users`](https://github.com/bitnami/bitnami-docker-mongodb/blob/3ec33a5c130b10e9523e04b6a7a90fcbc09214a3/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L482-L503) does not sanitise its env-vars, and does not check the value of `result`, so if the user-creation fails, the script continues blindly.

Deleting the Helm chart and the StatefulSet's PVC, and reinstalling with `auth.rootPassword` set to "password" worked as expected.

**Version**

- Output of `docker version`: N/A, it was kubernetes.

- Output of `docker info`: N/A, it was kubernetes.

- Output of `docker-compose version` (if applicable): N/A, it was kubernetes.

- Chart version: `mongodb-10.1.2`

- Helm version:
```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is a kubernetes 1.15 bare-metal cluster.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. I will open a task for improving the password management inside the container. I cannot guarantee an ETA, but we will update the ticket as soon as we have more news.

**Comment by TBBle** [comment]
This is still a thing.

**Comment by javsalgar** [comment]
Added on-hold tag

**Comment by javsalgar** [comment]
Hi,

This has been problematic in several of our solutions. @GeorgeTsilias feel free to submit a PR with changes in the container. In the meantime, I will forward this to the engineering team to see if we can re-prioritize.

**Comment by GeorgeTsilias** [comment]
@TBBle Indeed the $result check could be implemented with the added benefit of being able to produce an error log if the user creation failed for whatever reason.
I'm not so sure about the sanitisation of the env-vars, could this somehow be done without altering the initial input value that the user provides?
@javsalgar I am currently looking into how this can be implemented.
[Bash documentation](http://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html) clearly states that: ' A single quote may not occur between single quotes, even when preceded by a backslash.'
I'm wondering if we could use awk to replace a single quote character ('), with (' " ' " ') as explained [here](https://stackoverflow.com/a/1250279/15214210)
Another idea is to use [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) for the `MONGODB_ROOT_PASSWORD` and `MONGODB_PASSWORD` variables on the script that Paul kindly linked in the previous message.
Not sure if that would work either, but I am going to give it a try once I manage to build & run an image.

**Comment by GeorgeTsilias** [comment]
I guess the simple solution of enclosing the `MONGODB_ROOT_PASSWORD` and `MONGODB_PASSWORD` is not considered viable, due to the variable expansion?

For example if the user specifies `MyName's$username` as a password,  the $username variable would be expanded to the actual username of the user on the target host.

I've verified that single quotes indeed work when the variables are double quoted, but again, I'm not sure whether this is an acceptable solution or not.

**Comment by javsalgar** [comment]
Hi, 

It seems to be that we would need to escape the dollar sign to avoid the expansion, applying a regex with sed for example. I don't see many examples in bash for that but maybe we could use the sanitize functions from other programming languages as a reference

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
