### ISSUE TITLE
You should not expose port 27017

### ISSUE THREAD

**Issue by ldeluigi** [bitnami/bitnami-docker-mongodb#242]
**Description**

Currently Dockerfile specification doesn't allow to override exposed ports.
There are many use cases where 27017 should not be exposed: private docker networks and not using the default port are two important examples.

**Describe the results you expected:**

I should be able to select what port to export in my dockerfile, without inheriting an exposed port from mongodb dockerfile.

**Solution**

Remove https://github.com/bitnami/bitnami-docker-mongodb/blob/16d50887548aba5e5bcbb8b634d67cd1351934d1/4.4/debian-10/Dockerfile#L27

**Version**
```
FROM bitnami/mongodb:4
```

**Comment by marcosbc** [comment]
Hi @ldeluigi, AFAIK when specifying `EXPOSE` it does not actually publish the port, and it would only be available inside the specific Docker network the container is running on.

This is what Docker's documentation says about the matter:

> The `EXPOSE` instruction informs Docker that the container listens on the specified network ports at runtime. You can specify whether the port listens on TCP or UDP, and the default is TCP if the protocol is not specified.
>
>The `EXPOSE` instruction **does not actually publish the port**. **It functions as a type of documentation between the person who builds the image and the person who runs the container**, about which ports are intended to be published. To actually publish the port when running the container, use the `-p` flag on `docker run` to publish and map one or more ports, or the `-P` flag to publish all exposed ports and map them to high-order ports.

https://docs.docker.com/engine/reference/builder/#expose

**Comment by ldeluigi** [comment]
Sorry, I can confirm now it was a misunderstanding. Have a nice day!
