### ISSUE TITLE
Recovering the snapshot data has been timed out  in shard cluster

### ISSUE THREAD

**Issue by tengzhuofei** [bitnami/bitnami-docker-mongodb#245]
bitnami/mongodb-sharded:4.4.1-debian-10-r60 

3 data shard node  all info the same

 08:18:04.05 INFO  ==> Setting node as primary
mongodb 08:18:04.07 
mongodb 08:18:04.07 Welcome to the Bitnami mongodb-sharded container
mongodb 08:18:04.07 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb 08:18:04.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb 08:18:04.07 
mongodb 08:18:04.07 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb 08:18:04.09 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 08:18:04.10 INFO  ==> Initializing MongoDB Sharded...
mongodb 08:18:04.15 INFO  ==> Writing keyfile for replica set authentication...
mongodb 08:18:04.16 INFO  ==> Enabling authentication...
mongodb 08:18:04.17 INFO  ==> Deploying MongoDB Sharded with persisted data...
mongodb 08:18:04.19 DEBUG ==> Waiting for primary node...
mongodb 08:18:04.19 INFO  ==> Trying to connect to MongoDB server mongodb-sharded...
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Could you provide more details in order to reproduce it? Is it a fresh installation or it had previous data? Which docker-compose.yaml file are you using?

**Comment by tengzhuofei** [comment]
I backed up the data by hard linking the data directory of the master node of the configuration and data pod and copying the files, and then there was a problem in restoring the data.

use chart https://github.com/bitnami/charts/tree/master/bitnami/mongodb-sharded

**Comment by tengzhuofei** [comment]
use docker-compose restore data is still error
mongodb-sharded_1         | mongodb 09:30:01.88 
mongodb-sharded_1         | mongodb 09:30:01.88 Welcome to the Bitnami mongodb-sharded container
mongodb-sharded_1         | mongodb 09:30:01.88 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb-sharded
mongodb-sharded_1         | mongodb 09:30:01.88 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb-sharded/issues
mongodb-sharded_1         | mongodb 09:30:01.88 
mongodb-sharded_1         | mongodb 09:30:01.89 INFO  ==> ** Starting MongoDB Sharded setup **
mongodb-sharded_1         | mongodb 09:30:01.91 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb-sharded_1         | mongodb 09:30:01.92 INFO  ==> Initializing Mongos...
mongodb-sharded_1         | mongodb 09:30:01.93 INFO  ==> Writing keyfile for replica set authentication...
mongodb-sharded_1         | mongodb 09:30:01.95 INFO  ==> Trying to connect to MongoDB server mongodb-cfg-primary...
mongodb-sharded_1         | mongodb 09:30:03.45 INFO  ==> Found MongoDB server listening at mongodb-cfg-primary:27017 !
mongodb-sharded_1         | mongodb 09:33:01.70 ERROR ==> Node mongodb-cfg-primary did not become available

**Comment by javsalgar** [comment]
What do you see in the mongo config nodes? Do they get initialized? Are you able to access using the credentials you previously set? Are you using the same replica set keys? That could partially explain the issue.

**Comment by javsalgar** [comment]
By accessing the config nodes I mean entering the container using docker exec and try to execute the mongo client with the proper credentials.

**Comment by tengzhuofei** [comment]
data node error

data-0

{"t":{"$date":"2021-01-22T08:11:04.216+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303064:216408][731:0x7fdee5882100], file:collection-8-2038549759726658328.wt, txn-recover: __wt_block_read_off, 283: collection-8-2038549759726658328.wt: read checksum error for 24576B block at offset 210300928: block header checksum of 0x3adde89f doesn't match expected checksum of 0xe85f29b2"}}
{"t":{"$date":"2021-01-22T08:11:04.216+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303064:216524][731:0x7fdee5882100], file:collection-8-2038549


data-1

{"t":{"$date":"2021-01-22T08:19:06.456+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":-31802,"message":"[1611303546:456150][317:0x7fbeca263100], file:WiredTigerHS.wt, hs_access: __posix_file_read, 429: /bitnami/mongodb/data/db/WiredTigerHS.wt: handle-read: pread: failed to read 4096 bytes at offset 36864: WT_ERROR: non-specific WiredTiger error"}}
{"t":{"$date":"2021-01-22T08:19:06.457+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":16,"message":"[1611303546:457280][317:0x7fbeca263100], txn-recover: __wt_txn_recover, 893: Recovery failed: Device or resource busy"}}
{"t":{"$date":"2021-01-22T08:19:06.458+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303546:458590][317:0x7fbeca263100], connection: __wt_cache_destroy, 369: cache server: exiting with 160 pages in memory and 124 pages evicted"}}
{"t":{"$date":"2021-01-22T08:19:06.458+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303546:458630][317:0x7fbeca263100], connection: __wt_cache_destroy, 374: cache server: exiting with 961464 image bytes in memory"}}
{"t":{"$date":"2021-01-22T08:19:06.458+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303546:458639][317:0x7fbeca263100], connection: __wt_cache_destroy, 377: cache server: exiting with 1216900 bytes in memory"}}
{"t":{"$date":"2021-01-22T08:19:06.458+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1611303546:458646][317:0x7fbeca263100], connection: __wt_cache_destroy, 383: cache server: exiting with 1208672 bytes dirty and 35 pages dirty"}}

**Comment by javsalgar** [comment]
Hi,

Do you have access to the previous working cluster? I don't have experience with doing backup and restore using hard links. How did you set the PVC in the new deployment of the chart?

**Comment by tengzhuofei** [comment]
the previous working cluster is ok，but I test the data restore in a time point， have error

**Comment by javsalgar** [comment]
Hi,

If the  previous cluster is running, are you able to execute the proper snapshot save commands in that previous cluster?

https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

```
etcdctl --endpoints $ENDPOINT snapshot save snapshotdb
```

**Comment by tengzhuofei** [comment]
etcd ?

**Comment by javsalgar** [comment]
Sorry, I answered the incorrect ticket (which also has an issue with snapshot recovery). Disregard that message.

**Comment by javsalgar** [comment]
But the idea also would apply for mongodb. Could you try with mongodb tools in your previous cluster? 

https://docs.mongodb.com/manual/tutorial/backup-and-restore-tools/

**Comment by tengzhuofei** [comment]
mongodump backup data is too slow

**Comment by javsalgar** [comment]
Hi,

Just for having an idea. How big is your data set? How long would mongodump take?
