### ISSUE TITLE
Custom user with different role

### ISSUE THREAD

**Issue by gau31rav** [bitnami/bitnami-docker-mongodb#253]
Hi,

We are using Bitnami Mongo Helm chart (replica set architecture), which in turns uses this Bitnami Mongo Image. We want to create a custom user to the Mongo Db.

As per current implementation the custom user, is created with readWrite role to specific database mentioned in env variable or values yaml of helm chart.

https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh (line 519)

In our scenario, we have multiple database created into single mongo instance and wanted to have the same user mappped to readWriteAnyDatabase role in Mongo.

Is it possible to modify the script to check if the database is specified then create the user with the role (configurable) in that database and if not by default it can readWriteAnyDatabase.

We will be more than happy to contribute.

**Comment by carrodher** [comment]
Hi, thanks for the suggestion. It should be possible, yes. I think the best approach is to create a new env. variable such as `MONGODB_USER_ROLE` and apply it to the mentioned script (take into account it should be applied to the different MongoDB versions present as subfolders in this repo):

```diff
-db.getSiblingDB('$MONGODB_DATABASE').createUser({ user: '$MONGODB_USERNAME', pwd: '$MONGODB_PASSWORD', roles: [{role: 'readWrite', db: '$MONGODB_DATABASE'}] })
+db.getSiblingDB('$MONGODB_DATABASE').createUser({ user: '$MONGODB_USERNAME', pwd: '$MONGODB_PASSWORD', roles: [{role: '$MONGODB_USER_ROLE', db: '$MONGODB_DATABASE'}] })
```

Then, in the Helm Chart, a new parameter in the `values.yaml` should be added to configure this env. variable in the container.

Please, take into account the above approach is just a suggestion, maybe you have a better idea, feel free to send both PRs (container & chart), we will be happy to review them

**Comment by gau31rav** [comment]
Thanks @carrodher for your comments. I am working on creating a PR for this, will submit once done.
