### ISSUE TITLE
Corrupted db

### ISSUE THREAD

**Issue by ghabarid** [bitnami/bitnami-docker-mongodb#257]
Our client is using a mongodb on our K8S. There db got corrupted. 
Is here any tools to repair the db?
The used image is  bitnami/mongodb:4.2
Thx.

**Comment by carrodher** [comment]
We don't provide this kind of tool nor can recommend any third-party software for that.
You can check the official MongoDB documentation just in case there is any official process/tool recommended for that, such as https://docs.mongodb.com/v3.6/reference/method/db.repairDatabase/, or create a ticket in a forum specialized in MongoDB itself.

From Bitnami we provide support for issues related to the container or Helm Charts, but in this case, seems an issue related to the application itself.
