### ISSUE TITLE
Initialisation fails to run (unbound variable error) on primary node for replicaset with TLS enabled via extra flags

### ISSUE THREAD

**Issue by thimster** [bitnami/bitnami-docker-mongodb#259]
**Description**

Hi.  We've recently upgraded to make use of this image (as well as upgraded version of the Helm chart we've been using to latest Bitnami one) to get us onto v4.4.5.  I've had problems however getting things running when enabling TLS which I think might be due to an issue with one of the script functions called upon initialisation; essentially root user creation is failing to run leading to an eventual restart with auth enabled but without a root user + password and subsequent failure of a replicaSet being able to be setup.

**Steps to reproduce the issue:**

1. Enable TLS extra flags:
    `$MONGODB_EXTRA_FLAGS=--tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert`
2.  Enable TLS client extra flags:
    `$MONGODB_CLIENT_EXTRA_FLAGS=--tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert`
3.  Set replicaset mode:
    `MONGODB_REPLICA_SET_MODE=primary`
4.  Set relevant advertised hostname
5.  Run the image

**Describe the results you received:**

MongoDB container hangs until execution timeout, restarts and then unable to connect with root user + password and replicaset does not establish.

**Describe the results you expected:**

MongoDB initialisation runs successfully, creates root user with password and replicaset creates correctly with MongoDB running with TLS.

**Additional information you deem important (e.g. issue happens only occasionally):**

From my investigation it looks like the issue boils down to the TLS extra args passed to MongoDB startup and these extra args are possibly not being handled correctly; though it could be the way they're being passed in (being handled as an array even though they're a string).

The issue appears to lie at line 145 of https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh:

```bash
        [[ "${#extra_args[@]}" -gt 0 ]] && args+=("${extra_args_array[@]}")
```

When I modify the image to output some further info, I can see that this is in fact throwing an `unbound variable` error for `extra_args` which appears to be due to `extra_args` being treated as an array, which it's not at this point (it's a string):

```bash
        [[ "${#extra_args}" -gt 0 ]] && args+=("${extra_args_array[@]}")
```

I'm happy to raise a PR with changes that are working for me but thought I'd raise this first in case I'm missing something.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:14:53 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Also happening on our OpenShift cluster.

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 50.06GiB
 Name: docker-desktop
 ID: 3LPB:5KYP:3P76:HTRT:5THI:7ASX:TEJF:7ID3:T5AD:P5F4:XD7E:BFPO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Our main platform is OpenShift 4.6 but have replicated on other runtimes.

**Comment by alvneiayu** [comment]
hi @thimster 

Other user has reported an issue that I think that seems similar and we have already added a PR:

https://github.com/bitnami/charts/issues/5698

Could you take a look if your problem is the same, please?

Thanks a lot and I will be looking forward for your reply.

Álvaro

**Comment by thimster** [comment]
Hi @alvneiayu !


Thanks very much for your reply and the link.  We do already have that code running from the PR so unfortunately it doesn't address our issue, though is related.  I'm not sure if I'm missing something that would trigger type conversion in that Bash code for the string into an array, but certainly changing it to get string size with `${#extra_args)` works for us.


Kind regards

 - Tim.

**Comment by alvneiayu** [comment]
hi @thimster 

I am trying to reproduce the issue but I can not. I installed the mongodb chart using those values:
```
architecture: replicaset

extraEnvVars:
  - name: MONGODB_REPLICA_SET_MODE
    value: primary
```

the chart set up by itself all the extra variables:

```
      MONGODB_EXTRA_FLAGS:              --tlsMode=requireTLS --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert 
      MONGODB_CLIENT_EXTRA_FLAGS:       --tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert

```
The chart is running without any problem. Your solution and the actual solution will return a number bigger than 0 and the extra values will be used as arguments. Could you share with me your docker compose (in case that you are using Dockers) or the k8s manifest (in case that you are using kubernetes), please?. To try to reproduce your problem

If you want, share me also your solution, I think that your solution will be really helpful to understand the problem that you are having. Are you changing all the variables to use the number of characters?

Thanks again for your time and I will be looking forward for your reply.

Álvaro

**Comment by thimster** [comment]
Thanks @alvneiayu - apologies for the slow reply.  I'm trying a couple of additional things and will then send through some extra details.  I think though I should be able to send through a solution that checks whether it's an array or string and uses the correct test.

Kind regards and thanks again for your help

 - Tim.

**Comment by alvneiayu** [comment]
hi @thimster 

Perfect, thanks for your time and let me know if I can help you with something.

Álvaro

**Comment by wgtmpeters** [comment]
@thimster  any progress or way for you to provide at least the PR changes needed to fix this? We are also running into this at the moment.
Thanks in advance!

**Comment by thimster** [comment]
Hi @wgtmpeters 

The fix that's worked for us is the following change to `rootfs/opt/bitnami/scripts/libmongodb.sh` line 145 to:

```bash
        [[ "${#extra_args}" -gt 0 ]] && args+=("${extra_args_array[@]}")
```

Still working to wrap it in a suitable test to check if it's an array or not so it doesn't change existing functionality when appropriate, and only use the above if it's not an array; hoping to provide further details soon and to get an appropriate PR up soon.


Kind regards

 - Tim.

**Comment by brambooo** [comment]
Any progress on this @thimster? We are also looking for a solution to fix this.

**Comment by thimster** [comment]
Hi @brambooo 

We've been super busy with a few things so apologies on the delay - but hopefully I should have some time over the next day or two to raise a PR for this

Regards

 - Tim.

**Comment by brambooo** [comment]
Thanks @thimster really appreciate it, keep us informed :)

**Comment by brambooo** [comment]
When do you think you have time to have a look at it @thimster? We run out of time and need a solution. Sorry for bordering!

**Comment by alvneiayu** [comment]
hi @brambooo 

Did you test the workaround shared by @thimster? [here](https://github.com/bitnami/bitnami-docker-mongodb/issues/259#issuecomment-827539919)

Maybe it can help you to fix the problem temporarily until we have the final solution.

Thanks a lot for your patience

Álvaro

**Comment by thimster** [comment]
Hi

Apologies for missing a few messages and the delay in this (have had a few other priorities).  It took a little while trying to figure out a suitable array test; and then I realised I could probably just test the already-typecast other var.  Hopefully this works with other configurations (I have tested at my end) and is hopefully useful for others.

 - Tim.

**Comment by thimster** [comment]
Sorted for us with the accepted pull request, thanks!
