### ISSUE TITLE
mkdir: cannot create directory '/bitnami/mongodb/data': Operation not permitted

### ISSUE THREAD

**Issue by MebinAbraham** [bitnami/bitnami-docker-mongodb#271]
**Description**
Unable to set up volume to persist the database as per the README https://github.com/bitnami/bitnami-docker-mongodb#persisting-your-database

**Steps to reproduce the issue:**

1. Running a basic mongodb docker compose set up
    ```
    version: '3.8'

    services:
      mongodb:
        image: "bitnami/mongodb:4.4"
        restart: always
        ports:
          - 27017:27017
        volumes:
          - $HOME/data/mongo:/bitnami/mongodb
      ```
2. Chown the volume as per README `sudo chown -R 1001 $HOME/data/mongo`. Before this, the error would be `Permission denied`
3. Run `docker compose up`

**Describe the results you received:**
The container exited due to "Operation not permitted"

```
mongodb_1  | mongodb 21:44:19.87 INFO  ==> ** Starting MongoDB setup **
mongodb_1  | mongodb 21:44:19.88 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb_1  | mkdir: cannot create directory '/bitnami/mongodb/data': Operation not permitted
mongodb_1 exited with code 1
```
**Describe the results you expected:**
Container starts up as expected with persistent volume attached.

**Additional information you deem important (e.g. issue happens only occasionally):**

Already tried: https://github.com/bitnami/bitnami-docker-mongodb/issues/177#issuecomment-544900186
Have also tried the following suggestion but had no luck: https://github.com/bitnami/bitnami-docker-mongodb/issues/206#issuecomment-617589288

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.94GiB
 Name: docker-desktop
 ID: ASZW:5CPV:LI3Y:EU4B:II3T:WLWL:K72D:RKSJ:3OR2:E3NC:53WC:6I23
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @MebinAbraham ,
I tried to reproduce the issue with no luck. After changing the permissions it works in my case.
Please be sure the permissions of `$HOME/data/mongo` are correct.

**Comment by MebinAbraham** [comment]
> Hi @MebinAbraham ,
> I tried to reproduce the issue with no luck. After changing the permissions it works in my case.
> Please be sure the permissions of `$HOME/data/mongo` are correct.

Thanks for the quick reply, unfortunately, I still have the issue. The owner is set to `1001` and I have also adjusted permissions via `chmod` to ensure it has both read and write access. I cannot seem to get past the permission issue, which it indeed is but not sure what I have not done that potentially needs doing.

**Comment by MebinAbraham** [comment]
Closing as I have managed to get it working, some conflict in permissions but I am not able to recreate this behaviour even if I create a new dir and not `chown`ing to user `1001`, so not sure what's up with that.
