### ISSUE TITLE
MongoDB log with file instead of /dev/stdout

### ISSUE THREAD

**Issue by whelan9453** [bitnami/bitnami-docker-mongodb#273]
**Description**

**Steps to reproduce the issue:**

1. Deploy MongoDB shard helm chart
2. Check MongoDB file 
3. log file is pointing to /dev/stdout

```
$ ls -al /opt/bitnami/mongodb/logs/mongodb.log 
lrwxrwxrwx 1 root root 11 Jun 20 06:57 /opt/bitnami/mongodb/logs/mongodb.log -> /dev/stdout
```

**Describe the results you expected:**

MongoDB log file should have an option to write as a file

- Output of `docker version`:

```
docker.io/bitnami/mongodb-sharded:4.4.6-debian-10-r36
```

I found this old issue https://github.com/bitnami/bitnami-docker-mongodb/issues/131 and the suggestion was to change the build script & build a customized image. 

Is it still the case? 
If so, please suggest where to edit for the current version?
(https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb/setup.sh here?)

**Comment by Mauraza** [comment]
Hi @whelan9453,

Yes is still the case, you need to change the line below and build a new container.
https://github.com/bitnami/bitnami-docker-mongodb/blob/232b510330be9c29f8a75a661e592dd8dc77b9ba/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb/postunpack.sh#L31-L32

**Comment by whelan9453** [comment]
> Hi @whelan9453,
> 
> Yes is still the case, you need to change the line below and build a new container.
> https://github.com/bitnami/bitnami-docker-mongodb/blob/232b510330be9c29f8a75a661e592dd8dc77b9ba/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb/postunpack.sh#L31-L32

thanks will find some time to try this ASAP
