### ISSUE TITLE
After the restart, mongodb-secondary keeps restarting

### ISSUE THREAD

**Issue by liwh1111** [bitnami/bitnami-docker-mongodb#277]
![image](https://user-images.githubusercontent.com/63097736/127444633-fe9723f3-73a8-4095-8b89-0f11ca04eaa4.png)
version
![image](https://user-images.githubusercontent.com/63097736/127444951-007729c4-73fc-43df-9180-bcaed98ee4a3.png)

**Comment by migruiz4** [comment]
Hi @liwh1111,

Could you please share some additional information about your issue? Especially, under what circumstances did this issue happen?

It would be helpful if you could open a terminal inside the primary node and run the following command using the mongo client:
```
kubectl exec -it mongodb-primary-0 -- bash
#Inside the container
mongo --host 127.0.0.1 --authenticationDatabase admin -u root -p <your_root_password>
#Inside the mongo shell
> rs.isMaster()
```

The command `isMaster()` will return information about the Replicaset, including the hosts that are part of it under the field `hosts`.
Ref: https://docs.mongodb.com/v4.0/reference/command/isMaster/#dbcmd.isMaster

Using that command, I expect to see if your `mongodb-secondary-0` is still part of the replicaset or not.

**Comment by liwh1111** [comment]
This happens after I restart the Mongo cluster, the secondary node cannot be readded to the cluster
rs.isMaster
![image](https://user-images.githubusercontent.com/63097736/127594691-5f255a45-c3ee-40fb-9f82-5cf014650ef4.png)

rs.status()
![image](https://user-images.githubusercontent.com/63097736/127594755-9363c867-a421-490a-bb16-be2719e52f77.png)

Where is the command for secondary node to join the cluster?

**Comment by pablogalegoc** [comment]
Hi @liwh1111,

> Where is the command for secondary node to join the cluster?

You can find here a guide to [add members to a replicaset](https://docs.mongodb.com/manual/tutorial/expand-replica-set/)
