### ISSUE TITLE
new signing keys not generated by the monitoring-keys-for-HMAC thread

### ISSUE THREAD

**Issue by tengzhuofei** [bitnami/bitnami-docker-mongodb#279]
4.4.3 and later imaging fixes the bug and Is the image synchronized with the latest？

**Comment by tengzhuofei** [comment]
https://jira.mongodb.org/browse/SERVER-52654

**Comment by marcosbc** [comment]
Hi @tengzhuofei, this issue is fixed in 4.4.3, so if you are using 4.4.1 you would need to upgrade your deployment.

Note that we already offer up to MongoDB 4.4.8 for sharded architecture: https://github.com/bitnami/bitnami-docker-mongodb-sharded
