### ISSUE TITLE
How about if I want to use auth  multiple  database  ? 

### ISSUE THREAD

**Issue by ZhuoSiChen** [bitnami/bitnami-docker-mongodb#283]
**Describe the results you expected:**
I want to  when mongodb is ready, execute my .js to create database and auth user to access the database。

**Comment by juan131** [comment]
Hi @ZhuoSiChen 

Please let's continue the conversation in [this issue](https://github.com/bitnami/charts/issues/7254) you opened in the Bitnami Charts repository.
