### ISSUE TITLE
Mongo 5.02? 

### ISSUE THREAD

**Issue by MoLow** [bitnami/bitnami-docker-mongodb#287]
Hi!
this repo is really appreciated! Just curious to know if there are plans to build/support an image of mongo 5, or should I use the official mongo docker image? (that lacks support of some features such as replication etc)

thanks

**Comment by alemorcuq** [comment]
Hi, @MoLow. Yes! We are currently working on releasing MongoDB 5. I will ping you when the release is done.

**Comment by carrodher** [comment]
Hi, we just released MongoDB 5.0 (see https://github.com/bitnami/bitnami-docker-mongodb/commit/bd0bf42ec26d3967dd38a83f6d63d06812e97920), you can find the code in this repository and the container images in the different registries, see [here](https://github.com/bitnami/bitnami-docker-mongodb#supported-tags-and-respective-dockerfile-links) the supported tags.
