### ISSUE TITLE
Bitnami: EKS : :4.2.17-debian-10-r6 : Errors

### ISSUE THREAD

**Issue by tropicallydiv** [bitnami/bitnami-docker-mongodb#295]
Hi
We are trying to create a bitnami mongodb database on EKS Cluster.
We are running into several issues as explained below:

1) Our Docker File: (

```yaml
FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6
USER 0
RUN whoami
USER 1001
```
Yaml file  contents 
```yaml
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: datadir
```
Logs:  
```bash
kubectl logs mong4-mongodb-0
mongodb 15:36:05.28
mongodb 15:36:05.28 Welcome to the Bitnami mongodb container
mongodb 15:36:05.28 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 15:36:05.28 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 15:36:05.28
mongodb 15:36:05.28 INFO  ==> ** Starting MongoDB setup **
mongodb 15:36:05.30 INFO  ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied   <<<<<<<<<<<<<<<<<<<<<<<
```
 cat Dockerfile
```yaml
FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6
```

2)   cat Dockerfile
```yaml
FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6

USER 0

RUN whoami
RUN mkdir -p /bitnami/mongodb/data
RUN chown -R 1001:1001 /bitnami/mongodb
RUN chmod -R 777  /bitnami/mongodb
RUN ls -l /bitnami/mongodb

USER 1001
```

Yaml file  contents 
```yaml
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: datadir
```

```bash
$ sudo docker build -t mongo3-6:v2 .
Sending build context to Docker daemon  354.7MB
Step 1/8 : FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6
 ---> 35e7babeb58b
Step 2/8 : USER 0
 ---> Using cache
 ---> a9172384388c
Step 3/8 : RUN whoami
 ---> Using cache
 ---> b32551a11e0d
Step 4/8 : RUN mkdir -p /bitnami/mongodb/data
 ---> Running in 44dc23200cbd
Removing intermediate container 44dc23200cbd
 ---> b2a9685bb884
Step 5/8 : RUN chown -R 1001:1001 /bitnami/mongodb
 ---> Running in 74fcd66abb14
Removing intermediate container 74fcd66abb14
 ---> 0b4508f9f7ed
Step 6/8 : RUN chmod -R 777  /bitnami/mongodb
 ---> Running in 6897aed34230
Removing intermediate container 6897aed34230
 ---> 7005a914260d
Step 7/8 : RUN ls -l /bitnami/mongodb
 ---> Running in 173b9856def2
total 0
drwxrwxrwx. 1 1001 1001 6 Sep 29 03:51 data
Removing intermediate container 173b9856def2
 ---> c3ddda9863d8
Step 8/8 : USER 1001
 ---> Running in c7367fb4ce70
Removing intermediate container c7367fb4ce70
 ---> 7da875fc71ae
Successfully built 7da875fc71ae
Successfully tagged mongo3-6:v2
```
on execution: 
```bash
Errors: 
ubectl logs mong4-mongodb-0
mongodb 15:45:50.34
mongodb 15:45:50.34 Welcome to the Bitnami mongodb container
mongodb 15:45:50.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 15:45:50.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 15:45:50.35
mongodb 15:45:50.35 INFO  ==> ** Starting MongoDB setup **
mongodb 15:45:50.37 INFO  ==> Validating settings in MONGODB_* env vars...
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied   <<<<<<<<<<<<<<<<<<<<<<<
```

3)  Docker file Contents 

```yaml
FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6

USER 0

RUN whoami
RUN mkdir -p /tmp/mongodb/data
RUN chown -R 1001:1001 /tmp/mongodb
RUN chmod -R 777  /tmp/mongodb

USER 1001
```
Yaml file  contents 
```yaml
        volumeMounts:
        - mountPath: /tmp/mongodb
          name: datadir
```

```bash
$ sudo docker build -t mongo3-6:v2 .
Sending build context to Docker daemon  354.7MB
Step 1/7 : FROM docker.io/bitnami/mongodb:4.2.17-debian-10-r6
 ---> 35e7babeb58b
Step 2/7 : USER 0
 ---> Using cache
 ---> a9172384388c
Step 3/7 : RUN whoami
 ---> Using cache
 ---> b32551a11e0d
Step 4/7 : RUN mkdir -p /tmp/mongodb/data
 ---> Running in bd00b2302de8
Removing intermediate container bd00b2302de8
 ---> 161949bfea86
Step 5/7 : RUN chown -R 1001:1001 /tmp/mongodb
 ---> Running in 160afe36ceb6
Removing intermediate container 160afe36ceb6
 ---> d36522a77286
Step 6/7 : RUN chmod -R 777  /tmp/mongodb
 ---> Running in c64bb065b1cc
Removing intermediate container c64bb065b1cc
 ---> dff990c93eac
Step 7/7 : USER 1001
 ---> Running in d5fe2a781643
Removing intermediate container d5fe2a781643
 ---> 5716cf57c93a
Successfully built 5716cf57c93a
Successfully tagged mongo3-6:v2
```

```bash
$ kubectl logs mong4-mongodb-0
mongodb 15:58:22.26
mongodb 15:58:22.26 Welcome to the Bitnami mongodb container
mongodb 15:58:22.26 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 15:58:22.26 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 15:58:22.26
mongodb 15:58:22.26 INFO  ==> ** Starting MongoDB setup **
mongodb 15:58:22.28 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 15:58:22.30 INFO  ==> Initializing MongoDB...
mongodb 15:58:22.31 INFO  ==> Deploying MongoDB from scratch...
mongodb 15:58:23.15 INFO  ==> Creating users...
mongodb 15:58:23.15 INFO  ==> Creating root user...   
exception: connect failed                                                                   <<<<<<<<<<<<<<<<<<<<<<<
mongodb 15:58:23.20 INFO  ==> Stopping MongoDB... 
```

Any help would be appreciated. 
TIA

**Comment by tropicallydiv** [comment]
First one we figured out:
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied <<<<<<<<<<<<<<<<<<<<<<<

This was because docker is configured with uid 1001.

Trying to figure out the second one.

**Comment by tropicallydiv** [comment]
SO the problem is  the flag 
 name: MONGODB_EXTRA_FLAGS
          value: --sslMode=requireSSL --sslPEMKeyFile=/certs/mongodb.pem

If I remove this then the pod gets created. 
When the pod does get create the folder and the file are there.

**Comment by Mauraza** [comment]
Hi @tropicallydiv,

The error with the permission meaning you are missing some configuration in the yaml, It's not related with the container. If you can share the deploy yaml maybe we can see here is the issue. We have a chart of mongodb maybe that could help https://github.com/bitnami/charts/tree/master/bitnami/mongodb 

About the MONGODB_EXTRA_FLAGS, could you add the variable `BITNAMI_DEBUG=true`?

**Comment by tropicallydiv** [comment]
Docker is installed as   uid=1001(docker) gid=1001(docker) groups=1001(docker)
Does that have any impact?

**Comment by Mauraza** [comment]
Hi @tropicallydiv,

In my case appears:
```logs
{"t":{"$date":"2021-10-01T08:59:50.906Z"},"s":"W",  "c":"CONTROL",  "id":23322,   "ctx":"main","msg":"Option: sslMode is deprecated. Please use tlsMode instead."}
{"t":{"$date":"2021-10-01T08:59:50.906Z"},"s":"W",  "c":"CONTROL",  "id":23321,   "ctx":"main","msg":"Option: This name is deprecated. Please use the preferred name instead.","attr":{"deprecatedName":"sslPEMKeyFile","preferredName":"tlsCertificateKeyFile"}}
```
Could you try something like this:
```yaml
           - name: MONGODB_CLIENT_EXTRA_FLAGS
              value: --tls --tlsCertificateKeyFile=/certs/mongodb.pem --tlsCAFile=/certs/mongodb-ca-cert
```

**Comment by tropicallydiv** [comment]
Can you try with version 3.6. using SSL

apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mongo36
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo36
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.16.0
  name: mongo36-mongodb
spec:
  ports:
  - name: mongodb
    port: 27020
    protocol: TCP
    targetPort: mongodb
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo36
    app.kubernetes.io/name: mongodb
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
data:
  ca.tco.census.gov.crt: <cert1> 
kind: Secret
metadata:
  name: mongodb-certs
type: Opaque
---
apiVersion: v1
data:
  mongodb-password: <pwd1> 
  mongodb-root-password: <pwd2> 
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: mongo36
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo36
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.16.0
  name: mongo36-mongodb
type: Opaque
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: mongo36
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongo36
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.16.0
  name: mongo36-mongodb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongo36
      app.kubernetes.io/name: mongodb
  serviceName: mongo36-mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: mongodb
        app.kubernetes.io/instance: mongo36
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mongodb
        helm.sh/chart: mongodb-10.16.0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: mongodb
                  app.kubernetes.io/instance: mongo36
                  app.kubernetes.io/name: mongodb
              namespaces:
              - adsd-cumulus-dev-db
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MONGODB_USERNAME
          value: mft
        - name: MONGODB_DATABASE
          value: mft-dev
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-password
              name: mongo36-mongodb
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongo36-mongodb
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DISABLE_JAVASCRIPT
          value: "no"
        - name: MONGODB_ENABLE_JOURNAL
          value: "yes"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        - name: MONGODB_EXTRA_FLAGS
          value: --sslMode=requireSSL --sslPEMKeyFile=/certs/mongodb.pem
        image: docker.io/bitnami/mongodb:3.6.23-debian-9-r48
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: datadir
        - mountPath: /certs
          name: certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: scdf-sa
      serviceAccountName: scdf-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: mongodb-certs
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi

**Comment by Mauraza** [comment]
Hi @tropicallydiv,

I was not able to reproduce it. Could you change the value of `BITNAMI_DEBUG=true`
```yaml
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: "true"
```
And see if in the logs appears something more.

**Comment by tropicallydiv** [comment]
Added debug=true and no extra logs

Changed
- name: MONGODB_EXTRA_FLAGS
          value: --sslMode=requireSSL --sslPEMKeyFile=/certs/mongodb.pem

to
- name: MONGODB_EXTRA_FLAGS
          value: "--sslMode=requireSSL --sslPEMKeyFile=/certs/mongodb.pem" 

Based on :  https://github.com/helm/charts/issues/17472
and still problem  exists.

**Comment by tropicallydiv** [comment]
kubectl logs mongo36-mongodb-0
mongodb 19:38:38.16
mongodb 19:38:38.17 Welcome to the Bitnami mongodb container
mongodb 19:38:38.17 Subscribe to project updates by watching https://github.com                                 /bitnami/bitnami-docker-mongodb
mongodb 19:38:38.17 Submit issues and feature requests at https://github.com/bi                                 tnami/bitnami-docker-mongodb/issues
mongodb 19:38:38.17
mongodb 19:38:38.17 INFO  ==> ** Starting MongoDB setup **
mongodb 19:38:38.21 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 19:38:38.23 INFO  ==> Initializing MongoDB...
mongodb 19:38:38.26 INFO  ==> Deploying MongoDB from scratch...
mongodb 19:38:38.27 DEBUG ==> Starting MongoDB in background...
about to fork child process, waiting until server is ready for connections.
forked process: 42
child process started successfully, parent exiting
mongodb 19:38:39.03 INFO  ==> Creating users...
mongodb 19:38:39.03 INFO  ==> Creating root user...
exception: connect failed
mongodb 19:38:39.08 INFO  ==> Stopping MongoDB...
[ec2-user@cat-test0151-m ~]$ kubectl describe pod  mongo36-mongodb-0
Name:         mongo36-mongodb-0
Namespace:    dev
Priority:     0
Node:         ip-10-194-25-226.ec2.internal/10.194.25.226
Start Time:   Mon, 04 Oct 2021 15:38:12 -0400
Labels:       app.kubernetes.io/component=mongodb
              app.kubernetes.io/instance=mongo36
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=mongodb
              controller-revision-hash=mongo36-mongodb-748849b574
              helm.sh/chart=mongodb-10.16.0
              statefulset.kubernetes.io/pod-name=mongo36-mongodb-0
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.194.25.27
IPs:
  IP:           10.194.25.27
Controlled By:  StatefulSet/mongo36-mongodb
Containers:
  mongodb:
    Container ID:   docker://758d6e1234c81e32e66eeb5d73a1f6807cd70863a39985d112                                 80b44bb1250d27
    Image:          dkr.ecr.us-east-1.amazonaws.com/eks/databases/bitnami/mongo:v12
    Image ID:       <image id > 
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 04 Oct 2021 15:39:10 -0400
      Finished:     Mon, 04 Oct 2021 15:39:12 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 04 Oct 2021 15:38:38 -0400
      Finished:     Mon, 04 Oct 2021 15:38:40 -0400
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:     1
      memory:  1Gi
    Environment:
      BITNAMI_DEBUG:                    true
      BITNAMI_LOG_LEVEL:                trace8
      MONGODB_USERNAME:                 mft
      MONGODB_DATABASE:                 mft-dev
      MONGODB_PASSWORD:                 <set to the key 'mongodb-password' in secret 'mongo36-mongodb'>       Optional: false
      MONGODB_ROOT_PASSWORD:            <set to the key 'mongodb-root-password' in secret 'mongo36-mongodb'>  Optional: false
      MONGODB_SYSTEM_LOG_VERBOSITY:     0
      MONGODB_DISABLE_SYSTEM_LOG:       no
      MONGODB_DISABLE_JAVASCRIPT:       no
      MONGODB_ENABLE_JOURNAL:           yes
      MONGODB_ENABLE_IPV6:              no
      MONGODB_ENABLE_DIRECTORY_PER_DB:  no
      ALLOW_EMPTY_PASSWORD:             no
      MONGODB_EXTRA_FLAGS:              --sslMode=requireSSL --sslPEMKeyFile=/certs/mongodb.pem
    Mounts:
      /certs from certs (ro)
      /tmp/mongodb from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from scdf-sa-token-pjjxk (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-mongo36-mongodb-0
    ReadOnly:   false
  certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-certs
    Optional:    false
  scdf-sa-token-pjjxk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  scdf-sa-token-pjjxk
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age               From                     M                                 essage
  ----     ------                  ----              ----                     -                                 ------
  Normal   Scheduled               65s               default-scheduler        Successfully assigned dev/mongo36-mongodb-0 to ip-10-194-25-226.ec2.internal
  Normal   SuccessfulAttachVolume  62s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-35653c05-2d67-409d-8306-3313fac23941"
  Normal   Pulling                 58s               kubelet                  Pulling image "dkr.ecr.us-east-1.amazonaws.com/eks/databases/bitnami/mongo:v12"
  Normal   Pulled                  58s               kubelet                  Successfully pulled image "dkr.ecr.us-east-1.amazonaws.com/eks/databases/bitnami/mongo:v12" in 225.472128ms
  Normal   Pulled                  8s (x3 over 55s)  kubelet                  Container image "dkr.ecr.us-east-1.amazonaws.com/eks/databases/bitnami/mongo:v12" already present on machine
  Normal   Created                 7s (x4 over 58s)  kubelet                  Created container mongodb
  Normal   Started                 7s (x4 over 58s)  kubelet                  Sarted container mongodb
  Warning  BackOff                 5s (x4 over 52s)  kubelet                  Back-off restarting failed container

**Comment by Mauraza** [comment]
Hi @tropicallydiv,

The YAML you share appears the namespace only in the deployment. Could you check that you have the names in the rest of the objects?

**Comment by tropicallydiv** [comment]
I removed the reference to namespace to let everything use the default namespace that we are in.
Still same issue.

**Comment by Mauraza** [comment]
Hi @tropicallydiv,

Could you check that when you deploy MongoDB there is no PVC from the previous installation?
