### ISSUE TITLE
MongoDB don't start on ipv6 k8s cluster

### ISSUE THREAD

**Issue by david9969** [bitnami/bitnami-docker-mongodb#300]
**Description**

MongoDB pods are not working properly when enabling ipv6 and it's pointing to ipv4 (127.0.0.1) instead of ipv6

**Steps to reproduce the issue:**

1. enableIPV6 set to true
2. try to deploy helm chart
3. see the logs of mongodb pods don't became 1/1 running

**Describe the results you received:**
```console
$ mongo --eval 'db.hello().isWritablePrimary || db.hello().secondary'
MongoDB shell version v4.4.10
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("0d17a75e-aaee-429e-b486-82fe18e26436") }
MongoDB server version: 4.4.10
false
```
 
**Describe the results you expected:**

Instead of connecting on ipv4 ip 127.0.0.1 we shall see an IPV6 connection. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Always

**Comment by carrodher** [comment]
Hi, according to https://docs.mongodb.com/manual/core/security-mongodb-configuration/  there are a couple of parameters that should be added to the config file to configure MongoDB to work with IPv6: `net.ipv6` and `net.bindIpAll`. Can you check if those parameters are set in your config file (_/opt/bitnami/mongodb/conf/mongodb.conf_)?

I just deployed the chart and checked the config file and everything seems to be properly set:
```console
$ helm install mongo bitnami/mongodb -n mongo --create-namespace --set enableIPv6=true
$ kubectl get pods -n mongo
NAME                            READY   STATUS    RESTARTS   AGE
mongo-mongodb-cf6dbd995-vjt8t   1/1     Running   0          18h
$ kubectl exec -it mongo-mongodb-cf6dbd995-vjt8t -n mongo -- cat /opt/bitnami/mongodb/conf/mongodb.conf
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  ipv6: true
  bindIpAll: true
  #bindIp:

# replica set options
#replication:
  #replSetName: replicaset
  #enableMajorityReadConcern: true

# sharding options
#sharding:
  #clusterRole:

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled
  #keyFile: replace_me
```

**Comment by david9969** [comment]
Hello,

net.ipv6 is set to true and bindIpAll as well . see the mongodb.conf below:

# where and how to store data.
storage:
  dbPath: /bitnami/mongodb/data/db
  journal:
    enabled: true
  directoryPerDB: false

# where to write logging data.
systemLog:
  destination: file
  quiet: false
  logAppend: true
  logRotate: reopen
  path: /opt/bitnami/mongodb/logs/mongodb.log
  verbosity: 0

# network interfaces
net:
  port: 27017
  unixDomainSocket:
    enabled: true
    pathPrefix: /opt/bitnami/mongodb/tmp
  **ipv6: true
  bindIpAll: true**
  #bindIp:

# replica set options
replication:
  replSetName: rs0
  enableMajorityReadConcern: true

# sharding options
#sharding:
  #clusterRole:

# process management options
processManagement:
   fork: false
   pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

# set parameter options
setParameter:
   enableLocalhostAuthBypass: false

# security options
security:
  authorization: enabled

The service is does not become 1/1 running :

`kubectl get pods | grep mongo
mongodb-0                                                  0/1     Running                 0          3m57s
mongodb-arbiter-0                                          0/1     Running                 1          3m55s
`

When I check logs for mongodb-0 I can see connections to ipv4. We shall see here an ipv6. 

{"t":{"$date":"2021-11-05T07:49:08.393+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn52","msg":"client metadata","attr":{"remote":"**127.0.0.1**:48188","client":"conn52","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.10"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 3.10.0-1160.24.1.el7.x86_64"}}}}

**Comment by carrodher** [comment]
With `bindIpAll: true`, MongoDB is being binding to both IPv4 and IPv6 addresses so it's possible to see some logs regarding IPv4, what is not normal is that containers inside pods are not running, I don't think this is going to be related to the IP binding configuration.

Can you check why the containers in the `mongodb-0` and `mongodb-arbiter-0` pods are not running?

**Comment by david9969** [comment]
The problem is clearly with the connection if I want to access that link in ipv4 127.0.0.1 it will timeout ... but if I try with IPV6 :: it is working so need somehow force all the connections through ipv6 because ipv4 is not reachable. 

This is why mongodb are not running - no errors on pods . Can you please advise ?

**Comment by marcosbc** [comment]
Hi @david9969, the `enableIPV6` option will only enable IPv6 for the MongoDB node in the configuration. However, if you want nodes to advertise a different hostname, you must also set `externalAccess.service.domain`/`externalAccess.hidden.service.domain`.

**Comment by david9969** [comment]
We are using MongoDB in a k8s Ipv6 cluster.

Will this parameters (externalAccess.service.domain/externalAccess.hidden.service.domain )change the healthcheck to ipv6 ? 

IF yes, how can to set them ? What value ? Don't see anything in your documentation about these parameters.

Liveness and Readiness Healthcheck is failing because they are trying to connect on 127.0.0.1 , see the log below for eg:

{"t":{"$date":"2021-11-08T15:20:49.978+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1210","msg":"client metadata","attr":{"remote":"127.0.0.1:45104","client":"conn1210","doc":{"application":{"name":"MongoDB Shell"},"driver":{"name":"MongoDB Internal Client","version":"4.4.10"},"os":{"type":"Linux","name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","architecture":"x86_64","version":"Kernel 3.10.0-1160.24.1.el7.x86_64"}}}}

If we replace 127.0.0.1 with [::] the request is success. We need somehow force mongodb connections through IPV6 not ipv4 (127.0.0.1)

**Comment by carrodher** [comment]
The information about the different parameters can be found in the chart README, for example in this section https://github.com/bitnami/charts/tree/master/bitnami/mongodb#traffic-exposure-parameters

Apart from that, you can take a look at the [_values.yaml_](https://github.com/bitnami/charts/blob/897ff948a0d54d8667ec01ba59ecb28550492824/bitnami/mongodb/values.yaml#L711):
```yaml
## External Access to MongoDB&reg; nodes configuration
##
externalAccess:
  ...
  ## Parameters to configure K8s service(s) used to externally access MongoDB&reg;
  ## A new service per broker will be created
  ##
  service:
    ...
    ## @param externalAccess.service.domain Domain or external IP used to configure MongoDB&reg; advertised hostname when service type is NodePort
    ## If not specified, the container will try to get the kubernetes node external IP
    ## e.g:
    ## domain: mydomain.com
    ##
    domain: ""
```
