### ISSUE TITLE
No log rotation options in environment config or container.

### ISSUE THREAD

**Issue by j4ys0n** [bitnami/bitnami-docker-mongodb#301]
**Description**

There do not appear to be any log file management options aside from enable/disable and verbosity level. Because of this, my mongos servers (and i'm assuming mongod also) running in docker continually fill up their disks. I've gone through your docs, source code, and googled extensively. I haven't been able to locate logrotate.conf in the mongodb docker containers.

**Steps to reproduce the issue:**

1. run mongos/mongodb docker image (i'm using compose)
2. make lots of queries

**Describe the results you received:**

log file grows to fill disk

**Describe the results you expected:**

log file is rotated to avoid filling the disk

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 20.10.8, build 3967b7d
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: container-id
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1045-aws
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.637GiB
 Name: ip-x-x-x-x
 ID: W72D:5FL3:GVUQ:JDV7:HZ77:U42V:M2EF:4JG4:MWC6:BU7P:UTGQ:6ANO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

AWS

**Comment by j4ys0n** [comment]
Ok - Looks like I'm wrong about the root cause. The mongodb.log is linked to `/dev/stdout`
```
I have no name!@30e78ba863b2:/$ ls -lah /opt/bitnami/mongodb/logs/
total 16K
drwxrwxr-x 1 root root 4.0K Sep 28 02:34 .
drwxrwxr-x 1 root root 4.0K Sep 27 02:01 ..
drwx------ 2 1001 root 4.0K Nov  6 17:09 mongodb.diagnostic.data
lrwxrwxrwx 1 root root   11 Sep 27 02:01 mongodb.log -> /dev/stdout
```
and running `du -h` says the container file system is only ~600MB total. which means the issue is docker container log... 

and voilà 
```
ubuntu@ip-x-x-x-x:~$ sudo ls -lah /var/lib/docker/containers/container-id
total 37G
drwx-----x 4 root root 4.0K Oct 21 11:04 .
drwx-----x 3 root root 4.0K Sep 28 02:34 ..
-rw-r----- 1 root root  37G Nov  6 17:12 container-id-json.log
```

adding this do my docker-compose configs:

```
    logging:
      driver: 'json-file'
      options:
        max-size: 100m
        max-file: '3'
```

if not using file-based logging (json-file) is default, then this likely isn't an issue.

it might be worth mentioning this in the documentation/readme somewhere.. or this issue might be enough for people to find via google.

**Comment by alemorcuq** [comment]
Thanks for taking your time debugging this! There's already a section in the README (https://github.com/bitnami/bitnami-docker-mongodb#logging) that talks about logging and links to Docker's official documentation for configuring logging.
