### ISSUE TITLE
can not init mongodb replicaSet 

### ISSUE THREAD

**Issue by wuruipeng404** [bitnami/bitnami-docker-mongodb#308]
System: CentOS 7.9
Kubernetes: 1.22.3
CNI: flannel 0.15.1

the arbiter log 
![image](https://user-images.githubusercontent.com/34570968/144784503-843c6b1d-d8d4-4017-b95e-fddf1eb4ea26.png)

the mongo pod
![image](https://user-images.githubusercontent.com/34570968/144784600-c55828d1-fdc7-4a89-9b0d-6665695509f0.png)

**Comment by javsalgar** [comment]
Hi,

It seems to me that there's an issue with your DNS provider in the cluster? Could you check it? Are the nodes marked as ready?

**Comment by wuruipeng404** [comment]
> Hi,
> 
> It seems to me that there's an issue with your DNS provider in the cluster? Could you check it? Are the nodes marked as ready?

Hello, it is indeed a DNS problem. The K8S version is incompatible with Flannel version. Now I have backed back K8S version to 1.20 and the problem has been solved
