### ISSUE TITLE
m1 compatible image

### ISSUE THREAD

**Issue by amirjani** [bitnami/bitnami-docker-mongodb#310]
Hi, 

I Just wondering is there any plan for release a m1 compatible version? 
because there is a lot of failure and strange behaviors in m1 Mac book 

<img width="293" alt="Screen Shot 2021-12-13 at 5 28 58 PM" src="https://user-images.githubusercontent.com/24614096/145821180-d0a3bcf9-a90a-4484-ab9e-59781dc2dd44.png">

**Comment by miguelaeh** [comment]
Hi @amirjani ,
We are performing some investigations about ARM images but we cannot provide an ETA for ahaving this image released for ARM procesors.

**Comment by carrodher** [comment]
Hi, we just created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
