### ISSUE TITLE
Secondary is never becoming available when used in replicaset mode and nodeports are used. Using the bitnami helm chart.

### ISSUE THREAD

**Issue by pranavparuchuri** [bitnami/bitnami-docker-mongodb#313]
**Description**

The secondary is never becoming available when used in replicaset mode and nodeports are used. Using the bitnami helm chart.
The secondary pod is stuck at  "Waiting until initial data sync is complete..." until the MONGODB_MAX_TIMEOUT is reached and fails.

**Steps to reproduce the issue:**

Launch using the bitnami helm chart for mongo with the below config

```yaml
image:
  debug: true
architecture: replicaset
externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts: 
      - 30017
      - 30018
    domain: "{NodeIP/NodeHostName}"
auth:
  enabled: false
```
**Describe the results you received:**

Secondary node when starting with no data waits for initial data sync and then terminates after 35 secs.
Then on pod restart, secondary pod will still be unavailable and not joined to the replica set.
```
mongodb 11:27:33.16 INFO  ==> Primary node ready.
mongodb 11:27:33.22 INFO  ==> Node currently in the cluster
mongodb 11:27:33.23 INFO  ==> Waiting until initial data sync is complete...
mongodb 11:28:10.72 ERROR ==> Initial data sync did not finish after 35 seconds
mongodb 11:28:10.72 INFO  ==> Stopping MongoDB...
```
**Describe the results you expected:**

When starting with empty data in both primary and secondary. Secondary data sync should be near instant and not timeout after 35 secs. I have already tried above by increasing the timeout to 1000sec. Still, the same issue happens.
The other issue here is above in logs it says that the Node is in the cluster when in replica set config only primary and the arbiter are in the cluster.

**Additional information you deem important (e.g. issue happens only occasionally):**

I was able to debug the same and found the Root cause of the issue in the function 
**mongodb_configure_secondary** in the file https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh.

```bash
mongodb_configure_secondary() {
    local -r node="${1:?node is required}"
    local -r port="${2:?port is required}"

    mongodb_wait_for_primary_node "$MONGODB_INITIAL_PRIMARY_HOST" "$MONGODB_INITIAL_PRIMARY_PORT_NUMBER" "$MONGODB_INITIAL_PRIMARY_ROOT_USER" "$MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD"

    if mongodb_node_currently_in_cluster "$node"; then
        info "Node currently in the cluster"
    else
        info "Adding node to the cluster"
        if ! retry_while "mongodb_is_secondary_node_pending $node $port" "$MONGODB_MAX_TIMEOUT"; then
            error "Secondary node did not get ready"
            exit 1
        fi

```
We are using the function **mongodb_node_currently_in_cluster**  to check if the node is already in the cluster and if not initiate the replicaset. But in the case of a nodeport the node info for both primary and secondary will be the same. So after primary is added in the replica set when we are checking if the secondary is in the replicaset it's checking if the node is in replicaset and we are checking with the node and port combination so it's assuming secondary is already in the replicaset.

I think we need to create a new function based on **mongodb_node_currently_in_cluster** except it takes both node and port as args and check for the combination in the replicaset config instead of just node or we need to change the signature of the **mongodb_node_currently_in_cluster** to do the same I am just not sure about the other case which might be affected by such a change.

If an approach can be suggested I can submit a PR for the same as well.

I did create a new function taking both port and node and used it in that mongodb_configure_secondary function and the replicaset is starting fine at that time.

**Comment by miguelaeh** [comment]
Hi @pranavparuchuri ,
Thank you very much for digging into the issue.
I agree, there have been several issues using Nodeports with this MongoDB Helm Chart, and looks like what you found is the source of all those issues.
Could you send a PR modifying that function to include the port as a parameter when checking if the node is already added to the cluster?

**Comment by pranavparuchuri** [comment]
Hi @miguelaeh,

I have create the PR for the same. Now the function mongodb_node_currently_in_cluster requires two args host and port.
changed the function mongodb_wait_confirmation to also do the same as that also has the same issue.

https://github.com/bitnami/bitnami-docker-mongodb/pull/314

I was able to bring up nodeport based replicaset with 2 nodes and 1 arbiter successful. Have not tested the cases involving hidden nodes etc and other configurations.

If any changes are required in the PR Please suggest.

**Comment by miguelaeh** [comment]
Thank you very much @pranavparuchuri 👏
