### ISSUE TITLE
Unable to start up mongod due to missing featureCompatibilityVersion document

### ISSUE THREAD

**Issue by dnsisme** [bitnami/bitnami-docker-mongodb#320]
**Description**

**Steps to reproduce the issue:**
hi, In the same k8s cluster, when using helm to deploy Mongo in different ns, individual namespace deployment fails occasionally. The reason for the failures is missing  featurecompatibilityversion document. and the frequent restart of the corresponding pod.
1. helm install test01-mongo -n test01 ./mongodb
2. kubectl get pods -n test01 | grep mongo
3. kubectl describe pods test01-mongo-mongodb-secondary-0 -n test01

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/88881577/151193029-c7d7d278-04e7-463b-afb5-c9a4d91d528f.png)
![image](https://user-images.githubusercontent.com/88881577/151192946-45609c09-c7b9-48a5-8bdb-cc884d6d9721.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/88881577/151193217-4b2fdb14-baad-4d4b-be26-607e9d4f8c25.png)

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

kubectl version：v1.20.10
helm version：v3.6.3
cenots：CentOS Linux release 7.5.1804 (Core)
kernel：4.14.0_1-0-0-45
![image](https://user-images.githubusercontent.com/88881577/151193622-d366c9ec-8d85-4014-aeff-25da942f994e.png)

2022-01-26T15:23:18.211+0000 F STORAGE [initandlisten] Unable to start up mongod due to missing featureCompatibilityVersion document.
2022-01-26T15:23:18.211+0000 F STORAGE [initandlisten] Please run with --repair to restore the document.
2022-01-26T15:23:18.211+0000 F - [initandlisten] Fatal Assertion 40652 at src/mongo/db/repair_database_and_check_version.cpp 579
2022-01-26T15:23:18.211+0000 F - [initandlisten]
***aborting after fassert() failure

thanks~

**Comment by juan131** [comment]
Hi @dnsisme 

Please correct me if I'm wrong but it doesn't look like an error with the Bitnami MongoDB chart but your cluster's CNI, am I right? I'd recommend you contact the Kubernetes Network SIG to find more info about how to troubleshoot this kind of errors.

**Comment by dnsisme** [comment]
> Hi @dnsisme
> 
> Please correct me if I'm wrong but it doesn't look like an error with the Bitnami MongoDB chart but your cluster's CNI, am I right? I'd recommend you contact the Kubernetes Network SIG to find more info about how to troubleshoot this kind of errors.



> Hi @dnsisme
> 
> Please correct me if I'm wrong but it doesn't look like an error with the Bitnami MongoDB chart but your cluster's CNI, am I right? I'd recommend you contact the Kubernetes Network SIG to find more info about how to troubleshoot this kind of errors.

Hi @juan131 

Your understanding is correct. I temporarily solved the problem by upgrading the new version. Next, I will continue to contact kubernetes network sig to find more info about how to troubleshoot this kind of errors,thx~

**Comment by dnsisme** [comment]
> 
Hi @juan131 

Your understanding is correct. I temporarily solved the problem by upgrading the new version. Next, I will continue to contact kubernetes network sig to find more info about how to troubleshoot this kind of errors,thx~

**Comment by juan131** [comment]
Great! Thanks so much for confirm so @dnsisme, I'm very glad you were able to solve the issue.
I'll proceed to close the issue.
