### ISSUE TITLE
Architecture is hard-coded to amd64 in dockerfile

### ISSUE THREAD

**Issue by antony** [bitnami/bitnami-docker-mongodb#323]
### Name and Version

bitnami/mongodb:5.0

### What steps will reproduce the bug?

1. Run the container on an arm64 machine
2. Get exec format error

### What is the expected behavior?

If the architecture wasn't hardcoded in the Dockerfile, an architecture appropriate version of mongo would be installed and run

The base bitnami buster image supports arm64 as of a year or so ago, and mongo itself supports arm64, so I think this should work.

### What do you see instead?

exec format error

### Additional information

Useful for CI machines that run on arm, and in my case, a Pinebook Pro dev machine which has an arm processor.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
