### ISSUE TITLE
Can't configure replicaset if data already exists 

### ISSUE THREAD

**Issue by iKrushYou** [bitnami/bitnami-docker-mongodb#324]
### Name and Version

bitnami/mongodb:4.2

### What steps will reproduce the bug?

In one terminal window, run (make sure `~/data/mongodb` is empty)
```
docker run -e MONGODB_REPLICA_SET_MODE=primary -e MONGODB_REPLICA_SET_NAME=rs0 -e ALLOW_EMPTY_PASSWORD=yes -it -p 27017:27017 -v ~/data/mongodb:/bitnami bitnami/mongodb:4.2
```
In another terminal window, log into the db and check the rs status
```
mongo

rs0:PRIMARY> rs.status()
{
	"set" : "rs0",
	"date" : ISODate("2022-03-08T17:41:01.500Z"),
	"myState" : 1,
```
Quit the docker process and re-run with the same command. Repeat logging in and checking rs status. You can see that the RS config is correct again.

Kill the docker container again and run without RS config
```
docker run -it -p 27017:27017 -v ~/data/mongodb:/bitnami bitnami/mongodb:4.2
```
Log in and verify that there is no RS configured
```
mongo

> rs.status()
{
	"ok" : 0,
	"errmsg" : "not running with --replSet",
	"code" : 76,
	"codeName" : "NoReplicationEnabled"
}
```

Now, clear the contents of `~/data/mongodb` and run
```
docker run -it -p 27017:27017 -v ~/data/mongodb:/bitnami bitnami/mongodb:4.2
```
Log in, verify no RS config

Kill docker process and run original command
```
docker run -e MONGODB_REPLICA_SET_MODE=primary -e MONGODB_REPLICA_SET_NAME=rs0 -e ALLOW_EMPTY_PASSWORD=yes -it -p 27017:27017 -v ~/data/mongodb:/bitnami bitnami/mongodb:4.2
```
log in, verify that there is still no RS config

### What is the expected behavior?

I would expect that when I specify an RS config that the DB starts up with the proper RS configuration 

### What do you see instead?

no RS config

**Comment by rafariossaa** [comment]
Hi,
  The initialization logic check if there is data in the volume and if there is data then the configuration steps are not performed. The logic is [in the function `mongodb_initialize`](https://github.com/bitnami/bitnami-docker-mongodb/blob/c2f37f4c29fd24fc48856cfe497c10f6373c1b7f/4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1382).
This is intended, so once configured you are no changing the configuration of a persisted database.
