### ISSUE TITLE
Example connectionstring for replicaset compose file

### ISSUE THREAD

**Issue by cknaap** [bitnami/bitnami-docker-mongodb#327]
### Name and Version

bitnami/mongo5.0

### What is the problem this feature will solve?

The [docker-compose-replicaset.yml](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose-replicaset.yml) sets up a replicaset nicely.
But afterwards it is very hard to find out what the connectionstring should look like to connect to it.

### What is the feature you are proposing to solve the problem?

Add an example connectionstring matching the docker-compose-replicaset.yml setup. Either in the readme.md or as a comment in the yml itself.

### What alternatives have you considered?

Finding out myself what the connectionstring should be - I failed.

**Comment by javsalgar** [comment]
Hi. For the docker-compose you are using it you would need to launch a container inside the same network as the docker-compose environment and then use the hosts `mongodb-primary` and `mongodb-secondary`
