### ISSUE TITLE
Failure trying to install vim per "install_packages" script

### ISSUE THREAD

**Issue by bitsofinfo** [bitnami/bitnami-docker-mongodb#330]
### Name and Version

5.0.6

### What steps will reproduce the bug?

```
kubectl run --namespace mongodb mongo-client --rm --tty -i --image bitnami/mongodb /bin/bash
```

From inside the container:
```
I have no name!@mongo-client:/$ install_packages vim

E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
```

https://github.com/bitnami/bitnami-docker-mongodb/issues/79

### What is the expected behavior?

I should be able to install an additional package when inside the container

### What do you see instead?

error `E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)`

### Additional information

https://github.com/bitnami/bitnami-docker-mongodb/issues/79

**Comment by javsalgar** [comment]
Hi,

Please note that this is a non-root container. If you want to install a package you need to launch the container as root or create a forked image.
