### ISSUE TITLE
Readiness and Liveness probes failing

### ISSUE THREAD

**Issue by vishZeno** [bitnami/bitnami-docker-mongodb#331]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

Trying to deploy bitnami/mongodb latest (5.0 or above) using terraform on minikube
Same code and config works on Ubuntu but is failing on macOS (Macbook Pro M1)

If the bitnami/mongodb image tag is removed from values.yaml then by default it loads with bitnami/mongodb:4.4 and everything works

Not sure why 5.0 is not working but 4.4 is working

main.tf
------
resource "helm_release" "mongodb" {
  name       = "mongodb"
  repository = "https://charts.bitnami.com/bitnami"
  chart      = "mongodb"
  version    = "11.0.2"

  values = [
    file("mongodb_values.yaml"),
  ]
}

mongodb_values.yaml
--------------------
auth:
  rootPassword: "password"

image:
  tag: "latest"

### What is the expected behavior?

MongoDB up and running

### What do you see instead?

ERROR

Readiness failed
Readiness probe failed: command "bash -ec # Run the proper check depending on the version\n[[ $(mongo --version | grep \"MongoDB shell\") =~ ([0-9]+\\.[0-9]+\\.[0-9]+) ]] && VERSION=${BASH_REMATCH[1]}\n. /opt/bitnami/scripts/libversion.sh\nVERSION_MAJOR=\"$(get_sematic_version \"$VERSION\" 1)\"\nVERSION_MINOR=\"$(get_sematic_version \"$VERSION\" 2)\"\nVERSION_PATCH=\"$(get_sematic_version \"$VERSION\" 3)\"\nif [[ \"$VERSION_MAJOR\" -ge 4 ]] && [[ \"$VERSION_MINOR\" -ge 4 ]] && [[ \"$VERSION_PATCH\" -ge 2 ]]; then\n mongo --disableImplicitSessions $TLS_OPTIONS --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep -q 'true'\nelse\n mongo --disableImplicitSessions $TLS_OPTIONS --eval 'db.isMaster().ismaster || db.isMaster().secondary' | grep -q 'true'\nfi\n" timed out

Liveness failed
Liveness probe failed: command "mongo --disableImplicitSessions --eval db.adminCommand('ping')" timed out

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. We received tickets about some assets not working on Macbook M1.

**Comment by vishZeno** [comment]
Hi @javsalgar thanks for your response. I was just curious because the 4.4 image is working fine on the ARM processors but 5.0 is failing. Let me know if I have missed anything, else I will wait for the next update

**Comment by javsalgar** [comment]
I'm not sure about the reason, probably in 4.4 some features may be failing as well. We will let you know as soon as we have a plan for ARM.

**Comment by vishZeno** [comment]
Thanks for your response. I will be waiting for the updates!
