### ISSUE TITLE
replica sets not starting since update to 4.2.19-debian-10-r48 last night

### ISSUE THREAD

**Issue by dave-yotta** [bitnami/bitnami-docker-mongodb#333]
### Name and Version

4.2.19-debian-10-r48

### What steps will reproduce the bug?

use the bitnami-mongodb-chart v10.20.5 to start a replica set

### What is the expected behavior?

all nodes become ready

### What do you see instead?

first secondary node becomes stuck at this check: https://github.com/bitnami/bitnami-docker-mongodb/blob/02b8da41e360028422fa995b46b489d443362a12/4.2/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L1092

### Additional information

pinning to 4.2.19-debian-10-r47 has resolved the issue in our development pipelines
the issue doesn't happen in local (which in my case is a docker desktop kubernetes cluster)
but it does happen on pipeline, which is running kind
and it does happen in our Amazon EKS clusters

**Comment by dave-yotta** [comment]
Hey there, I'll share what I can and what I remember!

Yes it times out.  The command checking for users in the primary is returning false, checking the shell command by kubectl exec onto the secondary and running it, we get a response (no users).  We're using passwordless, here's what we've overridden in the values.yaml at the time:

```
# bitnami mongodb values
mongodb:
  # auth:
  #   enabled: true
  #   rootPassword: setatruntime
  #   replicatSetKey: setatruntime
  # tls:
  #   enabled: true
  #   autoGenerated: true
  fullnameOverride: local-mongo # from bitnami common
  architecture: replicaset
  replicaCount: 3
  replicaSetName: rs1
  arbiter:
    enabled: false
  image:
    tag: 4.2.19-debian-10-r47
    debug: true
  auth:
    enabled: false
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 1024Mi
```
we've since changed the tag to `4.2.19-debian-10-r47` obviously so I don't have any more info without finding the time to dig into it again.

**Comment by fmulero** [comment]
Thanks @dave-yotta. We recently migrated to new MongoDB Shell (`mongosh`) and it seems slower than `mongo` commands. We are working on it. I'll share any news in this issue

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
