### ISSUE TITLE
How can I rs.status()?

### ISSUE THREAD

**Issue by Zehuif** [bitnami/bitnami-docker-mongodb#336]
### Name and Version

lasted

### What is the problem this feature will solve?

Hi I want to know how to rs.status(). I don't know how to do it pleasy help me :(.

### What is the feature you are proposing to solve the problem?

More clear instruction in readme.

**Comment by javsalgar** [comment]
Hi,

In order to execute rs.status() you need to use a mongodb client. I advise you to check with the upstream MongoDB getting started guide: https://www.mongodb.com/docs/manual/tutorial/getting-started/
