### ISSUE TITLE
Connecting to a replicaset mongodb from docker host

### ISSUE THREAD

**Issue by Lucaber** [bitnami/bitnami-docker-mongodb#337]
### Name and Version

bitnami/mongodb:4.4

### What steps will reproduce the bug?

Starting a replicaset mongodb in the default docker bridged network
```
docker run --name mongodb-primary -p 27017:27017 \
  -e MONGODB_REPLICA_SET_MODE=primary \
  -e MONGODB_ROOT_PASSWORD=password123 \
  -e MONGODB_REPLICA_SET_KEY=replicasetkey123 \
  bitnami/mongodb:4.4
```
Connect from the docker host
`mongo --host replicaset/localhost`

### What is the expected behavior?

Connection successful with version 4.4.13-debian-10-r58
```
2022-05-17T16:04:39.676+0200 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to 192.168.176.2:27017
2022-05-17T16:04:39.677+0200 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for replicaset is replicaset/192.168.176.2:27017
Implicit session: session { "id" : UUID("466b80e6-15f3-4d6d-bd2e-ec70b17fdbb2") }
MongoDB server version: 4.4.13
WARNING: shell and server versions do not match
replicaset:PRIMARY>
```

### What do you see instead?

Connection to the replicaset fails
```
2022-05-17T16:09:04.103+0200 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for replicaset is replicaset/89dfe114ad8d:27017
2022-05-17T16:09:04.103+0200 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to 89dfe114ad8d:27017
[hangs]
```

### Additional information

Starting with r59 in [this](https://github.com/bitnami/bitnami-docker-mongodb/commit/a1029c11dc03671e8c9cb09be2b1075ede2d4dee#diff-12ebc6fb99fa5ad828da067dfcd0fb89ea07fc597b629d45701f2722ed4e6cd7R254) commit, the default advertised hostname has been changed from the container ip to the container hostname.
The host or other container(in the default network) are not able to resolve the container hostname.

Running all container in a network or connecting them with `--link` could resolve the issue but wouldn't make it possible to use the replicaset from the docker host.

Starting a container without `MONGODB_ADVERTISED_HOSTNAME` even throws a warning with false information: `WARN  ==> In order to use hostnames instead of IPs your should set MONGODB_ADVERTISED_HOSTNAME`.

The [replicaset example in the readme](https://github.com/bitnami/bitnami-docker-mongodb#step-1-create-the-replication-primary) doesn't work either. The default hostname of a container is the ID `89dfe114ad8d` not `mongodb-primary`.

Is there any more information on why this behavior has been changed? Where are the changes of the single commit `4.4.13-debian-10-r59 release ` coming from?
To fix this issue in my current environment, I would need to set `MONGODB_ADVERTISED_HOSTNAME` to the container ip but isn't available to me before starting the container.

**Comment by Lucaber** [comment]
With `MONGODB_ADVERTISED_HOSTNAME=127.0.0.1` we are only able to connect from the host or the mongodb container itself. Connecting from other containers in the same docker network is now not possible anymore. 
A new env var like `MONGODB_ADVERTISE_IP` could be used to advertise the container IP. I'm ready to create a pull request if this solution would be accepted.

**Comment by javsalgar** [comment]
Hi!

Sure! PRs are welcome! Feel free to create a draft that we can use for discussion.
