### ISSUE TITLE
Replicate data between 2 mongodb replicasets

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/bitnami-docker-mongodb#339]
### Name and Version

bitnami/mongodb

### What is the problem this feature will solve?

I would like to migrate the data of a mongodb replicaset (a) to a different mongodb replicaset (b) using replication

### What is the feature you are proposing to solve the problem?

There are a few guides online that show it is possible : 

https://mschmitt.org/blog/mongodb-migration-replicaset/

https://www.mongodb.com/docs/manual/tutorial/deploy-geographically-distributed-replica-set/

However upon attempting i get the following error:

```
replica set IDs do not match, ours: 628cb373d4eda0a12d1a75e0; remote node's: 6290888e8c0f616827de3033"
```

### What alternatives have you considered?

mongodump/restore likely cause loss of some data.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami mongodb container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
