### ISSUE TITLE
Can't start Mongodb 5.x: Illegal instruction

### ISSUE THREAD

**Issue by linuxmail** [bitnami/bitnami-docker-mongodb#340]
### Name and Version

bitnami/mongodb:latest

### What steps will reproduce the bug?

1. OS: Debian Buster
2. VM: Proxmox  KVM with CPU KVM64
3. Version: docker-ce-cli 5:20.10.12~3-0~debian-buster 
4. Command to start:  docker run --name mongodb bitnami/mongodb:latest

### What is the expected behavior?

Starting MongoDB

### What do you see instead?

```
$ docker run --name mongodb bitnami/mongodb:latest
mongodb 12:07:49.53 
mongodb 12:07:49.53 Welcome to the Bitnami mongodb container
mongodb 12:07:49.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 12:07:49.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 12:07:49.54 
mongodb 12:07:49.54 INFO  ==> ** Starting MongoDB setup **
mongodb 12:07:49.56 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 12:07:49.60 INFO  ==> Initializing MongoDB...
mongodb 12:07:49.62 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 336:    44 Illegal instruction     "$@" > /dev/null 2>&1
```

### Additional information

Tried to create a Cluster with docker-compose file, but failed .. so I tried with the single command .. and have the same issue.

**Comment by linuxmail** [comment]
I've tested some other version with MongoDB 5.x but got only 4.x working as expected.

**Comment by linuxmail** [comment]
I can confirm it. If the host CPU has this flag and the KVM CPU would switched to CPU "Host", MongoDB 5.x starts.

It would be nice .. if a script checks before MongoDB 5.x starts, if this CPU flag exists.

**Comment by vglaiju** [comment]
Thanks  i was googling in vain, why mongodb:5.0.9-debian-10-r11 always lead to /opt/bitnami/scripts/libos.sh: line 336:    64 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1 & never hit this post.
Guess I shoud have checked this issues first.
OK so ill try with 4.x
