### ISSUE TITLE
zstd version is old (1.3.8)

### ISSUE THREAD

**Issue by nicolaerosia** [bitnami/bitnami-docker-mongodb#352]
### Name and Version

docker.io/bitnami/mongodb:5.0.9

### What steps will reproduce the bug?

zstd 1.3.8 is from `Dec 27, 2018`

```sh
docker run -it docker.io/bitnami/mongodb:5.0.9-debian-10-r11 /bin/bash

find /usr/lib -name '*zst*'
/usr/lib/x86_64-linux-gnu/libzstd.so.1
/usr/lib/x86_64-linux-gnu/libzstd.so.1.3.8
```

### What do you see instead?

The official mongodb image is using a newer zstd
```sh
docker run -it docker.io/mongo:5.0 /bin/bash
find /usr/lib -name '*zst*'
/usr/lib/x86_64-linux-gnu/libzstd.so.1
/usr/lib/x86_64-linux-gnu/libzstd.so.1.4.4
```

Any reason you're using an old zstd? Newer versions have much better performance.

**Comment by javsalgar** [comment]
Hi,

This is because we were using Debian 10 images. Now, in the latest releases, we are using Debian 11 which ships a newer version of zstd

```
I have no name!@d35b3f443a71:/$ find /usr/lib -name '*zst*'
/usr/lib/x86_64-linux-gnu/libzstd.so.1
/usr/lib/x86_64-linux-gnu/libzstd.so.1.4.8
```

**Comment by nicolaerosia** [comment]
oh, thank you very much, I was not aware there are debian 11 images, thanks!
