### ISSUE TITLE
[request] Setting of UID and GID 

### ISSUE THREAD

**Issue by bott0r** [bitnami/bitnami-docker-mongodb#75]
I am looking for a way to set UID and GID upon pulling the docker image, often there is a way to set it via environmental variables.

cheers 
 -b

**Comment by prydonius** [comment]
Hey @bott0r, we're actually looking into moving our containers to run as non-root users and support the Docker `USER` command. Once that's supported, you'd be able to run the container with any uid with the `docker run --user` flag. I'm not sure when we expect that change to happen though, as there are some internal build pipeline changes and we also need to review the security aspect of these changes.

**Comment by akd31** [comment]
Is there any update for this ?

**Comment by juan131** [comment]
Hi @akd31 we haven't moved this Docker Image to **non-root** yet. At this moment, this is the list of Docker Images that already supports this functionality:

- Nginx
- Kafka
- Zookeeper
- Ghost
- Memcached
- Redis
- MariaDB

**Comment by OpenApisGuard** [comment]
Hi, any plan to support non-root users for Cassandra

**Comment by juan131** [comment]
Hi @OpenApisGuard 

AFAIK, we do not have immediate plans to work on it.

cc/ @tompizmor @sameersbn

**Comment by djzager** [comment]
I made an attempt to update this container for running as a non-root user but failed.

Here are my changes:

```diff
diff --git a/3.7/Dockerfile b/3.7/Dockerfile
index f32a604..44000a5 100644
--- a/3.7/Dockerfile
+++ b/3.7/Dockerfile
@@ -1,6 +1,9 @@
 FROM bitnami/minideb-extras:jessie-r24
 LABEL maintainer "Bitnami <containers@bitnami.com>"

+ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
+    HOME="/"
+
 # Install required system packages and dependencies
 RUN install_packages libc6 libgcc1 libpcap0.8 libssl1.0.0
 RUN bitnami-pkg unpack mongodb-3.7.3-0 --checksum 63f389d722788ccbf82b1bf395ab9241739a1d02393c9e072f7140868ff5bf58
@@ -25,5 +28,6 @@ ENV BITNAMI_APP_NAME="mongodb" \

 EXPOSE 27017

+USER 1001
 ENTRYPOINT ["/app-entrypoint.sh"]
 CMD ["/run.sh"]
diff --git a/3.7/rootfs/run.sh b/3.7/rootfs/run.sh
index 7bed039..d50a006 100755
--- a/3.7/rootfs/run.sh
+++ b/3.7/rootfs/run.sh
@@ -11,4 +11,8 @@ ARGS="--config /opt/bitnami/mongodb/conf/mongodb.conf"
 sed -i 's/path: .*\/mongodb.log/path: /' /bitnami/mongodb/conf/mongodb.conf

 info "Starting ${DAEMON}..."
-exec gosu ${USER} ${EXEC} ${ARGS}
+if [ $EUID -eq 0 ]; then
+    exec gosu ${USER} ${EXEC} ${ARGS}
+else
+    exec ${EXEC} ${ARGS}
+fi
```

Build, run, and :cry: : 

```
$ docker run --rm --name mongodb docker.io/djzager/mongodb:test

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': You have to be root to call start
```

Same as @redbaron I attempted to find the mongodb nami package with no success. I'm happy to contribute effort to get this container image updated, just point me in the right direction.

**Comment by javsalgar** [comment]
Hi,

Currently, we do not have the nami packages in a Github repo, but you can download it from here:  https://downloads.bitnami.com/files/stacksmith/mongodb-3.7.3-0-linux-x64-debian-8.tar.gz

(reference: https://github.com/bitnami/minideb-extras/blob/master/jessie/rootfs/usr/local/bin/bitnami-pkg)

Inside, you will see node.js files with the installation logic.  `main.js` and `helpers.js` are the important ones. If you want to get rid of the error above, add the following snippet to `main.js`.

```
$app.postUnpackFiles = function() {
  // Needed so we can call to $app.start and similar while initiasing as non-root
  $app.installedAsRoot = false;
};
```

The issue appears because the module was installed as root (during the container build process). This fix should workaround the issue. You will need to see if there are other changes to be done in the actual installation logic to make it work as non-root. Feel free to share with us the changes you perform and we will review them :)

Let us know if there is anything else we can help you with.

**Comment by redbaron** [comment]
> Feel free to share with us the changes you perform and we will review them :)

making changes to a tarball and share diffs here? no , please publish nami packages as github projects, at least as a mirror from your internal repos.

**Comment by dotf** [comment]
Any news on this one? Is it planned to make it run as non-root user?

**Comment by juan131** [comment]
Hi @dotf 

It is not planned to be moved to a non-root approach, at least in the short term.

**Comment by eldada** [comment]
@juan131 - I see custom UID is now working. What about GID? Often the requirement is to link to an existing user with an already set group, which is non root.
Running with custom GID gives the following error:
```
$ docker run --rm --name mongodb --user 2002:2002 bitnami/mongodb:latest

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
EACCES: permission denied, open '/.nami/registry.json'
```

Any idea or plan to support this soon?

**Comment by javsalgar** [comment]
Hi,

Currently, our Bitnami MongoDB works as non-root. This non-root user group must necessarily belong to the root user as well. It doesn't come to mind a way to make our current configuration compatible with any random group (that does not belong to the `root` group). I do not think there are short term plans to allow this configuration. However, could you provide more information about your use case so we understand why it requires a custom group?

**Comment by eldada** [comment]
Hi @javsalgar,
The use case is fairly simple. Some organisations (enterprise) enforce running all Docker containers with a custom user and group for full control and compliance. This is usually mapped to a dedicated user on the host. This is usually a security measure. Can be argued, but still. This is the requirement. To make it really work in the container, the file system permissions have to be more relaxed (if this is even possible). 
IMHO, you should consider implementing such support. Especially for the enterprise.

**Comment by javsalgar** [comment]
Interesting. I have my concerns about relaxing the permissions more, I am not sure if this could potentially compromise the container. Do you have any example of Dockerfile that is compatible with your use case?

**Comment by javsalgar** [comment]
At the moment that's the only solution that comes to mind: creating a user and a group that matches your requirements.
