### ISSUE TITLE
Container volume path is incorrectly documented

### ISSUE THREAD

**Issue by scarlac** [bitnami/bitnami-docker-mongodb#80]
**Description**

Data volume path in documentation is incorrect.

**Steps to reproduce the issue:**

1. Follow documentation instruction on running a container with a host-mounted folder for the data dir `docker run -v /path/to/mongodb-persistence:/bitnami bitnami/mongodb:latest`
2. Wait for server to finish launching

**Describe the results you received:**

Host data folder is empty.

**Describe the results you expected:**

Expected it to be full of data files from the mongo server

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a documentation issue.

**Version**

- Output of `docker version`:

```
docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
docker info
Containers: 7
 Running: 4
 Paused: 0
 Stopped: 3
Images: 169
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 283
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: F425:IB6N:LXGE:ZMJJ:BQ7T:I5KY:HQBS:DU56:RUDT:IN4B:EM5V:JYJR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 69
 Goroutines: 94
 System Time: 2017-07-14T17:08:54.944889016Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Volume should be mapped as `./whateverlocalfolder:/opt/bitnami` not `./whateverlocalfolder:/bitnami`

**Comment by silviofdez** [comment]
Hi,

I have tried to reproduce your issue with no luck, I execute `docker run -v /tmp/foo:/bitnami bitnami/mongodb:latest` and after that there in `/tmp/foo` there is a mongodb directory with conf and data.

**Comment by scarlac** [comment]
@silviofdez I just ran this exact command:
`~/jobs ✅  docker run -v ${PWD}/db:/bitnami bitnami/mongodb:latest`
And after it had started up I shut it down and ran:
```
[13:19:41] ~/jobs ✅  ls -alR db
total 16
drwxr-xr-x@   4 seph  staff   136 Jul 19 13:17 .
drwxr-xr-x+ 134 seph  staff  4556 Jul 19 13:17 ..
-rw-r--r--@   1 seph  staff  6148 Jul 19 13:18 .DS_Store
drwxr-xr-x+   2 seph  staff    68 Jul 19 13:17 mongodb

db/mongodb:
total 0
drwxr-xr-x+ 2 seph  staff   68 Jul 19 13:17 .
drwxr-xr-x@ 4 seph  staff  136 Jul 19 13:17 ..
```

Are you sure you are connected to the official docker hub and not using a "local" repository?

**Comment by scarlac** [comment]
Update: I just re-pulled the latest image from the hub and it's now generating the files correctly. My old image was 5 weeks old -  I didn't think to upgrade it already:
```
[13:19:46] ~/jobs ✅  docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
(...)
bitnami/mongodb         latest              5cd1e2e83dbe        5 weeks ago         400MB
```

My new image is:
```
[13:25:12] ~/jobs ✅  docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
bitnami/mongodb         latest              304c702e5e3d        13 days ago         389MB
```
You can close this issue. I'm just leaving these details in for future reference.

**Comment by prydonius** [comment]
@scarlac sorry for the inconvenience, this was due to a recent change where we removed the `VOLUMES` directive to allow more flexibility and enable users to choose between a single volume or separate ones.
