### ISSUE TITLE
How to log in / connect to running mongodb instance?

### ISSUE THREAD

**Issue by ahundt** [bitnami/bitnami-docker-mongodb#82]
Thanks for creating this mongodb docker setup, it looks like a huge time saver!

I followed the instructions and created a mongodb instance which I have running, but I'm not sure how to:

1. Connect to the mongo shell
2. Ensure the physical machine's ports are configured to connect to mongo publically
3. Ensure the physical machine's ports only locally available on the current machine for security or testing reasons.

Could you please advise?

**Comment by ahundt** [comment]
@prydonius I read through https://github.com/bitnami/bitnami-docker-mongodb/issues/62 but I was hoping the steps above could be done with simple command line commands or via pymongo with something like the following from https://github.com/IDSIA/sacred/issues/205:

```
echo "############################"
echo "# MongoDB persistent docker image"
echo "############################"
echo "#"
echo "# https://github.com/bitnami/bitnami-docker-mongodb"


username=mluser
password=SET_PASSWORD_BEFORE_RUNNING_THIS


https://github.com/bitnami/bitnami-docker-mongodb
mkdir -p $HOME/datasets/ml_models_sacred_mongodb/persistence

docker run --name mongodb \
  -v $HOME/datasets/ml_models_sacred_mongodb/persistence:/bitnami \
  -e MONGODB_USERNAME=$username -e MONGODB_PASSWORD=$password \
  -e MONGODB_DATABASE=sacred bitnami/mongodb:latest
```

Would the url I use be something like the following?
```
mluser:SET_PASSWORD_BEFORE_RUNNING_THIS@mycomputer.com:27017/sacred?authMechanism=SCRAM-SHA-1'
```

**Comment by ahundt** [comment]
maybe something like what's described in https://docs.docker.com/engine/userguide/networking/#exposing-and-publishing-ports should be added to my `docker run` call so port `27017` is accessible?

**Comment by prydonius** [comment]
@ahundt yep, you're missing the port mapping, so adding `-p 27017:27017` will get something like that url working. Looks like it's missing from our `docker run` examples, but FWIW I recommend using the `docker-compose` tool and the [Compose definition](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/docker-compose.yml). This will get you up and running with a single `docker-compose up`.

**Comment by ahundt** [comment]
thanks so I'd run something like `docker-compose path/to/file.yml` then `docker-compose up`? I've never used it before so I'm not familiar. Super dumb copy-pastable commands might also make the readme easier to learn from. :-)

Thanks for your help!

**Comment by prydonius** [comment]
Close, you need to create an new directory for your project and download the Docker Compose file there, then run `docker-compose up`:

```
$ mkdir myapp && cd myapp
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-mongodb/master/docker-compose.yml > docker-compose.yml
$ docker-compose up
```

We do have this snippet at the top of the README (https://github.com/bitnami/bitnami-docker-mongodb#docker-compose), but let me know if you think we can make it clearer!

**Comment by ahundt** [comment]
oh cool! Sure, the most helpful very small things would be:

1. Which is your "recommended" method of starting up
2. One additional line marked optional to connect to the mongo shell
3. The URL to connect to the database with the default configuration

extras could be:

4. Why you would use one method vs the other
5. a link to the docs for each command and/or a brief description of what it does

Thanks for your help!

**Comment by thomasjpfan** [comment]
A compose file is most useful when you want to run multiple services that need to talk to each other. For your original use case the compose file would look like this:
```yaml
version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_USERNAME: $username
      MONGODB_PASSWORD: $password
      MONGODB_DATABASE: sacred
    volumes:
      - $HOME/datasets/ml_models_sacred_mongodb/persistence:/bitnami
    ports:
      - "27017:27017"
```
and a bash script to run it:
```bash
username=mluser
password=onetwothree
docker-compose up -d
```
This would open up port 27017 on your localhost, so you can run:
```shell
>  mongo "mluser:onetwothree@localhost:27017/sacred"
```
to connect to the database.

If you are just running one service you can just have a single bash script:
```bash
username=mluser
password=onetwothree
docker run --name mongodb \
  -v $HOME/datasets/ml_models_sacred_mongodb/persistence:/bitnami \
  -e MONGODB_USERNAME=$username -e MONGODB_PASSWORD=$password \
  -e MONGODB_DATABASE=sacred \
  -p 27017:27017 -d \
  bitnami/mongodb:latest
```
to start the database. If you have one service, I would stick to using `docker run`. If you have more  than one service, I would use `docker-compose`.
