### ISSUE TITLE
How to add privileges to a database user?

### ISSUE THREAD

**Issue by rachelwilson** [bitnami/bitnami-docker-mongodb#85]
**Description**

I have followed the instructions to create a user and database on first run, and am able to connect to the mongo client in the docker container.  But I am unable to "show dbs" because that user needs the clusterAdmin privilege in order to list databases.  How do I add privileges to users?  Do I need to do this manually through the admin user, or is there a way via configuration?

**Steps to reproduce the issue:**

$ mongo "myuser:mypassword@localhost:27017/mydatabase"
MongoDB shell version v3.4.9
connecting to: mongodb://express:express@localhost:27017/runningorder
MongoDB server version: 3.4.9
> db
mydatabase
> show dbs
2017-12-04T17:26:49.870+0000 E QUERY    [thread1] Error: listDatabases failed:{
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { listDatabases: 1.0 }",
	"code" : 13,
	"codeName" : "Unauthorized"
} :

**Version**

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Docker for MAC

**Comment by chipironcin** [comment]
Hi @rachelwilson 
There are three possible situations:
- You launch the container without user
  - Full unathenticated access
- You launch the container with root password
  - Root user is enabled with full access
- You launch the container with user and password
  - User is enabled with limited access

So currently you dont have any root user. You have two options:
1. Recreate the containers using both root password and user/password environment variables.
2. Modify the `mongodb.conf` file located at `/opt/bitnami/mongodb/conf/mongodb.conf` to disable auth. Then restart the container, login and create an admin user. Then enable the auth again and restart the container.

To create the admin user:
```
db.createUser(
   {
       user: "tom", 
       pwd: "jerry", 
       roles:["root"]
   })
```
