### ISSUE TITLE
[helm/mongodb] Unable to start mongodb without authentication using helm chart

### ISSUE THREAD

**Issue by eldada** [bitnami/bitnami-docker-mongodb#93]
**Description**

Using the latest helm chart from https://github.com/kubernetes/charts/tree/master/stable/mongodb (2.0.1), there is no way to pass a blank `MONGODB_ROOT_PASSWORD` to enable unauthenticated access as suggested in https://github.com/bitnami/bitnami-docker-mongodb#setting-the-root-password-on-first-run
> When MONGODB_ROOT_PASSWORD is not specified the server allows unauthenticated and unrestricted access.

If I don't pass **mongodbRootPassword** or pass an empty string, a random password is created by the secret `mongodb-root-password`.

**Steps to reproduce the issue:**
1. Install the helm chart with a blank `mongodbRootPassword`: 
```
$ helm install --name mongodb --set mongodbRootPassword='' stable/mongodb
```
2. Get the value of `MONGODB_ROOT_PASSWORD`
```
$ kubectl exec -t jfmc-mongodb-566c95b8b7-6tcrs -- env | grep MONGODB_ROOT_PASSWORD
MONGODB_ROOT_PASSWORD=tK5enswngk
```

**Describe the results you received:**
MongoDB is still running with authentication with a random root password.
`MONGODB_ROOT_PASSWORD=tK5enswngk`

**Describe the results you expected:**
MongoDB running with no authentication
`MONGODB_ROOT_PASSWORD=`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
GKE, K8s 1.8.8, helm 2.8.1.
mongodb chart version 2.0.1.
mongodb version 3.6.3 (image.tag=3.6.3)

**From boot log:**
```
nami    INFO  Initializing mongodb
mongodb INFO  ==&gt; Creating root user...
mongodb INFO  ==&gt; Enabling authentication...
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Root Password: **********
mongodb INFO   (Passwords are not shown for security reasons)
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
```

**Comment by juan131** [comment]
As you can check at the Secrets file:
https://github.com/kubernetes/charts/blob/master/stable/mongodb/templates/secrets.yaml

It's configuring a random value when mongodbRootPassword it's empty:

```
  {{ if .Values.mongodbRootPassword }}
  mongodb-root-password:  {{ .Values.mongodbRootPassword | b64enc | quote }}
  {{ else }}
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
```

Will be valid for you if we implement a solution like the one on MariaDB chart? As you can check on the [values.yaml](https://github.com/kubernetes/charts/blob/master/stable/mariadb/values.yaml) there's a **"usePassword:"** parameter that allows to configure the chart so it accepts empty passwords.

**Comment by eldada** [comment]
@juan131 - that looks like a good, simple solution.

**Comment by juan131** [comment]
I have been checking the Image configuration. When using an empty value for both **MONGODB_PRIMARY_ROOT_PASSWORD** and **MONGODB_PRIMARY_ROOT_PASSWORD**, instead of setting an empty password for user **"root"**, it disables authentication on MongoDB configuration:

```
# security options
security:
  authorization: disabled
  #keyFile: replace_me
```

Therefore, you can access with all privileges just using the Mongo Shell as shown below:

```
mongo
```

Is that valid for you?

**Comment by juan131** [comment]
Hi @eldada I just created this PR to fix this issue on the chart: https://github.com/kubernetes/charts/pull/5159

Please feel free to comment/review it.

**Comment by juan131** [comment]
@eldada the PR was merged on the official MongoDB chart. Could you please take a look and let us know if that solves your issue?

**Comment by eldada** [comment]
Great! Looks good. I will test it early next week. Closing. Thanks for the quick fix!
