### ISSUE TITLE
Feature Request: SSL Transport Encryption support

### ISSUE THREAD

**Issue by dtzar** [bitnami/bitnami-docker-mongodb#95]
It would be great to have the ability to run this container with [SSL/TLS transport encryption](https://docs.mongodb.com/manual/core/security-transport-encryption/).  I would deem this essential to run this workload in a production capacity.  With some hacking, I'm sure it could be done but would be fantastic to have "built-in" support (like you do already for replica set, admin password, etc).

**Comment by cliffcotino** [comment]
Are there currently any plans to be able to support this feature?

**Comment by cliffcotino** [comment]
We are starting the primary with options:
```
MONGODB_EXTRA_FLAGS = "--sslMode=requireSSL \
--sslPEMKeyFile=/secrets/cert.pem \
--sslClusterFile=/secrets/cert.pem \
--sslCAFile=/secrets/ca.pem \
--sslAllowConnectionsWithoutCertificates \
--clusterAuthMode x509"
```

But it seems that the secondaries fail to add themselves to the replicaset because the command used to connect to the master do not contain the correct arguments.
In our case the extra arguments would need to be:
```--ssl --sslPEMKeyFile=/secrets/cert.pem --sslCAFile=/secrets/ca.pem"```

Is it possible to add this as extra functionality in the `/.nami/components/com.bitnami.mongodb/` scripts?

We would be happy to provide Pull Requests to be able to support this.

**Comment by tompizmor** [comment]
@cliffcotino We are in the middle of a refactoring of the MongoDB image. We are rewriting all the initialization logic from javascript (nami scripts) to bash.  

Once we release the new container, you will see all the bash logic in the repo so it will be much easier for you to see how it is being configured and send a PR.

Until now, the initialization logic was shipped into the image but was not published in any repo so it was not possible to send PR.

**Comment by cliffcotino** [comment]
Nice improvement, it took some digging indeed to find out what the actual problem was.
Are there any estimations regarding timelines for these changes?

**Comment by tompizmor** [comment]
@cliffcotino We are in the testing step so unless we found something wrong, probably we will release it this week or the next one.

**Comment by cliffcotino** [comment]
We've created a pull request #161 to be able to support SSL/TLS

**Comment by sameersbn** [comment]
Thanks for the contribution @cliffcotino. The PR has been merged and the infrastructure providing this feature will be available in the next build of the image. :tada:
